### ISSUE TITLE
Proposta di tesi s272985

### ISSUE THREAD

**Issue by LorenzoRvll** [TdP-prove-finali/Introduzione#100]
### Studente proponente
s272985 Ravalli Lorenzo

### Titolo della proposta
Turni 24H. Software per la gestione di turni. (eventualmente da modificare)

### Descrizione del problema proposto
Con la proposta si mira a risolvere il problema dell’assegnazione a turno mensile dei vari dipendenti, in un contesto lavorativo che prosegue per 24 ore. 

### Descrizione della rilevanza gestionale del problema
La rilevanza gestionale del problema è molto considerevole. Qualunque azienda si trova ad affrontare il problema di assegnare i propri dipendenti in vari turni. Molte di queste richiedono un’alternanza dei dipendenti nell’arco delle 24 ore. Ad esempio aziende con macchinari in funzione h24, stazioni di polizia o infermieri negli ospedali.

### Descrizione dei data-set per la valutazione	
Il data-set utilizzato sarà creato da me per simulare il caso di un reparto realistico di un azienda. Conterrà una tabella riepilogativa di tutti i dipendenti, con info generali su ognuno di esso, e una tabella relativa ai vari giorni di non disponibilità per ogni dipendente (es. ferie o alto).

### Descrizione preliminare degli algoritmi coinvolti	
Il software si baserà su una ricorsione che analizzando i vari vincoli troverà la migliore soluzione possibile per gestire i turni. I vincoli saranno relativi al sovraccarico di lavoro (es. se notte smonto, se pomeriggio non mattina, ogni 5 giorni 2 di riposo ecc.).
Vi sarà una classe che rappresenta i dipendenti (dal dataset), una i vari turni (creati su una lista in base alle opzioni scelte dall’utente). La ricorsione assegna a ogni turno un dipendente disponibile creando una lista di accoppiamenti (una nuova classe). I dipendenti disponibili verranno segnalati da un metodo che valuta i vincoli, e casualmente li ordina.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	
Il programma proporrà una finestra di gestione per i dipendenti, quindi relativi al dataset,  dove sarà possibile indicare per dipendenti i vari giorni di non disponibilità/ferie, potrei implementare anche l’aggiunta o a modifica del dataset dei dipendenti.
Una finestra per il calcolo dei turni, con alcune opzioni, come quanti dipendenti per turno (es. 2 mattina 1 pomeriggio 1 notte), il mese nel quale si vogliono calcolare i turni e magari un’opzione per rendere possibile gli straordinari (che eliminerebbe alcuni vincoli).
Una finestra riepilogativa con gli eventuali turni calcolati per dipendente. 
Infine una parte dedicata ai responsi, con alcune valutazioni, ad esempio se con i turni richiesti tutti lavorano le ore necessarie,  vi è una carenza di personale ecc.

**Comment by fulcorno** [comment]
Il problema è interessante e rilevante, ed algoritmicamente adatto (anche rischia di essere computazionalmente molto oneroso se affrontato con ricorsione pura).

Vedo un po' critica la costruzione 'a mano' del database con le disponibilità, in quando operazione molto noiosa, ed un po' arbitraria. Sarebbe meglio riuscire ad utilizzare dei dati reali da qualche azienda o da qualche benchmark pubblico... ad esempio ho trovato questo <http://www.schedulingbenchmarks.org/>, prova a vedere se ti può servire (o qualcosa di analogo).

Nel lavoro non è richiesta la "finestra per la gestione per i dipendenti", che sarebbe molto lunga da implementare e non aggiungerebbe nulla dal punto di vista algoritmico.

Riguardo al problema di ottimizzazione, bisogna fare attenzione non solo ai vincoli (doverosi) ma anche alle funzioni obiettivo: tutti devono lavorare un certo numero di ore min/max, non ci devono essere eccessive disparità, ecc ecc. Occorre formalizzarli per bene. Spesso sono obiettivi che si possono misurare solo su base temporale "lunga", almeno alcuni mesi, il che complica ovviamente l'algoritmo.

Fammi sapere cosa pensi in merito ai dati in input, così possiamo procedere.

**Comment by LorenzoRvll** [comment]
Per quanto riguarda il database accolgo il suo suggerimento in merito al sito (http://www.schedulingbenchmarks.org/), prenderò in esame uno dei dataset proposti (Ho in mente il dataset riguardanti turni per 4 settimane 18 dipendenti 3 turni per giorno). Rimuovo dai piani la finestra per la gestione dipendenti. E per quanto riguarda le funzioni obiettivo l'algoritmo proverà a generare dei turni più equi in base al lasso temporale del dataset. Eventuali disparità verranno segnalate nella parte finale dedicata ai responsi.

**Comment by fulcorno** [comment]
Va bene, riesci a scrivermi qui sotto la proposta complessiva, con le modifiche che proponi?

**Comment by LorenzoRvll** [comment]
### Studente proponente

s272985 Ravalli Lorenzo

### Titolo della proposta

Turni 24H. Software per la gestione di turni. 

### Descrizione del problema proposto

Con la proposta si mira a risolvere il problema dell’assegnazione a turno mensile dei vari dipendenti, in un contesto lavorativo che prosegue per 24 ore. 

### Descrizione della rilevanza gestionale del problema

La rilevanza gestionale del problema è molto considerevole. Qualunque azienda si trova ad affrontare il problema di assegnare i propri dipendenti in vari turni. Molte di queste richiedono un’alternanza dei dipendenti nell’arco delle 24 ore. Ad esempio aziende con macchinari in funzione h24, stazioni di polizia o infermieri negli ospedali.

### Descrizione dei data-set per la valutazione	

Per quanto riguarda il database utilizzerò uno di quelli proposti dal sito: "http://www.schedulingbenchmarks.org/". Prenderò in esame uno dei dataset proposti riguardanti turni per 4 settimane, con 18 dipendenti per 3 turni di lavoro al giorno. Il dataset avrà una tabella riguardante i dipendenti con orari di lavoro richiesti min e max, una tabella sui turni effettivi durante il mese, una tabella per la gestioni dei giorni “off” di non disponibilità, e dei giorni di richiesta turno per i vari dipendenti.

### Descrizione preliminare degli algoritmi coinvolti	

Il software si baserà su una ricorsione che analizzando i vari vincoli troverà la migliore soluzione possibile per gestire i turni. I vincoli saranno relativi al sovraccarico di lavoro (es. se notte smonto, se pomeriggio non mattina, ogni 5 giorni 2 di riposo ecc.). SI cercherà anche di rispettare i day off e le varie richieste dei dipendenti ove possibile. Inoltre tutti dovranno rispettare il numero di ore min/max cercando di evitare le disparità.
Vi sarà una classe che rappresenta i dipendenti (dal dataset), una i vari turni (creati su una lista in base alle opzioni scelte dall’utente). La ricorsione assegna a ogni turno un dipendente disponibile creando una lista di accoppiamenti (una nuova classe). I dipendenti disponibili verranno segnalati da un metodo che valuta i vincoli, e casualmente li ordina.


### Descrizione preliminare delle funzionalità previste per l’applicazione software	

Il programma proporrà una finestra per il calcolo dei turni, con alcune opzioni come la possibilità di escludere a priori le richieste di turni dei dipendenti.
Una finestra riepilogativa con gli eventuali turni calcolati per dipendente. 
Infine una parte dedicata ai responsi, con alcune valutazioni, ad esempio se con i turni richiesti tutti lavorano le ore necessarie,  vi è una carenza di personale ecc.

**Comment by fulcorno** [comment]
ok, proposta accettata
