### ISSUE TITLE
Proposta di tesi s284429

### ISSUE THREAD

**Issue by mattiaghigo7** [TdP-prove-finali/Introduzione#103]
### Studente proponente

S284429 Ghigo Mattia

### Titolo della proposta

Applicazione per la creazione di un itinerario turistico nella città di Torino

### Descrizione del problema proposto

Il problema riguarda la creazione di un itinerario nella città di Torino. Partendo da un albergo, scelto in funzione di quelli presenti all’interno di una lista creata in base alle richieste dell’utente, l’applicazione creerà un cammino passante tra vari punti di interesse (quali possono essere chiese, monumenti, teatri e molto altro) che rispetti i filtri inseriti ed altri vincoli preimpostati (ad esempio per evitare un elevato quantitativo di luoghi dello stesso genere). 

### Descrizione della rilevanza gestionale del problema

Dal punto di vista gestionale, l’applicazione creata potrà risultare utile alle aziende operanti nel settore turistico, che grazie ad esso, potranno minimizzare il tempo necessario per la programmazione di un itinerario e massimizzare così i profitti, potendo soddisfare un numero di clienti più elevato. Inoltre, risulterebbe utile anche al singolo utilizzatore, che non dovrà ricercare su decine di siti differenti che cosa vedere, quando e come. Per quanto riguarda la pianificazione di un viaggio, infatti, è spesso difficile scegliere con cura i luoghi di interesse, dato che, la posizione dell’albergo influisce sui luoghi visitabili.

### Descrizione dei data-set per la valutazione	

I data-set utilizzati nel progetto derivano dal sito aperTO, ovvero il portale del comune di Torino contenente diversi dati riguardanti la città.
Riporto di seguito la lista dei database utilizzati con relativi link:
alberghi (http://aperto.comune.torino.it/dataset/alberghi-2020)
chiese (http://aperto.comune.torino.it/dataset/chiese-e-altri-luoghi-di-culto)
luoghi storici (http://aperto.comune.torino.it/dataset/luoghi-storici)
musei (http://aperto.comune.torino.it/dataset/musei)
teatri (http://aperto.comune.torino.it/dataset/teatri)
I data-set relativi ai luoghi da visitare potrebbero venire uniti, al fine di creare un unico database complessivo contenente tutti i luoghi di interesse, riporterebbe un attributo aggiuntivo che specifica la classe di appartenenza (chiese, luoghi storici, musei, teatri e così via) per un migliore filtraggio.
Verrebbero aggiunti, a mano, altri luoghi particolari che meritano di essere citati. Inoltre, verrebbe effettuato un attento controllo, al fine di eliminare tuple superflue (come, ad esempio, nel database relativo agli alberghi, dove sono presenti strutture fuori Torino), completare i campi lasciati vuoti (in alcuni casi, ad esempio, non sono presenti le informazioni relative alle coordinate, campo molto utile per la creazione del grafo) ed altre piccole migliorie utili.

### Descrizione preliminare degli algoritmi coinvolti	

Innanzitutto, mediante un algoritmo di ricerca, il software genererà una lista di alberghi che rispetti le preferenze espresse dall’utente, ad esempio il budget, le stelle dell’albergo, se è permesso l’ingresso ai cani e così via. Successivamente alla selezione dell’albergo, sarà possibile selezionare delle preferenze per la futura creazione dell’itinerario (tipologia di luoghi che si desidera visitare, distanza totale che si è disposti a percorrere), a scelta avvenuta un algoritmo creerà un grafo tenendo conto dell’hotel e dei luoghi che rispettano i filtri. Il grafo generato avrà come vertici i luoghi visitabili e l’albergo (che sarà il punto di partenza dell’itinerario), e come archi i tragitti da un luogo ad un altro, pesati in base alla distanza calcolata tramite le coordinate. Infine, tramite un algoritmo ricorsivo, si calcolerà l’itinerario migliore, ovvero quello con il maggior numero di luoghi che rispettino le scelte dell’utente. 

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’utente avrà a disposizione un’interfaccia dove dovrà effettuare delle scelte, in funzione delle quali verrà popolata una tendina contenente gli alberghi disponibili per la selezione. Successivamente si abiliteranno ulteriori campi per il filtraggio dei luoghi di interesse che si intende visitare, oltre ad un campo che permetta di inserire la distanza che si è disposti a coprire. A scelte effettuate, verrà visualizzato l’elenco rappresentante l’itinerario, in un’area testuale, con tutte le informazioni necessarie.

**Comment by fulcorno** [comment]
Il data-set è molto interessante ed il dominio applicativo è valido.
Non mi convince molto il criterio di ottimizzazione (se ho capito bene: max del numero di luoghi visitati con il vincolo della distanza massima totale). Credo che più che la distanza, possa essere rilevante il tempo. Ed il tempo dovrebbe comprendere sia il tempo di spostamento, che il tempo di visita (si riesce a stimare?). Altrimenti stiamo creando dei percorsi turistici "a staffetta", in cui devo solo "toccare" i vari monumenti e ripartire in tempo zero.
Cosa ne pensi?
Ultimo suggerimento: forse i filtri espressi dall'utente si possono configurare come "livelli di gradimento", non semplicemente "si/no", altrimenti diventa poco interessante la ricerca.
(nota; povera Basilica di Superga, non la visiterà mai nessuno...)

**Comment by mattiaghigo7** [comment]
Effettivamente il tempo potrebbe essere più adatto alla creazione dell'itinerario, il tempo per lo spostamento tra 2 luoghi lo potrei calcolare in funzione della loro distanza, mentre per quanto riguarda il tempo di visita lo potrei cercare sul Web, e nel caso non riesca a trovarlo potrei stimarlo in base alla durata della visita di luoghi simili.
Per i filtri potrei far scegliere all'utente dei valori (ad esempio da 1 a 5), in base alle proprie preferenze, e successivamente pesarli in funzione della distanza dall'albergo di partenza, in tal modo il turista potrebbe visitare anche luoghi che meno lo attraggono, ma che essendo molto vicini all'hotel potrebbe valer la pena di visitare (ovviamente verrebbe messo un limite per tali luoghi, al fine di non fargli passare la vacanza in luoghi indesiderati).
La mia idea era di creare un itinerario fattibile a piedi, trovo che molti turisti, soprattutto ultimamente, viaggiano spesso in treno, questo purtroppo però esclude la visita a luoghi fuori mano (come purtroppo è Superga).

**Comment by fulcorno** [comment]
ok, con i chiarimenti forniti, la proposta è accettata.
Ti chiederei di aggiornare la descrizione iniziale integrandola con queste nuove scelte.
