### ISSUE TITLE
Proposta tesi s268947

### ISSUE THREAD

**Issue by Matta-Riccardo** [TdP-prove-finali/Introduzione#107]
### Studente proponente

s268947 Matta Riccardo

### Titolo della proposta

Pianificazione delle vacanze nella regione Puglia e gestione delle strutture ricettive e dei luoghi di interesse.

### Descrizione del problema proposto

Il problema proposto consiste nella programmazione delle vacanze nella regione Puglia: sia nella scelta della struttura ricettiva che nelle attività e nei luoghi di interesse da poter visitare, con la possibilità di fornire la sistemazione e il programma più indicato a seconda delle preferenze espresse in fase preliminare dal viaggiatore.
Con la possibilità di consigliare al viaggiatore anche la località più adatta alle sue esigenze, ad esempio se esso non conosce i vari paesi ma vuole soggiornare in una località di mare.

L'idea poi è anche quella di aggiungere una parte per la gestione delle strutture ricettive con la possibilità di aggiunta e modifica dei vari dati, in modo da tenere sempre aggiornata la situazione.

### Descrizione della rilevanza gestionale del problema

Tale applicazione è utile per i viaggiatori che intendono recarsi in Puglia, evitando a questi ultimi di mettersi a fare tante ricerche separate ma venendo assistiti e guidati sia nella scelta della sistemazione che nelle varie attività da fare, in modo tale da soddisfare al meglio le loro richieste e a garantirgli un ottima esperienza già a partire dalla scelta della loro destinazione. Inoltre sarà prevista una parte a sostegno dei vari albergatori dove poter modificare i dati riguardanti le loro strutture e poter inserire anche nuove strutture ricettive, in maniera analoga sarà possibile anche gestire i vari luoghi di interesse con possibilità di aggiunta e modifica.

### Descrizione dei data-set per la valutazione	

I database utilizzati sono stati recuperati dal sito DatiOpen.it (una banca dati di open data) e più in particolare nella sezione turismo: 

http://www.datiopen.it/it/opendata/Regione_Puglia_Strutture_ricettive
http://www.datiopen.it/it/opendata/Regione_Puglia_Luoghi_di_interesse_turistico_culturale_naturalistico

In una fase preliminare ho anche in parte corretto qualche mancanze nei dati per poterli successivamente utilizzare al meglio.

Inoltre per una gestione più precisa delle varie località ho creato un piccolo database con le varie coordinate geografiche di tutte le località pugliesi, tali dati sono stati importati dal sito www.dossier.net (ad esempio per le coordinate delle località presenti nella provincia di Bari https://www.dossier.net/utilities/coordinate-geografiche/provincia-bari.htm)
 

### Descrizione preliminare degli algoritmi coinvolti	

La ricerca della struttura ricettiva come base richiede il numero di ospiti, evitando così di suggerire sistemazioni che non abbiano un numero sufficiente di posti letto, dopo di ché sarà possibile scegliere la tipologia di struttura tra quelle presenti e ovviamente la località in caso questa sia già stata decisa. In alternativa sarà possibile esprimere una serie di preferenze (provincia nella quale cercare, se località di mare, località di entroterra e località di entroterra ma vicino al mare) e farsi consigliare dal programma la destinazione con le varie strutture trovate.
Al contempo verrà fornito un programma da poter seguire attraverso la creazione di un grafo: verranno trovati i luoghi nelle vicinanze della località di soggiorno inserendo una distanza max nella quale cercare e una serie di preferenze (tali luoghi trovati rappresenteranno i vertici di tale grafo) e verrà calcolato l'itinerario da percorrere che maggiormente soddisfi le preferenze espresse.
Infine tramite comandi di INSERT INTO, UPDATE o DELETE sarà possibile gestire le info riguardati sia le strutture ricettive che i luoghi di interesse.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione presenterà una sezione per la pianificazione delle vacanze sempre disponibile e abilitata e una sezione per la gestione delle strutture e dei luoghi di interesse abilitabile tramite l'inserimento di una password specifica.
La ricerca della struttura è resa possibile tramite la compilazione di alcuni campi e di scelte operate attraverso dei menu a tendina, dopo di che verrà popolata una tabellina con i vari risultati trovati e le rispettive informazioni.
Individuata poi la località sarà possibile la creazione del grafo con i vari luoghi di interesse, sarà necessario inserire una distanza max entro la quale cercare e ulteriori preferenze sulle varie attività e verrà così visualizzato l'itinerario migliore possibile.

**Comment by fulcorno** [comment]
Il problema affrontato è sicuramente rilevante, ed il data-set è adeguato (anche se forse le informazioni nei database linkati sono un po' troppo "sporche" e incomplete).

Mi sembra impossibile poter tenere conto del numero di posti disponibili nelle strutture, per il semplice motivo che possiamo conoscere la capienza totale, ma non l'occupazione attuale (o quella prevista in un certo giorno). Sono informazioni in possesso solo dei gestori delle strutture, e non mi pare credibile riuscire ad ottenerle.
Non è nemmeno credibile pensare che i gestori possano entrare con le loro credenziali nella tua applicazione.
Quindi suggerisco di eliminare quella parte e concentrarsi sul resto.

La parte restante, legata alla proposta di itinerari e luoghi di interesse, è più fattibile, ma attualmente è descritta in modo molto generico (non si capisce quali siano i criteri di ricerca, i vincoli, ecc.).

In definitiva, ti chiederei di inserire una nuova richiesta (questa la segno come non accettabile), espandendo/dettagliando meglio la parte di ricerca.
