### ISSUE TITLE
Generatore di build con gli emblemi di Pokemon Unite

### ISSUE THREAD

**Issue by ilM4rion** [TdP-prove-finali/Introduzione#112]
### Studente proponente

s281374 Marietti Andrea

### Titolo della proposta

Generatore di build con gli emblemi di Pokemon Unite

### Descrizione del problema proposto

Pokemon Unite è un videogioco del genere MOBA in cui due squadre si scontrano per segnare il maggior numero di punti nelle basi avversarie. I giocatori hanno a disposizione dei personaggi standard per tutti, ma di cui possono aumentare (o diminuire) i 7 parametri tramite degli emblemi ottenibili con l'avanzare del livello. 
Ogni emblema ha tre livelli: Bronzo, Argento e Oro. Più alto è il livello (dal metallo di meno valore al più prezioso) maggiori saranno le variazioni dei parametri, sia in positivo che in negativo. A livello di community, tuttavia, è caldamente sconsigliato utilizzare i livelli Bronzo e Argento, dati gli scarsi vantaggi che vengono forniti al giocatore.
La creazione di una combinazione di emblemi è complessa in quanto bisogna trovare la combinazione migliore dati 10 slot da riempire. L'applicazione avrà quindi lo scopo di facilitare la ricerca della combinazione migliore date delle richieste del giocatore tramite un algoritmo ricorsivo.

### Descrizione della rilevanza gestionale del problema

I parametri che gli emblemi vanno a modificare hanno un grande impatto nel gioco a livello competitivo, dove anche una piccola variazione può segnare l’esito di uno scontro; un personaggio improntato alla difesa, ad esempio, richiederà sicuramente elevati parametri difensivi, mentre potrà non necessitare di rilevante velocità di movimento. 
Nell’ambito gestionale, la ricerca di una soluzione che massimizza un parametro non è da considerarsi sempre come la soluzione migliore, ma fornisce informazioni utili per avere una stima dei vantaggi e degli svantaggi che conseguono ad una serie di scelte combinate tra loro.

### Descrizione dei data-set per la valutazione	

Non esistendo un data-set scaricabile con tutte le informazioni, i dati sono ottenuti effettuando webscraping  dal sito: https://game8.co/games/Pokemon-UNITE/archives/383688. Per effettuare questo procedimento è stata usata una estensione per browser basati su Chromium chiamata “Web Scraper”, che permette di estrarre le informazioni in automatico previa specifica degli elementi HTML in cui presenti e di inserirle in un file csv, facilmente convertibile in SQL.  
Il database è composto da un’unica tabella formata da cinque colonne:
-Name: è nome del Pokemon che identifica l’emblema;
-Color: è il colore dell’emblema;
-Bronze, Silver, Gold: per ogni colonna sono indicati  sia il parametro che viene aumentato sia quello viene diminuito.

### Descrizione preliminare degli algoritmi coinvolti	

Per effettuare la ricerca della combinazione richiesta è necessario utilizzare un algoritmo ricorsivo con vari filtri al fine di soddisfare tutte le richieste. 
Verranno proposte all’utente due opzioni per la creazione della build: automatica e manuale.
Nella prima, l’utente può scegliere il parametro da massimizzare e, se desidera, un parametro da non portare a valore negativo. In questo caso l’algoritmo ricorsivo partirà con un insieme parziale vuoto e dovrà, quindi, esplorare tutte le possibili combinazioni. Mentre nel secondo caso sarà possibile scegliere manualmente un numero a piacere di emblemi (fino a 10) e il parametro che si vuole massimizzare. L’insieme parziale partirà con al suo interno gli emblemi scelti e l’algoritmo si occuperà di completare nel modo migliore la combinazione.
Per permettere entrambe le opzioni senza intaccare l’esperienza dell’utente, si sfrutta il polimorfismo, ovvero verranno create due funzioni omonime che implementano un algoritmo ricorsivo identico se non per piccole variazioni dettate dalla differenza dei parametri di input.
Il problema principale è processare tutte le possibili combinazioni dati 233 emblemi e 10 posizioni. I tempi di esecuzione sarebbero molto grandi, data l’elevata quantità di risorse richieste. Per ovviare a questo problema si potrebbero usare dei parametri di soglia che devono necessariamente essere superati prima del completamente della combinazione, al fine di scartare tutte le combinazioni che non soddisfano gli standard richiesti.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione avrà una interfaccia semplice e minimale. Saranno presenti due schede, una per l’opzione manuale e una per quella automatica, così da prevenire ogni possibile errore dell’utente. In entrambe le schede, sotto le opzioni di scelta, sarà presente un’area di testo in cui verrà mostrato l’output composto dall’elenco degli emblemi scelti e dal calcolo dei valori ottenuti.
Nella schermata per l’opzione automatica saranno presenti due comboBox; una per la scelta del parametro da massimizzare e una, il cui utilizzo è a discrezione dell’utente, per selezionare il parametro da non modificare sotto lo zero. Nell’altra, invece, sarà sempre presente una comboBox per massimizzare una statistica, ma anche altre 10 per permettere all’utente di scegliere manualmente gli emblemi. 
Viene ipotizzata la possibilità di utilizzare questa funzione anche solo per calcolare rapidamente il risultato ottenibile e quindi vengono lasciate 10 opzioni per l’inserimento dei dati, rendendo di fatto inutile la comboBox per il parametro da massimizzare.

**Comment by fulcorno** [comment]
La proposta è accettabile sia dal punto di vista applicativo che algoritmico.
Una cosa che non ho capito, è se un giocatore possa disporre sempre di tutti i 233 emblemi, oppure se le disponga di un sotto-insieme e debba trovare la migliore combinazione tra di essi. Se così fosse, si risolverebbero 2 problemi: l'algoritmo sarebbe più "vario" perché ciascun giocatore avrebbe soluzioni diverse, e l'algoritmo sarebbe anche più rapido perché si ridurrebbe lo spazio di ricerca.
(nota: in caso di problemi prestazionali, si potrebbe anche ridurre il numero di emblemi ad un valore inferiore a 10)

**Comment by ilM4rion** [comment]
Nel mio prototipo avevo ipotizzato avesse a disposizione la totalità degli emblemi, però potrebbe essere più realistico ipotizzare che si parta da un sottoinsieme casuale, dato che soltanto gli utenti con più ore di gioco li riescono ad avere tutti, e si cerchi la soluzione migliore partendo da quello. Per quanto riguarda i 10 slot, se impiega troppo, proverò a ridurre; dipende da quanto grande farò il sotto insieme. Nel prototipo attuale si otteneva la risposta più complessa in circa 25secondi quindi vorrei non peggiorare le prestazioni
