### ISSUE TITLE
Richiesta disponibilità relatore tesi

### ISSUE THREAD

**Issue by alezemelo** [TdP-prove-finali/Introduzione#113]
### Studente proponente

s283260 Alessandro Boscolo Zemelo

### Titolo della proposta

Simulazione dell'interazione dell'utente alla playlist creata in base a specifici gusti musicali

### Descrizione del problema proposto

Creazione di una simulazione in cui viene generata una playlist tramite algoritmo ricorsivo in base alle caratteristiche specificate inizialmente (caratterizzanti anche il db che si vuole utilizzare). Tale playlist viene utilizzata per valutare dopo quanti minuti l'utente abbandona la piattaforma, Il criterio di uscita potrebbe essere: playlist terminata, nessun ascolto dopo 5 m ecc.. 
La simulazione potrebbe essere applicata a più profili utente: se la playlist è generata nel genere rock, si potrebbero creare profili utente di generi affini al rock, come l'alternative rock, blues-rock, tutti con diverse probabilità di ascoltare una canzone della playlist.

### Descrizione della rilevanza gestionale del problema

L'interesse gestionale del problema è capire come trattenere maggiormente l'utente nella piattaforma creando un'ambiente di suggerimento musicale tale da non poter andare da compagnie concorrenti, ovvero brandizzare l'utente.

### Descrizione dei data-set per la valutazione	

Avevo notato l'applicabilità del mio problema a tale db: https://www.kaggle.com/datasets/nelgiriyewithana/top-spotify-songs-2023
con i seguenti campi:
- track_name: Name of the song
- artist(s)_name: Name of the artist(s) of the song
- artist_count: Number of artists contributing to the song
- released_year: Year when the song was released
- released_month: Month when the song was released
- released_day: Day of the month when the song was released
- in_spotify_playlists: Number of Spotify playlists the song is included in
- in_spotify_charts: Presence and rank of the song on Spotify charts
- streams: Total number of streams on Spotify
- in_apple_playlists: Number of Apple Music playlists the song is included in
- in_apple_charts: Presence and rank of the song on Apple Music charts
- in_deezer_playlists: Number of Deezer playlists the song is included in
- in_deezer_charts: Presence and rank of the song on Deezer charts
- in_shazam_charts: Presence and rank of the song on Shazam charts
- bpm: Beats per minute, a measure of song tempo
- key: Key of the song
- mode: Mode of the song (major or minor)
- danceability_%: Percentage indicating how suitable the song is for dancing
- valence_%: Positivity of the song's musical content
- energy_%: Perceived energy level of the song
- acousticness_%: Amount of acoustic sound in the song
- instrumentalness_%: Amount of instrumental content in the song
- liveness_%: Presence of live performance elements
- speechiness_%: Amount of spoken words in the song

### Descrizione preliminare degli algoritmi coinvolti	

I principali problemi algoritmici saranno l'identificazione della playlist da sottoporre alla simulazione tramite ricorsione sui parametri inseriti dall'utente e la scelta dei criteri di uscita dalla simulazione e la definizione di "tempo" che non dovrà corrispondere al "tempo reale" in quanto richiederebbe troppo per ottenere un output Infine, un ultimo problema potrebbe essere la determinazione del profilo utente. Riguardo questo ultimo problema si potrebbe includere un altro db nel quale si ricava il profilo di diversi utenti in base all'utenteID: https://www.kaggle.com/datasets/andrewmvd/spotify-playlists?select=spotify_dataset.csv

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente tramite l'interfaccia grafica potrà visualizzare la playlist generata sui parametri da lui scelti (come denceability, numero di brani ecc..) e potrà simulare in base a diversi profili utente proposti quanto l'utente si trova affine e quindi quanto viene trattenuto nell'applicazione.

**Comment by fulcorno** [comment]
L'ambito applicativo ed il data-set selezionato vanno bene.

La proposta però mi pare ancora molto generica dal punto di vista delle funzionalità e degli algoritmi.
In che senso si intende generare ricorsivamente una playlist? con il numero di brani presenti, non credo che una soluzione ricorsiva sia fattibile.
Nella fase di simulazione, poi, non mi è chiaro come si determini l'ascolto (o l'abbandono) dei brani: avendo una playlist generata a partire da certi criteri, con quali (altri?) criteri si simula il comportamento dell'utente?

Ti chiederei di chiarire meglio questi due aspetti: come creare la playlist in un tempo di esecuzione accettabile, e quali siano i meccanismi della simulazione.
