### ISSUE TITLE
L’industria cinematografica e la ridistribuzione dei suoi ricavi

### ISSUE THREAD

**Issue by ludofalcone** [TdP-prove-finali/Introduzione#115]
### Studente proponente

S258777 Ludovica Falcone

### Titolo della proposta

L’industria cinematografica e la ridistribuzione dei suoi ricavi

### Descrizione del problema proposto

“Come è possibile che il cinema sia un mercato in crisi se i film fatturano milioni di dollari ogni giorno?”
Lo scopo del progetto è rispondere a questa domanda andando ad analizzare l’andamento del box-office statunitense dal 1995 al 2022 inserendolo in una simulazione che tiene conto dei possibili accordi commerciali stipulati tra case di produzione, distributori ed esercenti cinematografici, del budget stanziato e del numero di settimane di programmazione dei film nelle sale. Il risultato è una stima del guadagno delle case di produzione e dei distributori per uno specifico film e il guadagno totale in un anno solare.

### Descrizione della rilevanza gestionale del problema

Il cinema statunitense è leader nell’industria cinematografica: rappresenta infatti il maggior produttore di contenuti audiovisivi destinati al rilascio nelle sale di tutto il mondo. 
Studi affermano che nel 2022 desse lavoro a circa 700.000 persone in California e a 180.000 a New York, pari al 5% della forza lavoro di entrambi i territori.
Avendo un così grande impatto sia a livello lavorativo che culturale, è importante capirne le dinamiche attraverso una simulazione della possibile ridistribuzione delle entrate al botteghino, dato che questi dati sono riservati e conseguenza di negoziazioni interne alle aziende. Questo strumento può essere utile ai fini di analisi di mercato e può indirizzare coloro che vogliono muovere i primi passi nell’industria cinematografica, come giovani filmmakers e case di produzione indipendenti, dando loro un quadro, seppur semplificato ma frutto di ricerche, dell’andamento del flusso di guadagni negli ultimi anni.

### Descrizione dei data-set per la valutazione	

Il database è da costruire su dati reperibili nel sito The Numbers. 
 https://www.the-numbers.com/market  -  https://www.the-numbers.com/movies/production-companies  -  https://www.the-numbers.com/market/distributors 
Quest’ultimo si occupa di tener traccia dei più importanti dati finanziari del mercato cinematografico ed è in costante aggiornamento.
Si andranno a prendere in esame le cento maggiori compagnie di produzione cinematografica statunitensi con i rispettivi film rilasciati dal 1995 al 2022 e distribuiti sul territorio americano da un determinato distributore. 
Ci sarà una tabella dedicata ai film composta da undici colonne, una alle case di produzione e una ai distributori. Per semplificazione, tratteremo gli esercenti come ente unico, anche se nella realtà sono i responsabili di una qualsiasi sala cinematografica.
Ogni film avrà indicato un codice univoco, il titolo, la casa di produzione, il distributore, il budget investito, il box-office globale, l’anno di rilascio e gli incassi per le prime quattro settimane in cui è stato in programmazione. Dato che il calcolo dei guadagni dalla quarta settimana in poi è lo stesso, questa colonna visualizzerà la differenza tra il box-office totale e gli incassi delle prime tre settimane dopo il rilascio.
Ogni casa di produzione verrà identificata da un codice univoco e dal nome.
Ogni distributore avrà un codice univoco e il nome.

### Descrizione preliminare degli algoritmi coinvolti	

L’algoritmo coinvolto è l’algoritmo di simulazione.
Dopo aver selezionato un film tramite un sistema di filtraggio basato sull’anno di rilascio, è possibile iniziare la simulazione basandosi su due valori di input scelti dall’utente. 
Il primo riguarda l’accordo tra casa di produzione e distributore e può essere di due tipi: leasing e profit-sharing.
Nel leasing, il distributore paga una somma fissa per acquistare i diritti di distribuzione del film. Supponiamo che tale somma sia uguale al 125% del budget speso.
Nel profit-sharing, casa di produzione e distributore dividono la loro quota in una proporzione 80-20, risultato della precedente ridistribuzione avvenuta con l’esercente, che analizzeremo in seguito. L’80% è della casa di produzione e il suo guadagno si calcola sottraendo a tale cifra il budget speso per il film.  Al distributore va il 20%. Queste cifre non tengono conto dei costi di marketing e pubblicizzazione del film, dato che essi non sono reperibili.
Il secondo valore di input delinea l’accordo tra distributore ed esercente cinematografico. Anche in questo caso, ce ne sono di due tipi: sliding scale e bidding.
Nel sliding scale, la percentuale di ridistribuzione dei guadagni dipende dal numero di settimane di programmazione del film nelle sale. Infatti, nella prima settimana il 95% degli incassi al botteghino appartiene alla casa di distribuzione, nella seconda il 90%, nella terza l'85% e dalla quarta in poi il rapporto subisce una brusca variazione arrivando ad un 50%. 
Nel bidding, tale percentuale è fissa ed è uguale al 95%, con il 5% destinato all'esercente. 
Il guadagno del distributore è poi da dividere, come precedentemente specificato, con la casa di produzione. 
Lo stesso procedimento può essere applicato se si è interessati al guadagno di una casa di produzione o di un distributore specifici, analizzando tutti i film che ha prodotto o distribuito rilasciati nell’anno selezionato.
Nel caso dello studio della singola casa di produzione, si stima un ulteriore valore che tiene traccia dell’utile generato, così da rendere più evidente l'entità del guadagno. 

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

Nella parte superiore dello schermo, ci sarà una text area in cui saranno brevemente spiegati i tipi di accordi tra casa di produzione, distributore ed esercente.
Si avrà una combo box con l’elenco degli anni dal 1995 al 2022 e l’utente è chiamato a scegliere un valore. Sullo schermo quindi comparirà l’elenco dei film rilasciati in tale anno, con affianco il nome della sua casa di produzione, il suo distributore e il suo budget.
Una combo box darà la possibilità di indicare uno dei film di questo elenco.
Successivamente, si potrà selezionare tramite due combo box i valori di calcolo dei guadagni: leasing o profit-sharing e sliding scale o bidding. Dopo aver cliccato un button, nella text area sottostante compariranno i guadagni risultanti della casa di produzione e del distributore.
Dopo aver cliccato su un button di reset, la text area verrà cancellata.
Pigiando un ulteriore button, comparirà a video il guadagno della casa di produzione del film selezionato in precedenza nell’anno scelto. Tramite un altro button, si potrà fare la stessa cosa ma analizzando il distributore.
L'utente sarà aiutato nella consultazione dell'interfaccia tramite la presenza di label esplicative.

**Comment by fulcorno** [comment]
La proposta è interessante e pertinente.

Visto che il cuore è la simulazione, e che il guadagno in ultima analisi dipende dal numero di spettatori, non sono riuscito a capire come intendi stimare/simulare il numero di spettatori di un determinato film, nelle varie settimane.
Inoltre non mi è chiaro se la simulazione prenderà in esame un solo film (e quindi processerà solo 4 eventi, uno per ciascuna settimana), oppure si considerano più film in contemporanea (che potrebbero anche 'interagire' tra loro) o una granularità temporale più fine.

**Comment by ludofalcone** [comment]
L'analisi non dipende dal numero di spettatori ma dagli incassi al botteghino. Sul sito dove prendo i dati c'è una differenziazione dell'incasso per ogni settimana: nelle prime tre settimane inserirò il valore reale in corrispondenza di ognuna, mentre nella quarta la somma di tutti gli incassi da quella settimana in poi, cioè la differenza tra il boxoffice totale e gli incassi delle prime tre settimane.
In una prima fase, prenderei in esame un film alla volta in base alle quattro possibili combinazioni di accordi tra casa di produzione, casa di distribuzione ed esercente. Gli incassi per settimana sono utili per uno solo di questi accordi, ovvero il sliding scale, dato che le percentuali di ridistribuzione variano proprio da settimana in settimana e non ce n'è una fissa. Lo scopo è calcolare quanto produttore e distributore abbiano guadagnato dal rilascio di quel film specifico..
In una seconda fase, è possibile calcolare il guadagno totale della casa di produzione e della casa di distribuzione del film scelto nell'anno selezionato all'inizio, analizzando tutti i film da loro prodotti o distribuiti sempre in base ai quattro accordi. Quindi si esegue lo stesso procedimento ma su "larga scala".
Spero di aver chiarito al meglio i Suoi dubbi e rimango disponibile ad apportare qualsiasi modifica per rendere più dinamico l'algoritmo.

**Comment by fulcorno** [comment]
Grazie per il chiarimento.
Scusa, ma mi sfugge ancora un aspetto.
Mi pare che il tipo di elaborazione che proponi non necessiti di una simulazione ad eventi, ma sia una semplice sommatoria (usando diverse formule di profit) di dati esistenti ed invariabili.
Cioè non mi pare che nell'elaborazione della quota di guadagno del film X nella settimana 3, il valore non dipenda né dai guadagni nella settimana 2, né dall'andamento del film Y.
A questo punto è inutilmente complesso impostare una simulazione ad eventi. 
Mi aiuti a capire cosa mi sta sfuggendo?

**Comment by ludofalcone** [comment]
Non Le sfugge niente, ha perfettamente ragione.
Il mio errore è stato nominarlo algoritmo di simulazione, quando nella pratica è un semplice algoritmo di ricerca.
Nel caso in cui non fosse accettabile, stavo pensando di implementare un algoritmo ricorsivo che costruisca una lista degli N film più remunerativi per le case di produzione nell'anno selezionato, basandosi sull'utile generato dai film prodotti. Il valore N è da far selezionare all'utente. 
A questo punto le analisi sarebbero quattro: guadagni del film specifico, guadagno nell'anno solare della casa di produzione, guadagno nell'anno solare del distributore e classifica.

**Comment by fulcorno** [comment]
Però anche in questo caso a che servirebbe la ricorsione?
Dato N, metto in ordine di incasso tutti i film dell'anno, e poi prendo i primi N...

**Comment by ludofalcone** [comment]
Sarebbe una lista di N film stampati in ordine di utile generato per le case di produzione e non di incasso, con il vincolo dell'anno di rilascio selezionato dall'utente in precedenza. Si può considerare come un dream team in cui si massimalizza l'utile.
Non è infatti detto che un film che abbia incassato molto al botteghino, abbia di conseguenza anche ritornato un profitto proporzionale ad esso. La classifica si baserebbe sul profit sharing e sullo sliding scale dato che sono i due accordi in cui la ridistribuzione dei guadagni è variabile. Le differenti percentuali di calcolo dello sliding scale aiutano proprio a sottolineare la "velocità" di guadagno del film: a parità di incasso, film X ritorna alla casa di produzione più di quanto faccia film Y perchè nelle prime tre settimane ha incassato maggiormente, anche se l'incasso totale a fine programmazione è il medesimo . 
Ho provato a fare un calcolo cartaceo prendendo in esame i film con maggiore incasso del 2019 e già le prime 6 posizioni ordinate in base all'utile non coincidono con quelle ordinate in base all'incasso: le percentuali sono molto diverse le une dalle altre dipendentemente dal budget e dagli incassi settimana per settimana. 
Al crescere di N, ovviamente la classifica sarebbe ancor più "imprevedibile".
