### ISSUE TITLE
Ottimizzazione del portafoglio finanziario

### ISSUE THREAD

**Issue by Chiara1995** [TdP-prove-finali/Introduzione#12]
### Studente proponente

s219345 Pizzato Chiara

### Titolo della proposta

Ottimizzazione del portafoglio finanziario

### Descrizione del problema proposto

L’applicazione desktop si propone di risolvere il problema relativo alla selezione degli investimenti per la scelta del portafoglio sulla base di determinati parametri fissati dall’utente (budget, rischio, rendimento e tempo). Si tratta di decidere in quali titoli e con quali quote investire i capitali disponibili in modo da massimizzare il ricavo atteso entro una determinata soglia di rischio oppure minimizzare il rischio entro una determinata soglia di rendimento minima. L’applicazione fornisce anche informazioni e indici economici relativi ai singoli titoli finanziari presenti nel data-set.

### Descrizione della rilevanza gestionale del problema

La definizione degli investimenti può riguardare sia un soggetto imprenditoriale nell’ambito della sua attività di impresa relativamente alla componente di liquidità, sia in senso esteso un privato cittadino nell’incremento della sua qualità di vita.
L’analisi dei possibili investimenti e le capacità di gestione sono fondamentali per la valutazione del portafoglio finanziario. Il problema affrontato dall’applicazione permetterà di creare un modello di simulazione di un sistema reale, raccogliere dati per la sperimentazione, analizzare i risultati in modo critico e valutare i flussi di investimento in scenari alternativi. L’obbiettivo principale è fornire all’utente uno strumento efficace per poter gestire il proprio capitale in base alle proprie esigenze e ai propri obbiettivi di guadagno e di possibile reinvestimento in attività imprenditoriali.
L’applicazione risponderà a tutte le attività che normalmente richiedono le capacità proprie dell’ingegnere gestionale nell’ambito dell’analisi degli investimenti: 
-capacità di individuare, valutare e gestire i principali rischi finanziari
-capacità di comprendere l'interazione tra l'andamento dei mercati finanziari, le opportunità di investimento e le scelte di struttura del capitale 
-analisi delle performance economico-finanziarie e dell'investimento
-definizione del portafoglio ottimale

### Descrizione dei data-set per la valutazione	

L’applicazione utilizzerà un data-set basato sulle informazioni del sito Finra (http://finra-markets.morningstar.com/BondCenter/Default.jsp) relative ad alcuni titoli a tasso fisso del mercato obbligazionario. 
Nella sezione Bond del Market Data Center sono riportate informazioni generali sul mercato obbligazionario degli Stati Uniti. L’applicazione si baserà su un sottoinsieme di titoli obbligazionari selezionati nelle categorie Corporate, Government e Municipal.
Ogni obbligazione è caratterizzata da un nome, un tasso d’interesse, una scadenza, un prezzo di mercato e un indice di rating assegnato da Moody’s.

### Descrizione preliminare degli algoritmi coinvolti	

L’applicazione permetterà di simulare la creazione di un portafoglio finanziario sulla base dei dati forniti in input dall’utente (capitale iniziale, rendimento, rischio, tempistiche e altri eventuali vincoli). Per la definizione del portafoglio verrà implementato un algoritmo di ricorsione che terrà conto dei vari vincoli alla base del problema. Dato l’elevato numero di titolo finanziari presenti nel database, sarà necessario ottimizzare al meglio l’algoritmo ricorsivo in modo da ridurre le tempistiche di calcolo del piano d’investimento ottimale (ad esempio verrà fissata una percentuale minima di possesso per ogni titolo in portafoglio).
Inoltre sarà possibile ottenere statistiche sui titoli finanziari tramite l’implementazione di algoritmi di ricerca.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’utente tramite l’applicazione potrà definire i parametri desiderati per la definizione del portafoglio finanziario. In particolare l’utente potrà definire il capitale iniziale disponibile, il rendimento atteso dall’investimento, il livello di rischio assunto, l’arco temporale e l’obbiettivo dell’investimento (massimizzazione dei ricavi considerato il rischio fornito come massimo livello o minimizzazione del rischio complessivo considerato il rendimento come valore minimo).
L’applicazione elaborerà i dati forniti in input dall’utente (vincoli del problema) per restituire l’allocazione ottimale finanziaria. L’utente potrà così ottenere informazioni su alcuni indici economici relativi al piano di finanziamento ottenuto e sulla diversificazione degli investimenti del portafoglio tramite grafici (diversificazione del rischio e dell’investimento). 
L’applicazione software permetterà all’utente di ricercare informazioni in merito ad un singolo titolo obbligazionario. Inoltre sarà possibile visualizzare l’elenco completo dei titoli presenti nel database su cui applicare eventualmente determinati filtri di ordinamento (per livello di rischio crescente, per rendimento crescente, per periodo).

**Comment by fulcorno** [comment]
L'argomento è rilevante e gli algoritmi sono adeguati ai contenuti del corso ed al tipo di dati trattati.
Questa proposta è accettata.
Cercherei di semplificare la realizzazione del software, ad esempio riducendo al minimo le funzioni accessorie (come ad esempio le info sul singolo titolo o l'elenco completo dei titoli, che non sembrano correlate con l'ottimizzazione del portafoglio).
