### ISSUE TITLE
Software per l’analisi statistica di sistemi energetici rinnovabili e valutazione degli investimenti per i clienti

### ISSUE THREAD

**Issue by AlexandraElenaHolota** [TdP-prove-finali/Introduzione#124]
### Studente proponente

s297022 Holota Alexandra Elena

### Titolo della proposta

Software per l’analisi statistica di sistemi energetici rinnovabili e valutazione degli investimenti per i clienti

### Descrizione del problema proposto

L’idea progettuale consiste nello sviluppo di un software capace di fornire un’analisi preliminare, specifica o generica, per quanto riguarda l’installazione di sistemi energetici rinnovabili e una soluzione per il cliente in termini di investimenti iniziali.  

L’analisi preliminare specifica avviene su una singola fonte rinnovabile, scelta dall’utente, rispetto alla quale verrano riportati i valori minimi, massimi e medi scelti tra le seguenti categorie:
- capacità installata in megawatt (MW);
- produzione annuale di energia in megawattora (MWh);
- ﻿﻿﻿consumo energetico annuale in megawattora (MWh);
- ﻿﻿﻿capacità di stoccaggio di energia in megawattora (MWh);
- efficienza dei sistemi di accumulo di energia in percentuale;
- costi di investimento iniziali in USD;
- riduzione delle emissioni di gas a effetto serra in tonnellate di CO2 equivalente;
- indice di riduzione dell'inquinamento atmosferico;
- numero di lavori creati.

Inoltre, l’utente potrà richiedere un’analisi generica su una singola fonte rinnovabile la quale verrà effettuata rispetto al valore minimo, massimo e medio relativo alle seguenti categorie di default:
- capacità installata in megawatt (MW);
- produzione annuale di energia in megawattora (MWh);
- ﻿﻿﻿consumo energetico annuale in megawattora (MWh);
- capacità di stoccaggio di energia in megawattora (MWh);
- costi di investimento iniziali in USD;
- indice di riduzione dell'inquinamento atmosferico.

Il cliente, successivamente, potrà richiedere un preventivo scegliendo 
- la tipologia di fonte rinnovabile, 
- l’investimento iniziale 
- il valore di capacità minimo necessario. 
Il software proporrà le 3 soluzioni che rispettano le preferenze del cliente, indicando: i costi iniziali, i relativi incentivi, i valori di capacità, produzione e consumo, l’indice d riduzione dell’inquinamento atmosferico e il numero di lavori che si creerebbero.

### Descrizione della rilevanza gestionale del problema

Negli ultimi anni, la sostenibilità ambientale è diventata una priorità per molte aziende, non solo per motivi etici, ma anche per migliorare la propria reputazione ecologica, la cosiddetta Green Reputation. Inoltre, l’impegno verso la sostenibilità ambientale può aiutare le imprese a rafforzare la propria imagine, accrescere la fiducia dei consumatori e migliorare la loro posizione competitiva sul mercato. 
Una delle principali modalità in cui le aziende possono migliorare la loro sostenibilità ambientale è l’investimento in fonti di energia rinnovabili, pertanto potrebbe essere utile poter visionare statistiche sulle produzioni, sul valore degli investimenti e sulle conseguenze ambientali relative all’installazione di differenti sistemi di energia rinnovabile.

### Descrizione dei data-set per la valutazione	

La risoluzione di tale problema avviene attraverso l’utilizzo di un data-set pubblicato sul sito Kaggle, in particolare si fa riferimento a “Set di dati per sistemi di energia rinnovabili”, accessibile dal link riportato di seguito. 
https://www.kaggle.com/datasets/girumwondemagegn/dataset-for-renewable-energy-systems?select=energy_dataset_.csv
Il set di dati contiene informazione dettagliate su vari sistemi di energia rinnovabile:
- Type_of_Renewable_Energy: Codice numerico che rappresenta il tipo di fonte di energia rinnovabile (1: Solare, 2: Eolico, 3: Idroelettrico, 4: Geotermico, 5: Biomassa, 6: Mareamotrice, 7: Moto ondoso);
- Installed_Capacity_MW: capacità installata in megawatt (MW);
- ﻿﻿﻿Energy_Production_MWh: produzione annuale di energia in megawattora (MWh);
- ﻿﻿﻿Energy_Consumption_MWh: Consumo energetico annuale in megawattora (MWh);
- ﻿﻿﻿Energy_Storage_Capacity_MWh: capacità di stoccaggio di energia in megawattora (MWh);
- Storage_Efficiency_Percentage: efficienza dei sistemi di accumulo di energia in percentuale;
- Grid_Integration_Level: codice numerico che rappresenta il livello di integrazione della griglia (1: completamente integrato, 2: parzialmente integrato, 3: integrazione minima, 4: microgriglia isolata);
- ﻿﻿﻿Initial_Investment_USD: costi di investimento iniziali in USD;
- ﻿﻿﻿Funding_Sources: codice numerico che rappresenta la fonte di finanziamento (1: Government, 2: Private, 3: Public-Private Partnership);
- Financial _Incentives_USD: incentivi finanziari in USD;
- GHG_Emission _Reduction_tCO2e: riduzione delle emissioni di gas a effetto serra in tonnellate di CO2 equivalente (tCO2e);
- Air_Pollution _Reduction_Index: Indice di riduzione dell'inquinamento atmosferico;
- Jobs_Created: numero di lavori creati;
L'obiettivo di tale data-set è quello di fornire una visione completa delle fonti di energie rinnovabili, utile per la ricerca e l'analisi nel campo dell'energia sostenibile.

### Descrizione preliminare degli algoritmi coinvolti	

Il programma sarà sviluppato usando il linguaggio Python, utilizzando i pattern MVC (Model View Controller) e DAO (Data Access Object) attraverso i quali vengono separati l’interfaccia utente, la logica applicativa e l’accesso ai dati. 

Per lo sviluppo dell’analisi preliminare specifica, verrà richiesto all’utente di scegliere la fonte rinnovabile da analizzare e la relativa categoria.
Successivamente, verranno raccolti i dati tramite query SQL relativi alle preferenze espresse in precedenza e verrà selezionato solo l’attributo scelto. I dati verrano salvati in una lista e, usando funzioni appropriate, verrano calcolati i valori di minimo, massimo e medio per la relativa categoria.

Per lo sviluppo dell’analisi preliminare generica, verrà richiesto all’utente di scegliere la fonte da analizzare. Quindi, verrano raccolti i dati tramite query SQL e verranno selezionati tutti gli attributi. I dati verrano salvati in una lista e verrano implementate le funzioni per calcolare i valori di minimo, massimo e medio. 

Infine, per lo sviluppo della soluzione per il cliente verrà richiesta la tipologia di fonte rinnovabile, l’investimento iniziale massimo ed il valore di capacità minimo necessario. Con le funzioni sviluppate in precedenza verrano selezionati i dati per ogni fonte rinnovabile e verrà implementata una funzione basata sulla ricerca ricorsivi al fine di proporre 3 soluzioni che rispettano le preferenze impostate dal cliente.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione sarà suddivisa in due sezioni, una prima dedicata all’analisi preliminare e una seconda dedicata alla ricerca della soluzione da proporre al cliente. 

Il menù a tendina per la scelta della fonte rinnovabile sarà comune ad entrambe le sezioni.

Nella prima sezione, il cliente dopo aver scelto la fonte rinnovabile potrà scegliere le eventuali categorie da analizzare singolarmente oppure, nel caso in cui si volesse l’analisi generica, basterà non scegliere nessuna categorie o selezionare la categorie apposita “Analisi generale”.  
L'analisi effettuata verrà stampata a schermo in risposta al click sul bottone “Analisi”.

La seconda sezione sarà costituita da due blocchi di testo nei quali l’utente potrà inserire il valore dell’investimento iniziale massimo e della capacità minima. Le tre soluzioni verrano stampate a video in seguito al click del bottone “Cerca soluzione”.

**Comment by JosephAv** [comment]
qui la tua repo per lavorare https://github.com/TdP-prove-finali/HolotaAlexandraElena.git
