### ISSUE TITLE
Sistema di Monitoraggio e Collaudo per Dispositivi IoT 

### ISSUE THREAD

**Issue by marcodonatucci** [TdP-prove-finali/Introduzione#126]
### Studente proponente

s293556 Marco Donatucci

### Titolo della proposta

Sistema di Monitoraggio e Collaudo per Dispositivi IoT 

### Descrizione del problema proposto

Il progetto si propone di sviluppare un sistema per il monitoraggio e il collaudo di dispositivi IoT dell'azienda Topfly s.r.l. installati sui veicoli. Il problema affrontato riguarda la necessità di verificare e testare l'efficacia e l'affidabilità dei dispositivi IoT durante la fase di collaudo prima della loro messa in opera. Questo sistema consentirà di raccogliere e analizzare i dati provenienti dai sensori installati sui veicoli per identificare eventuali malfunzionamenti, ottimizzare le prestazioni e garantire che i dispositivi siano pronti per l'uso sul campo. La sfida principale è sviluppare un'interfaccia user-friendly che permetta ai tecnici di collaudo di eseguire test completi e ottenere feedback immediati sui dispositivi.

### Descrizione della rilevanza gestionale del problema

Dal punto di vista gestionale, l'applicazione sviluppata rappresenta un significativo miglioramento nei processi operativi di Topfly s.r.l. L'ottimizzazione del collaudo e dell'installazione dei dispositivi riduce i tempi di inattività dei veicoli e migliora la qualità del servizio offerto ai clienti. La possibilità di eseguire controlli e comandi da remoto aumenta l'efficienza degli operatori, mentre la gestione centralizzata dei dati di collaudo permette una migliore tracciabilità e analisi delle performance. Inoltre, l'integrazione di funzionalità di contatto diretto con i tecnici e l'invio automatico di report via email semplifica la comunicazione interna e con i clienti.

### Descrizione dei data-set per la valutazione	

I dati per la valutazione saranno ottenuti dai server aziendali, dove i sensori dei dispositivi inviano le loro informazioni durante la fase di collaudo. Questi dati includono misurazioni di posizione, temperatura, tempi di funzionamento, livelli di batteria, dati del tachigrafo e altre metriche operative. La piattaforma server dell'azienda fornirà l'accesso ai dati storici e in tempo reale tramite API. Questi dati saranno utilizzati per monitorare le performance dei dispositivi, rilevare anomalie e garantire che soddisfino gli standard richiesti prima di essere messi in servizio.

### Descrizione preliminare degli algoritmi coinvolti	

I principali problemi algoritmici da affrontare includono:

1.⁠ *⁠Autenticazione e sicurezza*: Implementazione di un sistema di login sicuro utilizzando tecniche di hashing per le password e protocolli di autenticazione standardizzati.
2.⁠ ⁠*Elaborazione delle immagini per il riconoscimento QR*: Utilizzo di algoritmi per la scansione e la decodifica di codici QR, garantendo un'alta precisione e velocità di riconoscimento.
3.⁠ ⁠*Ricerca e filtraggio dei dispositivi*: Sviluppo di algoritmi di ricerca ottimizzati per la rapida identificazione dei dispositivi tramite il loro codice univoco.
4.⁠ ⁠*Esecuzione di comandi remoti*: Implementazione di algoritmi per l'invio e la gestione di comandi ai dispositivi, assicurando la corretta esecuzione e la gestione degli errori.
5.⁠ ⁠*Generazione e invio di report via email*: Automazione della raccolta dati e generazione di report, inclusi gli algoritmi per la formattazione e l'invio delle email.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione prevista permetterà ai tecnici di collaudo di monitorare e testare i dispositivi IoT in tempo reale. Le funzionalità principali includeranno:
•⁠  ⁠*Login*: Accesso all'applicazione tramite username e password, con autenticazione sicura.
•⁠  ⁠*Ricerca dispositivi*: Possibilità di cercare i dispositivi utilizzando un codice identificativo univoco o tramite la scansione di un codice QR presente nelle immagini della galleria.
•⁠  ⁠*Visualizzazione dati dispositivo*: Display dettagliato delle informazioni del dispositivo, inclusi i dati dei sensori in tempo reale.
•⁠  ⁠*Esecuzione comandi*: Interfaccia per eseguire comandi specifici sui dispositivi, come cambio del nome, blocco/sblocco del motore, controllo del tachigrafo e abilitazione del lettore.
•⁠  ⁠*Contatto tecnico*: Funzionalità per contattare un tecnico tramite telefonata diretta dall'applicazione in caso di problemi specifici.
•⁠  ⁠*Invio report via email*: Generazione automatica e invio di un'email all'azienda contenente tutti i dati del collaudo effettuato.

**Comment by JosephAv** [comment]
Qui la tua repo, lavora/carica qui 

https://github.com/TdP-prove-finali/Marco-Donatucci.git

**Comment by marcodonatucci** [comment]
Potrebbe mandarmi un invito per la repo? Ho provato a fare il push ma 
ottengo un errore, probabilmente perchè non ho il permesso

remote: Permission to TdP-prove-finali/Marco-Donatucci.git denied to 
marcodonatucci.
fatal: unable to access 
'https://github.com/TdP-prove-finali/Marco-Donatucci.git/': The 
requested URL returned error: 403

Il 2024-06-24 12:02 Giuseppe Averta ha scritto:

**Comment by JosephAv** [comment]
Ora dovresti riuscirci

Giuseppe

Giuseppe Averta, PhD

Politecnico di Torino, Italy
e ***@***.***



------ Original Message ------
From "Marco Donatucci" ***@***.***>
To "TdP-prove-finali/Introduzione" ***@***.***>
Cc "Giuseppe Averta" ***@***.***>; "State change" 
***@***.***>
Date 24/06/24, 12:32:21
Subject Re: [TdP-prove-finali/Introduzione] Sistema di Monitoraggio e 
Collaudo per Dispositivi IoT (Issue #126)

**Comment by marcodonatucci** [comment]
Grazie, ho caricato tutto e ho inoltrato la richiesta di conclusione sul 
portale

Il 2024-06-24 14:11 Giuseppe Averta ha scritto:
