### ISSUE TITLE
Sistema Diagnostico Avanzato per la Ricerca di Malattie e Sintomi con Ponderazione della Gravità

### ISSUE THREAD

**Issue by Francesco0603** [TdP-prove-finali/Introduzione#132]
### Studente proponente

s294392 Francesco Pusceddu

### Titolo della proposta

Sistema Diagnostico Avanzato per la Ricerca di Malattie e Sintomi con Ponderazione della Gravità

### Descrizione del problema proposto

Il problema affrontato consiste nella difficile, lenta o imprecisa identificazione rapida e accurata delle malattie a partire dai sintomi presentati. L’obiettivo del progetto è la creazione di un software che permetta di evidenziare le relazioni tra sintomi e malattie attraverso un algoritmo dipendente dalla gravità dei sintomi. L’applicazione sarà in grado di identificare la malattia più probabile tra quelle presenti nel database ed oltre alla diagnosi, fornirà suggerimenti sulle precauzioni da adottare in modo da sensibilizzare l'utente
 in maniera congrua alla gravità della problematica. 

### Descrizione della rilevanza gestionale del problema

Dal punto di vista gestionale, il sistema rappresenta uno strumento di supporto per i professionisti della salute e può essere integrato in sistemi di assistenza sanitaria esistenti per migliorare l'efficienza diagnostica. Riducendo il carico di lavoro dei medici e migliorando la tempestività della diagnosi, questo progetto ha il potenziale per ottimizzare la gestione delle risorse mediche, specialmente in contesti con risorse limitate. Inoltre, può fornire una prima guida diagnostica a pazienti o utenti finali che potrebbe concorrere ad aumentare ulteriormente l'efficienza del sistema sanitario. In conclusione l'Infrastruttura medica potrebbe subire un influenza non solo diretta come sopracitato, ma anche indiretta attraverso la promozione dell'educazione sanitaria e della consapevolezza.

### Descrizione dei data-set per la valutazione	

Il progetto utilizzerà il dataset disponibile nel repository GitHub: "https://github.com/itachi9604/healthcare-chatbot/tree/master" (healthcare-chatbot) che contiene informazioni dettagliate su malattie, sintomi e relative correlazioni. Il dataset è composto da tabelle che associano malattie ai possibili sintomi, descrizioni delle malattie, precauzioni raccomandate e la gravità dei sintomi. Inoltre, verranno utilizzati valori di gravità numerici attribuiti ai sintomi per migliorare la precisione dell'algoritmo diagnostico. Se necessario, i dati saranno ulteriormente arricchiti per supportare tutte le funzionalità previste.

### Descrizione preliminare degli algoritmi coinvolti	

L’algoritmo principale sarà una variante della ricerca ricorsiva su grafi, in cui i nodi sono costituiti dalle malattie e gli archi sono non orientati e rappresentati dai sintomi comuni tra due malattie, inoltre saranno anche pesati in quanto ad ogni sintomo vi corrisponde un valore di gravità. L'algoritmo esplora il grafo a partire dai sintomi inseriti, passando da una malattia all'altra seguendo gli archi più pesanti. Il peso di un arco aumenta in base alla gravità e al numero di sintomi condivisi tra due malattie, e le malattie con il peso totale maggiore saranno considerate le più probabili. Inoltre, se la diagnosi risulta incerta o più malattie hanno pesi simili, l'algoritmo può chiedere ulteriori sintomi per migliorare la precisione del risultato. In questo modo, la ricorsione permette di affinare continuamente la diagnosi, migliorando la probabilità di trovare la malattia corretta.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione permetterà all'utente di inserire sintomi manualmente o selezionarli da una lista. Le principali funzionalità includeranno:
1) Diagnosi basata su grafi ponderati: Il sistema identificherà le malattie più probabili calcolando gli archi ponderati, che rappresentano i sintomi comuni tra malattie. Le malattie con il peso maggiore, derivato dal numero e dalla gravità dei sintomi, saranno considerate le più probabili.
2) Sistema di raccomandazione delle precauzioni: Per ogni diagnosi confermata, l’applicazione fornirà una lista di precauzioni raccomandate per gestire la malattia.
3) Previsione della gravità della malattia: L’applicazione valuterà la gravità della malattia in base alla combinazione e alla severità dei sintomi inseriti.
4) Percorso diagnostico interattivo: In caso di diagnosi ambigue, il sistema suggerirà ulteriori domande per raccogliere nuovi sintomi e affinare i risultati.
5) Esportazione dei risultati: Gli utenti potranno esportare la diagnosi e le raccomandazioni in un report consultabile.

**Comment by JosephAv** [comment]
ok, qui la tua repo per lavorare https://github.com/TdP-prove-finali/PuscedduFrancesco.git
