### ISSUE TITLE
Software a supporto del processo decisionale 

### ISSUE THREAD

**Issue by YENY-CT** [TdP-prove-finali/Introduzione#133]
### Studente proponente

s259614 Contreras Tupac Yeny Andrea

### Titolo della proposta

Software a supporto del processo decisionale 

### Descrizione del problema proposto

L’applicazione si propone di aiutare i responsabili dei negozi di giocattoli nella loro attività decisionale e di controllo, fornendo tramite grafici e tabelle, una panoramica generale delle performance per identificare informazioni indispensabili, ad esempio quale prodotto contribuisce maggiormente ai profitti, i trend, la redditività delle varie categorie di prodotti...
Verrà svolto anche un’analisi CVP (costo-volume-profitto) in modo che i manager possano conoscere la correlazione fra costo, volume e reddito e attraverso la simulazione potranno capire se attuare o meno determinate azioni correttive per raggiungere un certo risultato, ad esempio se diminuendo il prezzo di vendita e aumentando il budget pubblicitario è possibile aumentare le vendite del prodotto x.

### Descrizione della rilevanza gestionale del problema

L’ obiettivo è quello di sviluppare un’applicazione di supporto per i manager affinché siano guidati verso decisioni strategiche che favoriscano la crescita aziendale e, dove occorre, operazioni correttive per una gestione delle risorse più efficiente.
L’applicazione non si limiterà a fornire un quadro generale delle performance dei vari punti vendita ma verrà anche svolta una simulazione che aiuterà i manager a capire che impatto hanno certe variazioni.

### Descrizione dei data-set per la valutazione	

Il data-set utilizzato è stato reperito dal sito Kaggle.com (comunità di data science in cui è possibile trovare e pubblicare set di dati), con una licenza di utilizzo non commerciale.
Esso è composto da quattro tabelle interconnesse che includono dati relativi ad una catena di negozi di giocattoli con diversi sedi in Messico chiamata Maven Toys.
Tale data-set include informazioni su prodotti, negozi, transazioni giornaliere e livelli attuali di inventario in ciascuna sede.

https://www.kaggle.com/datasets/mysarahmadbhat/toy-sales

### Descrizione preliminare degli algoritmi coinvolti	

Il Programma sarà sviluppato in linguaggio Python, utilizzando i pattern MVC (Model, View, Controller) e DAO per garantire la separazione tra l’interfaccia utente, la logica applicativa e l’accesso ai dati.
l’applicazione metterà a disposizione un menu a tendina affinché l’utente possa selezionare la location di interesse e tramite query SQL verranno ricercate le informazioni necessarie contenute nel data-set che saranno stampate poi in formato tabellare e grafico.
Attraverso un algoritmo ricorsivo verrà identificato il negozio e il prodotto più redditizio.
All’utente sarà anche richiesto di inserire in input dei dati di tipo numerico per poter implementare una serie di formule per l’analisi CVP e avviare la simulazione.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’obiettivo è quella di sviluppare un’applicazione che permette all’utente di:
-	selezionare la location che si vuole analizzare in modo da poter visualizzare l’andamento delle vendite e consentire una migliore comprensione dei dati tramite un output anche di tipo grafico e tabellare
-	inserire in input alcuni parametri necessari affinché il programma possa:
    -  generare il diagramma di redditività che evidenzierà alcuni informazioni utili come il margine di sicurezza che indicherà di quanto possono calare le vendite prima che si iniziano a sostenere delle perdite 
    -  avviare la simulazione per poter avere un’idea su eventuali scenari ipotetici

**Comment by JosephAv** [comment]
ok, qui la repo per lavorare https://github.com/TdP-prove-finali/ContrerasTupacYenyAndrea.git

**Comment by YENY-CT** [comment]
Buongiorno ho provato a fare il push al link inviatomi
ma mi appare il seguente messaggio di errore:
remote: Permission to TdP-prove-finali/ContrerasTupacYenyAndrea.git denied to YENY-CT.
unable to access 'https://github.com/TdP-prove-finali/ContrerasTupacYenyAndrea.git/': The requested URL returned error: 403
