### ISSUE TITLE
Proposta Prova Finale s301037

### ISSUE THREAD

**Issue by AngelaDellEdera** [TdP-prove-finali/Introduzione#135]
### Studente proponente

s301037 Dell'Edera Angela

### Titolo della proposta

Simulazione e Ottimizzazione della Sostenibilità nella Filiera della Moda

### Descrizione del problema proposto

Il progetto proposto mira a risolvere un problema nel settore della moda sostenibile: come monitorare e ottimizzare l'uso di risorse ambientali (materiali, acqua, energia, ecc.) e ridurre l'impatto ecologico della produzione, distribuendo pratiche più sostenibili tra i brand. L'obiettivo è creare un’applicazione che simuli l'impatto ambientale di vari brand nel tempo e offra suggerimenti per migliorare le loro performance ecologiche. Sarà analizzata l'efficienza delle risorse, i metodi di produzione ecologici e l'impronta di carbonio. L'analisi potrebbe includere scenari in cui i brand cambiano i loro processi produttivi o materiali, verificando il loro impatto sulla sostenibilità.

### Descrizione della rilevanza gestionale del problema

La pressione per adottare pratiche sostenibili nella moda sta crescendo rapidamente, sia a causa delle normative internazionali che delle aspettative dei consumatori. Iniziative come il Global Fashion Agenda e gli Sustainable Development Goals (SDGs) delle Nazioni Unite richiedono alle aziende di ridurre il loro impatto ambientale. Dal punto di vista gestionale, una piattaforma che simuli scenari di sostenibilità fornisce un valore strategico, consentendo alle aziende di prevedere l'impatto delle loro scelte e allinearsi con gli obiettivi normativi e di mercato. Oltre a rispondere alle esigenze dei regolatori, queste decisioni basate sui dati permettono alle aziende di migliorare la loro reputazione e acquisire un vantaggio competitivo.

### Descrizione dei data-set per la valutazione	

Il dataset utilizzato nel progetto contiene 5000 record unici, ciascuno relativo a un brand di moda sostenibile, proveniente dalla piattaforma Kaggle (https://www.kaggle.com/datasets/waqi786/sustainable-fashion-eco-friendly-trends/data), e contiene informazioni rilevanti per ogni brand di moda sostenibile. Ogni record presenta dati che permettono di analizzare l'impatto ambientale delle attività dei brand e simulare scenari per migliorare le loro pratiche sostenibili.

Le informazioni contenute nel dataset includono:

Brand_ID: identificatore univoco del brand.
Brand_Name: nome del brand.
Country: paese di origine del brand.
Year: anno di rilevazione dei dati.
Sustainability_Rating: punteggio complessivo di sostenibilità del brand.
Material_Type: tipologia di materiali utilizzati (es. riciclato, organico, sostenibile).
Eco_Friendly_Manufacturing: presenza di pratiche produttive eco-compatibili.
Carbon_Footprint_MT: impronta di carbonio in tonnellate metriche.
Water_Usage_Liters: consumo di acqua in litri durante la produzione.
Waste_Production_KG: quantità di rifiuti prodotti in chilogrammi.
Recycling_Programs: se il brand adotta o meno programmi di riciclo.
Product_Lines: numero di linee di prodotti offerte.
Average_Price_USD: prezzo medio dei prodotti in dollari USA.
Market_Trend: trend di mercato del brand in termini di domanda e sostenibilità.
Certifications: certificazioni ambientali ottenute.

### Descrizione preliminare degli algoritmi coinvolti	

Ricerca attraverso query:   
L'applicazione utilizzerà query SQL per filtrare i brand che soddisfano criteri specifici di sostenibilità (ad esempio, punteggi di sostenibilità superiori a una certa soglia). Questo approccio verrà ottimizzato per gestire dataset di grandi dimensioni (5000 record).

Simulazione Ricorsiva:
 Attraverso funzioni ricorsive, l'applicazione modellerà l'impatto delle decisioni sui materiali sostenibili nel tempo. Questo approccio permetterà di visualizzare come piccole modifiche, come l'introduzione di materiali riciclati, possano influenzare gradualmente il punteggio di sostenibilità di un brand anno dopo anno.

Ottimizzazione Semplice: 
Saranno implementati algoritmi per ottimizzare l'uso delle risorse, come i materiali sostenibili. L'obiettivo sarà quello di trovare il miglior equilibrio tra costo e sostenibilità, contribuendo a decisioni più informate.

Analisi delle Reti: 
L'applicazione utilizzerà la libreria NetworkX per rappresentare la supply chain come un grafo, in cui i nodi sono i brand e i materiali e gli archi rappresentano le connessioni tra di essi. Le metriche di centralità, come la betweenness centrality, saranno calcolate per identificare i brand più centrali e influenti nella rete, fornendo indicazioni su quali brand abbiano il maggiore impatto sulla sostenibilità globale del settore.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione si propone di fornire uno strumento intuitivo e pratico per manager e consulenti di sostenibilità nel settore della moda. Le principali funzionalità previste includono:

Ricerca dei Brand Sostenibili: Gli utenti potranno inserire un punteggio di sostenibilità desiderato. L'applicazione utilizzerà una funzione ricorsiva per restituire un elenco di brand che soddisfano il criterio specificato, consentendo un rapido accesso ai brand più sostenibili.

Calcolo del Consumo Totale delle Risorse: Gli utenti avranno la possibilità di calcolare il consumo totale d’acqua o la produzione di rifiuti di tutti i brand. Il programma fornirà un output che mostrerà la somma totale per la risorsa selezionata, permettendo di visualizzare l'impatto complessivo delle pratiche di produzione.

Simulazione di Scelte di Materiale: Gli utenti potranno selezionare un brand e modificare la percentuale di materiali sostenibili utilizzati. Il programma mostrerà l'effetto immediato di queste scelte sul punteggio di sostenibilità, aiutando a comprendere le conseguenze delle decisioni in tempo reale.

Queste funzionalità sono progettate per rendere l'applicazione accessibile e utile, supportando decisioni informate sulla sostenibilità e contribuendo a un futuro più responsabile nel settore della moda.

**Comment by JosephAv** [comment]
qui la repo per lavorare https://github.com/TdP-prove-finali/DellEderaAngela.git
