### ISSUE TITLE
Proposta prova finale Maris

### ISSUE THREAD

**Issue by CSMaris** [TdP-prove-finali/Introduzione#14]
### Studente proponente

s223305 Maris Catalin Stefan

### Titolo della proposta

Simulazione linea di produzione industriale

### Descrizione del problema proposto

Data una domanda quotidiana di prodotti da soddisfare, si vuole cercare di valutare i parametri fondamentali nella progettazione della linea di produzione che soddisferà la suddetta domanda. In particolare lo scopo principale del software sarà la possibilità di creare una linea di produzione modularmente, cioè creando ogni workstation della linea con i propri parametri, e tramite interfaccia utente valutarne la fattibilità per soddisfare una certa domanda nell'arco di un anno.

### Descrizione della rilevanza gestionale del problema

Nel momento in cui un'azienda decide di mettere in commercio un nuovo prodotto, dopo averne valutata la fattibilità progettuale, dovrà organizzare le proprie risorse per mettere in produzione tale prodotto. Nella quasi totalità dei casi si fanno delle stime sulla domanda futura che verranno utilizzate per elaborare il piano di produzione. Ovviamente sarebbe sconveniente e soprattutto poco intelligente organizzare la linea solamente sulla base dell'intuito, ma bisognerebbe invece cercare di simulare nel modo più realistico possibile l'andamento del piano di produzione per trovare eventuali problemi che potrebbero generarsi, uno tra tutti l'eccessiva utilizzazione dei macchinari.

### Descrizione dei data-set per la valutazione	
Verrà utilizzato un data-set riguardante l'andamento della domanda quotidiana di alcuni prodotti che mi è stato fornito dal Professor Chiabert.  I dati saranno riferiti agli anni 2015-2017.  Il data-set contiene il valore numerico della domanda di 3 prodotti finiti giorno per giorno , ognuno riferito ad un anno diverso. Il data-set è liberamente modificabile in quanto personalmente creato da un un file Excel che mi è stato dato dal prof Chiabert.

### Descrizione preliminare degli algoritmi coinvolti	

-Creazione e gestione di varie linee di produzione
-Gestione delle query al database delle vendite previste
-Simulazione, giorno per giorno, dell'andamento delle varie linee di produzione in base alle vendite previste del prodotto finito utilizzante la suddetta linea e proposta di miglioramenti nei casi di problemi della linea o di inefficienze. Si effettuerà una ricorsione tra tutte le possibili combinazioni di parametri delle workstation per poter ottenere la migliore linea possibile dati dei vincoli iniziali sui parametri.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione sarà tendenzialmente un' interfaccia grafica che permetterà di dare in input i parametri di ogni workstation per poter creare la linea di produzione su cui effettuare la simulazione. Tramite un tasto di avvio si eseguirà la simulazione di produzione sulla linea selezionata per un certo prodotto, e una volta fatto si otterranno in output messaggi di diagnosi, quali blocchi della linea per eccessivo input di materia prima, gravi inefficienze, ecc... 
La simulazione consisterà nella determinazione quotidiana dell'input di materia prima da immettere a monte della linea di produzione, la quale verrà volta per volta processata da ogni workstation in modo da poter garantire un throughput tale da soddisfare la domanda del giorno in questione (si suppone di dover produrre per poter vendere o stoccare entro la sera del giorno considerato). Per ogni workstation si valuterà il tempo effettivo di lavorazione,  dati i parametri di normale funzionamento e di varianza precedentemente preimpostati. Se non sussistono problemi, ogni giorno la quantità in uscita dalla linea sarà uguale o maggiore alla domanda; nel caso di quantità maggiore si potrà generare uno stock in modo da poter coprire eventuali inefficienze nei giorni a seguire. 
Possibili anomalie nel funzionamento possono essere un' eccessiva quantità in input alla linea che sovraccaricherebbe la workstation collo di bottiglia della linea, o contrariamente un'utilizzazione troppo bassa di alcune workstations, sintomo di non star sfruttando a pieno le potenzialità della linea. In fase di progettazione della linea, si potrebbe anche effettuare una sorta di benchmarking interno, cioè una valutazione di quanto la linea proposta si avvicini alle ideali caratteristiche ottimali (funzionamento ideale: mancanza di varianza nei tempi di processo per ogni workstation). Questi sarebbero i problemi principali da affrontare, altre particolarità potrebbero essere gestite, ma ne valuterò la fattibilità una volta risolti i principali problemi algoritmici delle anomalie sopra descritte.
L'obbiettivo finale diventa quindi la determinazione dei parametri ottimali di ogni workstation per poter garantire il soddisfacimento della domanda, imponendo inizialmente un range entro cui devono trovarsi.
Tutte le informazioni riguardanti i parametri verranno inserite in input dall'utente, in quanto si ipotizza di eseguire il set-up ex novo della linea, senza riutilizzare workstations già in azienda. Si ipotizza inoltre un andamento "lineare" della produzione, cioè l'inserimento di un solo tipo di materia prima a monte della linea, senza fornire informazioni di diagnosi riguardanti eventuali mancanze di materia prima o prefabbricati in quanto ciò è problema di chi gestisce il piano di produzione ai livelli più alti della gerarchia aziendale.

**Comment by fulcorno** [comment]
L'argomento è adatto ed il tipo di elaborazione è adeguata agli argomenti del corso.
Aggiungerei alcune precisazioni:
- chiarire la dimensione del data-set (è una cosa enorme, striminzita, o una ragionevole via di mezzo?)
- chiarire la possibilità di re-distribuire il data-set (autorizzazione del prof. Chiabert)
- fornire maggiori dettagli su come verrà effettuala la simulazione, e quali tipologie di anomalie saranno identificate
- ridurre al minimo la fase di "editing grafico" delle configurazioni delle linee (porta via molto tempo, e algoritmicamente non aggiunge molto)
- eventualmente fornire la possibilità di ripetere la simulazione "in automatico" cambiando la configurazione iniziale (entro alcuni range specificati dall'utente), per poi identificare quella che avrà fornito risultati migliori.

Puoi modificare la proposta secondo i punti precedenti, e farmi sapere quando la posso riguardare.

**Comment by fulcorno** [comment]
ok, approvato
