### ISSUE TITLE
 Cammini minimi dei Taxi all'interno della città di New York.

### ISSUE THREAD

**Issue by walfor** [TdP-prove-finali/Introduzione#15]
### Studente proponente

s223216 Walter Forcignanò

### Titolo della proposta

Cammini minimi dei Taxi all'interno della città di New York.

### Descrizione del problema proposto

Il problema che si vuole risolvere è  quello di individuare all'interno di un grafo, costruito analizzando i percorsi dei taxi nella citta' di New York, i cui dati sono ricavati da un dataset esistente, il percorso che minimizza il tempo di percorrenza date due posizioni inizialmente scelte dall'utente. Nel caso in cui i due luoghi selezionati non siano collegati, il programma visualizza un messaggio di errore.
Nel dettaglio, dati tutti possibili percorsi effettuati dai taxi, individuare tramite un algoritmo ricorsivo la soluzione che porta alla ottimizzazione della funzione obiettivo rappresentata dal tempo totale di percorrenza.

### Descrizione della rilevanza gestionale del problema

Il problema è rilevante dal punto di vista gestionale, in quanto l'ottimizzazione del tempo di percorrenza è alla base di qualsiasi sistema di controllo logistico, sia per il trasporto di persone, che di merci. Nella sua versione più completa, il problema potrebbe essere affrontato includendo altre variabili come l'usura del mezzo (a seconda delle strade percorse), il costo del carburante, la gestione dei turni e l'esperienza di viaggio (ad esempio, a parità di tempo ed altre condizioni, si potrebbe preferire percorsi più panoramici e rilevanti da un punto di vista turistico).

### Descrizione dei data-set per la valutazione	

La fonte dal quale verranno prelevati i dati è un data-set  trovato in rete sul sito www.kaggle.com, è un data-set reale, il cui contenuto è una collezione di dati con varie informazioni, tra cui i cammini dei taxi all'interno della città di New York.
link del data-set: https://www.kaggle.com/maheshdadhich/strength-of-visualization-python-visuals-tutorial/data
Di ogni tratta effettuta dai taxi vi è una sua scomposizione del tragitto nelle varie vie della città che vengono attraversate, e vengono riportate alcune misurazioni tra cui il tempo di percorrenza per ogni step, la distanza in metri del singolo step, e le coordinate spaziali del luogo attraversato che rappresenteranno i nodi del grafo che verrà costruito.
I dati risultano essere grezzi, in particolare nel formato CSV, quindi per poter effettuare qualunque operazione, è necessario prima formattare i dati, rappresentati solitamente da liste, e verificare la loro integrità.
La particolarità del data-set è che i valori riporati in tabella sono delle liste separate da un carattere separatore nel dettaglio '|' .
In particolare i dati che verranno utilizzati sono:
number_of_steps: Numero di step effettuati nel percorso.
street_for_each_step: Lista delle strade in cui avviene ogni manovra. Piu' manovre possono essere fatte sulla stessa via. Inoltre la stessa via può apparire più volte.
-total_travel_time: Tempo totale tra i due punti del grafo che rappresentano partenza e arrivo del percorso.
-distance_per_step:  Distanza che c'è  tra ogni singolo step.
-travel_time_per_step:  Tempo che intercorre per ogni step.
-step_location_list: Le coordinate di ogni azione che viene fatta durante il percorso.

### Descrizione preliminare degli algoritmi coinvolti	

-Il principale algoritmo che verrà implementato sarà quello della ricorsione. In particolare, dati due punti della città di New York corrispondenti a due vie, identificare se queste sono collegate all'interno del grafo costruito sulla base dei percorsi dei taxi esitenti, e tra tutti i possibili cammini individuare quello che vada a minimizzare il tempo di percorrenza, trovando quindi l'ottimo se esiste, altrimenti sarà visualizzato un messaggio di errore.
-In particolare l'esistenza del cammino  tra due punti sarà individuata se una volta costruito il grafo dato dalle coordinate delle posizioni di ogni singolo step dei percorsi effettuati da ogni singolo taxi, esisterà un arco che collegherà i due nodi del grafo. Ciò sarà realizzato tramite un opportuno algoritmo di visita.
-Costruzione di una struttura dati avanzata, un grafo pesato tenendo conto come peso il tempo di percorrenza del taxi che compirà quel percorso.
-La formattazione dei dati dal formato CSV, in un formato che sia gestibile e che rispetti i principi della programmazione a oggetti.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

A livello generale l'utente avrà a disposizione un interfaccia che presenterà tutte le possibili vie presenti nel database, potrà selezionare quale percorso si vuole effettuare e avviare, definiti i dati di partenza, ovvero le due località,  l'algoritmo che calcolerà il cammino minimo effettuato da un taxi.
A schermo sarà riportato il percorso seguito, il tempo di percorrenza di ogni singolo step, le vie attraversate e il numero di manovre eseguite.

**Comment by fulcorno** [comment]
ok, la proposta è accettata.
