### ISSUE TITLE
Gestione contabilità direzionale di tecnici in un azienda di servizi.

### ISSUE THREAD

**Issue by nicomontale** [TdP-prove-finali/Introduzione#18]
STUDENTE PROPONENTE
Montaleone Nicola s218444 

TITOLO DELLA PROPOSTA

Gestione contabilità direzionale di tecnici in un azienda di servizi.

DESCRIZIONE DEL PROBLEMA PROPOSTO

Ho contattato un'azienda di servizi di installazione e manutenzione di caldaie e climatizzatori che mi ha fornito un database relativo all'operato dei tecnici del 2018.
Lo scopo principale è di effettuare un' analisi delle performance dei tecnici e delle azioni finalizzate all'incremento della produzione: installazione, manutenzione ordinaria e straordinaria, per formulare strategie generali e piani a breve/lungo termine. 
E' necessario dunque calcolare il fatturato, la percentuale dei ritorni, margini ed altri indicatori in modo tale di avere un'analisi completa dell'operato sia globale che del singolo.

DESCRIZIONE DELLA RILEVANZA GESTIONALE
Principalmente, dal punto di vista gestionale, questa applicazione potrà fornire un report di contabilità direzionale, considerando tutto l'arco dell'anno, in modo tale da poter rilevare dove 
le attività non stanno procedendo nel modo previsto e dove, alcune parti dell'organizzazione,  
richiedono maggiore attenzione.  
Per un opportuno controllo, tra i vari indicatori di calcolo i più importanti sono: il fatturato, la percentuale dei ritorni, margine ( fatturato manodopera vs costo manodopera), differenza tra gli interventi non eseguiti rispetto agli appuntamenti di lavoro straordinario.

DESCRIZIONE DEL DATA-SET PER LA VALUTAZIONE
I dati sono estrapolati da file Excel costituiti da: nominativi (non reali per la privacy), quantità di installazioni effettuate con il relativo fatturato, quantità manutenzioni  ordinarie e straordinarie,
quantità di ricambi effettuati con rispettivo costo (LIFO) e fatturato ed altri valori contabili necessari per la valutazione, per un totale di circa 22 valori e 100 dipendenti identificati univocamente da un rispettivo codice (per semplificare ho cercato di incorporare in un unica 
tabella tutti i dati). Vi sarà presente una tabella contenente username  e password per il login.

DESCRIZIONE PRELIMINARE DEGLI ALGORITMI COINVOLTI
Gli algoritmi utilizzati per questa applicazione saranno principalmente di calcolo numerico per  il calcolo degli indicatori finali, ricerca, ordinamento e  creazione di un grafo orientato per quanto riguarda la formazione di un team. 
 
DESCRIZIONE PRELIMINARE DELLE FUNZIONALITA' PREVISTA PER L'APPLICAZIONE DEL SOFTWARE 

Chi utilizzerà l'applicazione in questione potrà essere in grado di:
-registrarsi ed effettuare il login 
-modificare i dati in modo tale da evitare errori contabili permanenti
-aggiungere o cancellare nominativi di tecnici dal database
-visualizzare in una tabella tutti i dati presenti nel database
-calcolare valori di: fatturato totale, indice ritorni, margine manodopera, valore medio, ricevuta fiscale; evidenziando quelli non conformi agli obiettivi richiesti 
-formazione di team costituito da 2 tecnici in base al fatturato e/o alla quantità dei lavori  
  straordinari non eseguiti              
-effettuare il logout
Sarà presente una leggenda per la spiegazione degli indicatori presenti all'interno del software.

**Comment by fulcorno** [comment]
La proposta è adeguata e quindi accettabile.
Nelle funzionalità previste, cercherei di concentrarmi maggiormente sugli aspetti più algoritmici (ad esempio permettendo di esplorare diverse possibilità, e di proporre delle soluzioni ottimali), tralasciando invece gli aspetti più "anagrafici" (login, logout, aggiunta/modifica/cancellazione elementi).
