### ISSUE TITLE
Proposta tesi sulla gestione dei posti letto in un ospedale

### ISSUE THREAD

**Issue by ariannaravera** [TdP-prove-finali/Introduzione#19]
### Studente proponente

s237250 Ravera Arianna

### Titolo della proposta

Previsione e gestione dell’occupazione dei posti letto in una struttura ospedaliera

### Descrizione del problema proposto

L'applicazione si propone di fornire una previsione dell’occupazione futura dei posti letto in un ospedale, pianificare la variazione di domanda di ricovero, facilitare la comunicazione interna all'ospedale e con altri ospedali e ridurre la cancellazione dei ricoveri per mancanza di posti letto.
Inoltre, si vuole implementare un modo per simulare i ricoveri e avere statistiche sulle quantità di posti letto disponibili e occupati nei singoli reparti, valutando possibili soluzioni alla mancanza di disponibilità. I risultati dell’applicazione potrebbero aiutare nella gestione delle assegnazioni di letti ai pazienti ed evitare problemi di sovraffollamento o inutilizzo di risorse.

### Descrizione della rilevanza gestionale del problema

Attualmente in molti ospedali vi è un forte problema di gestione degli spazi e dei letti per i pazienti, questo a causa delle scarse risorse assegnate alle sanità e della cattiva gestione del problema dal punto di vista organizzativo.
Attraverso un data-set dello storico dei ricoveri degli ultimi mesi su un ospedale di medie dimensioni, paragonabile alla maggior parte degli ospedali nel nostro Paese, con formule di forecasting sarà possibile avere previsioni delle occupazioni future dei posti letto. Indispensabile per riuscire a organizzare al meglio la gestione ed evitare problemi, tenendo conto anche di quante urgenze sono smaltibili ed ottimizzando l'accesso tempestivo dei pazienti al setting assistenziale più appropriato.

### Descrizione dei data-set per la valutazione	

Il data-set è stato fornito da un ospedale e consiste in un archivio dello storico dei ricoveri del suddetto ospedale. I dati sono così divisi: data di accettazione e inizio ricovero, data di dimissione e reparto.
I reparti in osservazione sono: cardiologia, chirurgia, ginecologia, medicina, neurologia, nido, ortopedia, pediatria, psichiatria, rianimazione, U.T.I.C. e urologia.

### Descrizione preliminare degli algoritmi coinvolti	

L'applicazione implementerà un algoritmo di previsione, per individuare la disponibilità di posti letto in singoli reparti e in dati periodi, e un algoritmo di simulazione basato sulla previsione che cerca la miglior soluzione per il ricovero.
Verranno anche effettuati controlli sull'integrità e la coerenza dei dati, con la presenza di messaggi di errore in caso di fallimento.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione software sarà un’interfaccia grafica composta da due diverse parti:
- La prima parte sarà dedicata alla previsione, dato un periodo di tempo limitato e un reparto verrà visualizzata la previsione dell’occupazione dei posti letto di quel reparto in quel periodo sia in forma tabellare che in forma grafica, attraverso un diagramma a torta.
- La seconda parte implementerà invece la funzione di simulazione, fornita una data di inizio ricovero, ed eventualmente anche di fine, e il reparto, verrà visualizzata la migliore soluzione possibile trovata per la sistemazione del paziente in quel periodo.

**Comment by fulcorno** [comment]
Proposta accettata.
