### ISSUE TITLE
"Start-up new network trade" di Delia Bonfiglio

### ISSUE THREAD

**Issue by deliabonfiglio** [TdP-prove-finali/Introduzione#2]
### Studente proponente

s213426 Bonfiglio Delia

### Titolo della proposta

"Start-up new network trade"

### Descrizione del problema proposto
L'applicazione desktop prevederà una gestione a livello di aggiunta, cancellazione e modifiche di punti vendita, gestione accentrata dei magazzini dei singoli negozi, gestione efficace del punto vendita tramite KPI commerciali e indicatori economici.

### Descrizione della rilevanza gestionale del problema

L'obiettivo che mi prefiggo è di sviluppare un'applicazione desktop che possa simulare la gestione centralizzata della rete di vendita per un monitoraggio puntuale e costante attraverso tutti i principali indicatori commerciali ed economici. 
Ipotizzo, a tal fine che i punti vendita saranno collegati in remoto tramite la piattaforma software. In questa fase mi occuperò della creazione della suddetta piattaforma, mentre per quanto riguarda il trasferimento dei dati, suppongo che l'azienda sia dotata di un software per la trasmissione dei dati a inizio e fine giornata.
Mi pongo di ottenere un'efficace gestione di magazzino e di un controllo puntuale del ROE del singolo punto vendita.

### Descrizione dei data-set per la valutazione	

Il software farà uso di un database contenente info di tipo statistico, tabella con anagrafica di punti vendita con informazioni di georeferenziazione, tabella dei prodotti, tabella gestione magazzino del punto vendita ed un'ultima dei dati giornalieri.

Poiché ipotizzo che l'utilizzo di questo software sarà destinato al monitoraggio dei punti vendita di una data azienda, intendo utilizzare dati specifici derivanti da un'azienda inventata, al fine di poter simulare realmente il funzionamento del progetto.

### Descrizione preliminare degli algoritmi coinvolti	

Al fine di poter simulare la gestione della rete di vendita, intendo implementare algoritmi di inserimento, cancellazione, modifica dei dati del punto vendita, ricerca di tipo geografico generale, ad esempio i punti vendita in una città selezionata, ordinati secondo profitto maggiore, e ricerca di tipo specifica ad esempio una volta selezionato un punto vendita si possono vedere quelli a lui più vicini. 

Intendo inoltre implementare il progetto al fine di poter visualizzare e controllare il magazzino e le scorte selezionato un punto vendita, e su questo fare calcoli di andamento giornaliero e mensile delle vendite, in aggiunta consentire una migliore comprensione dei suddetti dati tramite un output anche di tipo grafico.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

Mi propongo di predisporre un'applicazione desktop di supporto per la gestione efficace dei punti vendita, per rispondere ai requisiti di un commitment di un noto brand commerciale che intende avviare e gestire un network commerciale nel territorio di una delle aree Nielsen (delimitata dalle regioni del Sud Italia).
Pertanto l'utente potrà sia controllare e modificare in quantità, posizione e dati i punti vendita dell'azienda, sia valutare l'andamento del singolo per verificare i profitti, il ROE e tramite vari indicatori economici comprendere a livello specifico l'efficienza della Sua gestione.

**Comment by fulcorno** [comment]
Non mi è chiaro un punto: l'applicazione è rivolta al singolo punto vendita o al gestore della catena? Generalmente sembra rivolta al gestore (centralizzato), che quindi analizza i dati di tutti i suoi punti vendita. Però in alcuni punti (ad es. quando parli di gestione del magazzino) sembra invece parlare del singolo punto vendita.

Per quanto riguarda il data-set, se stiamo parlando di una rete di punti vendita, con un catalogo ben fornito, credo che non sia semplice "inventarsi" dei dati realistici. Oppure hai già trovato delle fonti dati utilizzabili?

Chiariti questi due punti, il resto è ok.

**Comment by deliabonfiglio** [comment]
L'applicazione è rivolta al gestore del punto vendita, in modo da poter supportare il suo lavoro di monitoraggio, controllo e analisi dell'andamento della catena di punti vendita,sia a livello globale sia a livello puntuale, infatti questi potrà anche valutare nello specifico uno dei negozi, appunto visionando il magazzino,  il profitto e il ROE. 

Per il data-set, pensavo di modificare i dati forniti su Istat di qualche società reale, ma modificarne i valori, ad esempio tramite Excel, in modo da avere tutti dati inventati.
In ogni caso se Lei ha suggerimenti generali o data-set utilizzabili, li accetto molto volentieri.

**Comment by fulcorno** [comment]
ok, per me va bene (a parte il fatto che non so se, nella realtà, il gestore di un punto vendita possa vedere l'andamento degli altri punti vendita, a lui concorrenti... ma a scopo didattico va bene).

Purtroppo non conosco direttamente data-set utilizzabili. Però qualcosa si trova. Ad esempio in 30 sencondi ho trovato http://archive.ics.uci.edu/ml/datasets/online+retail , https://bigml.com/gallery/datasets/consumer_and_retail , http://recsyswiki.com/wiki/Grocery_shopping_datasets , https://www.kaggle.com/c/rossmann-store-sales/data (cercando "shop data set").

Procedi pure con il lavoro
