### ISSUE TITLE
Ottimizzazione di un corredino in base al budget

### ISSUE THREAD

**Issue by chiaralansia** [TdP-prove-finali/Introduzione#20]
###Studente proponente

s234834 Chiara Lanza

###Titolo della proposta

Ottimizzazione di un corredino in base al budget

### Descrizione del problema proposto

Il problema da risolvere è la formazione del corredino perfetto. Poiché in base al budget iniziale le proposte sono diverse in quantità e qualità.

### Descrizione della rilevanza gestionale del problema

L'applicazione può essere usata dal commerciante per semplificare il momento della vendita e confrontare i guadagni in base ai diversi abbinamenti o dal cliente per farsi un'idea di ciò che può comprare.

### Descrizione dei data-set per la valutazione	

I dati sono autoprodotti e ancora da terminare.
Sono presenti nome dell'articolo, categoria (sulla quale lavorerò per il problema dello zaino), stagione (dove assente è perché parte essenziale del corredino indipendentemente dalla stagione), prezzo al dettaglio e all'ingrosso. I dati sono fittizi e inventati nonostante ci sia una base di conoscenza preliminare del settore e quindi verosimili.
[LISTINO CHIARA.xlsx](https://github.com/TdP-prove-finali/Introduzione/files/3113233/LISTINO.CHIARA.xlsx)

### Descrizione preliminare degli algoritmi coinvolti
	
Attraverso un algoritmo ricorsivo con i dovuti vincoli si risolverà il problema dello zaino che avrà però più soluzioni candidate, quella perfetta è quella con guadagno maggiore per il commerciante .

I vincoli saranno di necessità (ad esempio non possono mancare body o tutine), di proporzione (se ci sono cinque tutine non ha senso avere meno di cinque body), sensati (il lenzuolo solo se prendo anche il materasso) ed altri che in corso di programmazione mi verranno in mente.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'output saranno le varie combinazioni se verrà selezionata la modalità cliente, invece sarà mostrato solo la combinazione perfetta con guadagno massimo se la modalità sarà commerciante. Ci sarà la possibilità di mostrare anche la lista delle varie combinazioni complete di prezzo di vendita, prezzo di acquisto e percentuale globale di guadagno.

**Comment by fulcorno** [comment]
Proposta accettata.
Suggerisco di formalizzare meglio il problema di ottimizzazione o i problemi di ottimizzazione (da fare come primo passo del lavoro), per chiarire bene quali sono i dati di inputi, quali i vincoli, e quali le funzioni obiettivo.
