### ISSUE TITLE
EV Manager - Tool per la Gestione della Mobilità Elettrica

### ISSUE THREAD

**Issue by ingalessandrobaldo** [TdP-prove-finali/Introduzione#21]
### Studente proponente

s236651 Baldo Alessandro

### Titolo della proposta

Tool per la Gestione della Mobilità Elettrica

### Descrizione del problema proposto

L’applicazione si propone di sensibilizzare l’utenza automotive, simulando, in prima istanza, una semplice analisi di mercato tra gli autoveicoli elettrici presenti tuttora nel mercato, includendo alcuni concept e modelli che debutteranno nell’arco di massimo 2 anni. 
La seconda parte del programma permette di pianificare una rotta all’interno dello stato della California (ottimo compromesso per la sua morfologia per testare le prestazioni in termini di autonomia della batteria), tenendo conto delle soste obbligatorie a delle stazioni di ricarica

### Descrizione della rilevanza gestionale del problema

La mobilità elettrica è un tema che, negli anni a venire, diventerà centrale nel mondo dei trasporti. Pochi software al momento riescono ad accomunare sistemi di navigazione con un listino dell’offerta automotive a impatto zero. 
L’applicazione sfrutterà semplici principi di Ricerca Operativa (teoria dei grafi, cammino minimo, albero ricoprente) applicati al mondo della programmazione per offrire, in un contesto semplificato ma intuitivo, un primo approccio a un settore, sicuramente in crescita, ma ancora acerbo (sia lato software, sia lato trasporti). 
A discrezione dell’utente sarà, ove possibile, la scelta di un percorso a tempo e costo minimo, a massimo numero di città visitabile lungo il percorso

### Descrizione dei data-set per la valutazione	

L’applicazione si appoggia su tre tipologie di data set:
Un database contenente le informazioni su tutte le stazioni di ricarica elettriche, aggiornato ad aprile 2019, nello stato della California (fonte: https://afdc.energy.gov/fuels/electricity_locations.html#/analyze?region=US-CA&fuel=ELEC&ev_levels=all&show_map=true)
Un database contenente l’elenco di tutte le città nello stato della California con informazioni sulle coordinate geografiche (fonte: https://www.kaggle.com/camnugent/california-housing-feature-engineering#cal_cities_lat_long.csv)
Un database contenente l’elenco di tutti gli autoveicoli elettrici presenti sul mercato e la cui uscita è programmata entro il 2021 (fonte: ev-database.org/ev-databse.uk)

### Descrizione preliminare degli algoritmi coinvolti	

Il programma sfrutterà concetti di Teoria sui Grafi, Cammino Minimo, Albero Ricoprente, Ricorsione per quanto riguarda il calcolo del percorso dato il grafo costruito con la posizione delle stazioni di ricarica, integrati con letture ottimizzate da db e concetti di Event Handling

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

Il pannello principale di interazione permette il lancio delle due grafiche principali che implementano rispettivamente la Scelta/Confronto tra i modelli di autoveicoli elettrici (attraverso un pannello con la scelta delle preferenze) e il Calcolo del percorso di navigazione all'interno dello Stato della California dati punti di partenza e arrivo. I tre pannelli sono collegati e richiamabili da ciascuno di loro mediante un bottone home (per ritornare al pannello iniziale) e bottoni Back e Forward

**Comment by fulcorno** [comment]
La proposta va bene.
Unica domanda: mi pare che il database ev-database.org non sia ad accesso libero (o si copiano i dati a mano, oppure bisogna pagare per avere un export dei dati). Come pensi di procedere?

**Comment by fulcorno** [comment]
Come ci siamo detti in aula, va bene per lo scraping manuale dei dati da ev-database. Ricorda di NON includere quei dati nel progetto su github (ma inviarmeli separatamente) in quanto le condizioni di licenza non lo permettono.
