### ISSUE TITLE
Promozione di nuovi supermarket 

### ISSUE THREAD

**Issue by CampanioloNF** [TdP-prove-finali/Introduzione#22]
### Studente proponente

s226878 Nicolò Flavio Campaniolo

### Titolo della proposta

Promozione di nuovi supermarket 

### Descrizione del problema proposto

Si intende realizzare un programma capace di definire il luogo ideale per l'apertura di nuovi punti vendita.
Il programma riceve dunque in input la quantità di supermercati che si intende aprire e restituisce un set di comuni, appartenenti alla medesima regione, dove si è valuta essere più idonea l'apertura dei nuovi punti vendita.

### Descrizione della rilevanza gestionale del problema

L'apertura di nuovi punti vendita è un problema di rilevanza gestionale. La cattiva gestione dell'investimento di un capitale
può portare al fallimento dell'azienda ed è dunque necessario ottimizzare, dove possibile, tale gestione.

In tale problema si ipotizza il caso in cui un supermarket voglia lanciare una campagna regionale per l'apertura di nuovi punti vendita.

Tale algoritmo restituisce un set di comuni dove le condizioni si prestano migliori alla nascita di un nuovo supermarket. 
Tuttavia, data la vastità del campo preso in considerazione, tale algoritmo si limita ad indicare esclusivamente il nome dei comuni maggiormente interessati, dove eventualmente sarà il caso di eseguire indagini di mercato più dettagliate.

Tale programma permette dunque di conoscere i principali rivali sul mercato in una determinata zona e le loro eventuali strategie di espansione.

### Descrizione dei data-set per la valutazione	

La risoluzione di tale problema avviene mediante l'utilizzo di due data-set. Nella fattispecie abbiamo un data-set contenente la lista dei supermercati presenti in Italia. Tale tabella contiene il comune, la provincia, la regione, il nome ed un identificativo del supermercato. Un secondo data-set contiene invece un censimento riferito al 2011 per tutti i comuni italiani. Tengo a dire che tali dati, pur non essendo esattamente reali, possono essere comunque considerati realistici

### Descrizione preliminare degli algoritmi coinvolti	

In tale applicazione saranno presenti algoritmi di ricerca e ricorsivi. Gli algoritmi di ricerca si occuperanno di interrogare il database per la restituzione di una lista di supermarket presenti nella stessa regione o aventi lo stesso nome.

Un algoritmo più complesso si occuperà della ricerca del set di comuni appartenenti alla stessa regione capace di ottimizzare l'apertura di nuovi punti vendita.
Tale algoritmo si occuperà di calcolare un 'punteggio' assegnato ad ogni comune che indichi quanto tale comune si presti favorevole ad ospitare un nuovo punto vendita. Tale punteggio tiene conto del numero di supermarket per abitanti presenti all'interno del comune. Si tende dunque a prediligere i comuni nei quali la saturazione sia inferiore. Vengono inoltre scartati i comuni in cui il database non riconosce la presenza di supermarket, ad esempio perché aventi un numero troppo esiguo di abitanti. Tale algoritmo si preoccupa di verificare la presenza del supermarket che intende espandersi nei vari comuni e tenerne conto nella valutazione (Se una determinata catena intende espandersi a Torino viene tenuto presente di quanti punti vendita della stessa catena siano già presenti a Torino). 

Per la realizzazione di un tale programma è necessario un algoritmo ricorsivo. Tale algoritmo calcola all'interno di ciascuna regione il set di comuni che ottimizzino il punteggio. Successivamente le confronta fra loro scegliendo la regione ottimale.

Per arrivare a tale soluzione tale programma riceve in input il nome della catena di supermarket che intende espandersi ed il numero di punti vendita che si intende aprire. Viene anche chiesto il numero massimo di punti vendita regionali ammessi. In aggiunta l'utente può anche aggiungere una regione dove si intende aprire i punti vendita e tale algoritmo restituirà esclusivamente
il set di comuni che massimizzi quella determinata regione

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente si troverà davanti un interfaccia dove avrà la possibilità di scegliere da una lista di supermarket quello interessato. Cliccando il bottone 'Cerca', riceverà in un'apposita area di testo il set di supermarket della catena selezionata, nei rispettivi comuni di ubicazione. In maniera analoga, avendo selezionato esclusivamente la regione, l'algoritmo restituisce nella medesima area, tutti i punti vendita presenti nella regione selezionata. E' possibile anche scegliere contemporaneamente una regione ed una linea di supermarket. In tal caso verranno restituiti tutti i punti vendita di tale catena nella regione selezionata.

Dopo aver selezionato una catena di supermarket, il numero di punti vendita che si intende aprire e la quantità massima di punti vendita regionali della medesima linea, sarà disponibile il bottone 'Espandi'. Nel caso non si sia selezionata alcuna regione, tale pulsante inizia la
ricerca del set di comuni, appartenenti alla medesima regione, che ottimizzi l'apertura dei nuovi punti vendita. Tale risultato è assoluto. Nel caso si voglia un risultato relativo ad una regione in particolare sarà necessario selezionarla. 

Il bottone 'Reset' ripulisce l'area di testo.

**Comment by fulcorno** [comment]
Ok, va bene, la proposta è approvata.
Fulvio
