### ISSUE TITLE
Tool per Società Calcistica

### ISSUE THREAD

**Issue by olehera** [TdP-prove-finali/Introduzione#23]
### Studente proponente

s238155 Herashchenko Oleksandr

### Titolo della proposta

Tool per Società Calcistica

### Descrizione del problema proposto

Si propone una possibile applicazione per talent scout, dirigenti o più in generale stakeholder di una società di calcio. 
In particolare il programma si presenta utile per ottimizzare la rosa: scelta una squadra, si ottiene l'elenco dei giocatori che compongono la rosa e alcune statistiche significative su di essa, in modo da capire quali caratteristiche si possono migliorare agendo sul mercato. L'utente deve inserire in input il budget massimo e scegliere quali parametri si vorrebbero migliorare.

### Descrizione della rilevanza gestionale del problema

Negli ultimi anni si è assistito ad una veloce e imponente evoluzione economica delle società di calcio, le quali attualmente possono essere definite delle vere e proprie aziende. E' dunque interessante in una prima analisi andare a valutare quantitativamente e qualitativamente la rosa di giocatori disponibili per capire quali miglioramenti si possono apportare nelle successive sessioni di calcio-mercato. 
In una seconda analisi si può inoltre capire come l'aggiunta/sostituzione di calciatori possa influenzare la rosa, sia dal punto di vista economico che qualitativo (fisicità, velocità, ecc..).

### Descrizione dei data-set per la valutazione	

La fonte dal quale deriva il data-set è il famoso video-gioco FIFA 2019. 
Link: https://www.kaggle.com/karangadiya/fifa19 
I dati sui giocatori sono abbastanza attendibili e il più possibile vicini alla realtà in quanto sono stati realizzati da specialisti del settore sulle misurazioni fatte durante tutto l'anno precedente sui giocatori. 
Il formato dei dati è CSV, dal link è possibile scaricare il data-set che presenta una tabella con oltre 18 000 giocatori e oltre 80 colonne con le caratteristiche esaustive di ognuno di essi.
Dunque è necessario formattare i dati ed eliminare le informazioni che sono superflue rispetto all'analisi proposta, devo ancora valutare se estrarre dal data-set solo i calciatori della serie A piuttosto che dei 5 principali campionati europei.

### Descrizione preliminare degli algoritmi coinvolti	

Il principale algoritmo che verrà implementato sarà sulla ricorsione: data la lista di giocatori che rappresentano la rosa e specificando una lista di giocatori sotto osservazione si provano tutte le possibili combinazioni, fino a che non si trova la soluzione migliore, i vincoli sono i parametri inseriti dall'utente.
Oltre al budget disponibile un'altro parametro importante potrebbe essere il numero massimo di giocatori rimpiazzabili/vendibili in modo da liberare spazio in rosa (pensavo ad un limite minimo e massimo di giocatori nella rosa) ed aumentare il budget. L'utente deve scegliere inoltre quale obiettivo vuole migliorare: vorrei calcolare dei parametri più generali che derivano da alcuni dati che sono disponibili per ogni giocatore.

### Descrizione preliminare delle funzionalità previste per l'applicazione software	

L'interfaccia si divide sostanzialmente in due sezioni: una sarà dedicata alla parte di visualizzazione delle caratteristiche della rosa attuale, oltre all'elenco dei giocatori vorrei rappresentare alcune statistiche calcolate globalmente sulla rosa ed eventualmente opportuni grafici per semplificare e rendere più efficace la visualizzazione.
La seconda parte sarà incentrata sull'ottimizzazione della rosa quindi una schermata permetterà di inserire e scegliere i parametri dell'analisi, in risposta ci sarà l'elenco della rosa ipotetica con le statistiche calcolate su di essa, potrebbe essere interessante anche un confronto delle statistiche tra la rosa attuale e quella ipotetica.

**Comment by fulcorno** [comment]
La proposta va bene.

Se ben capisco, si tratta di una variante del problema dello zaino (dentro il budget disponibile, inserisco quanti più possibile giocatori "bravi") di tipo multi-obiettivo (i giocatori sono valutati da molti punti di vista diversi) e con vincoli aggiuntivi (non posso avere tutti attaccanti), e che parte da una rosa esistente (variandola) anziché da zero.
Cercherei di applicare anche dei filtri o delle strategie di ricerca per evitare di dovere impostare una ricorsione che trovi 11 persone da un insieme di 500, che avrebbe tempi di esecuzione inaccettabili.
