### ISSUE TITLE
Programmazione dei turni lavorativi del personale infermieristico in un reparto ospedaliero

### ISSUE THREAD

**Issue by RiccardoBaldassa** [TdP-prove-finali/Introduzione#27]
### Studente proponente

s227583 Baldassa Riccardo

### Titolo della proposta

Programmazione dei turni lavorativi del personale infermieristico in un reparto ospedaliero 

### Descrizione del problema proposto

L'applicazione si propone di generare in modo automatico ed ottimale l'orario lavorativo di una serie di infermieri assegnati ad un certo reparto ospedaliero.
La creazione manuale dei turni infermieristici è un'operazione complessa che richiede molto tempo, soprattutto quando il numero di infermieri da gestire aumenta.
L'obbiettivo dell'applicazione è quindi quello di automatizzare quest'operazione rispettando i vincoli normativi reali, cercando di assegnare i turni nel modo più equo possibile e cercando di andare incontro alle esigenze dei singoli infermieri.

### Descrizione della rilevanza gestionale del problema

La programmazione dei turni di lavoro degli infermieri negli ospedali è materia di studio tutt'oggi, esistono diverse tipologie di gestione in questo ambito che sono state sviluppate nel corso degli anni, ognuna con le proprie problematiche. Tuttavia, tutte queste diverse tipologie di gestione vengono attualmente ancora implementate manualmente.
La gestione di questo problema è molto complicata per il gran numero di vincoli, di variabili e di dati da tenere in conto. Una ricerca manuale quasi sicuramente non porterà alla soluzione migliore, sopratutto quando il personale infermieristico cresce.
L'utilizzo di questa applicazione permetterebbe oltre al far risparmiare molto tempo agli addetti che svolgono questo compito, di valutare e programmare nel modo più efficace i turni degli infermieri, cercando di non avere disparità di trattamento e basandosi sulle ferie richieste da essi.

### Descrizione dei data-set per la valutazione	

I dati utilizzati comprenderanno la lista degli infermieri assegnati al reparto.

### Descrizione preliminare degli algoritmi coinvolti	

L'algoritmo principale utilizzerà la ricorsione e sarà molto articolato perché dovrà verificare una molteplicità di vincoli. L'algoritmo cercherà di generare la programmazione trimestrale dei turni di tutti gli infermieri, a partire dalle loro richieste riguardo le ferie che vorranno fare nei seguenti tre mesi.
La soluzione sarà accettata se tutti i turni lavorativi del reparto verranno coperti e se i vincoli contrattuali degli infermieri verranno rispettati.
Oltre al rispetto dei vincoli normativi, l'algoritmo cercherà di trovare la soluzione ottimale che permetta di non creare disparità di trattamento tra gli infermieri e, seguendo delle norme di buon senso che comunemente si cerca di seguire, si cercherà di trovare la soluzione che rispetti maggiormente una situazione lavorativa ottimale, senza sovraccarichi di lavoro e con riposi lavorativi ben distribuiti, per esempio: minimizzazione del numero di notti consecutive per ogni infermiere, massimizzazione del numero di fine settimana liberi per ogni infermiere, ecc. 

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

All'avvio dell'applicazione l'utente dovrà indicare qual è il numero di infermieri necessari per ognuno dei tre turni lavorativi, poi inserirà gli infermieri che lavorano in quel reparto all'interno del database. Dopo aver inserito tutti gli infermieri dovrà indicare per ognuno di essi in quali giorni vorrebbero avere le ferie nei seguenti tre mesi.
A questo punto l'utente potrà avviare la funzione principale che proverà a generare la programmazione dei turni a partire dalle preferenze degli infermieri, se l'applicazione trova questa soluzione allora verrà mostrata, altrimenti verrà indicato per quale motivo non è riuscita a generare la soluzione e se è possibile genererà comunque una soluzione attuando qualche variazione alle richieste degli infermieri. Dopo aver accettato la soluzione proposta, sarà possibile ripetere l'operazione di richiesta ferie degli infermieri e generare la programmazione dei turni per i successivi tre mesi. Sarà inoltre possibile visionare l'orario assegnato ad ogni singolo infermiere.

**Comment by fulcorno** [comment]
Ho 2 osservazioni su questa proposta:

1. la descrizione del data-set è incompleta. Non è vero che sia sufficiente conoscere l'elenco degli infermieri. Infatti è necessario che il data-set contenga anche le richieste di ferie di ciascuno degli infermieri. Ci sono poi molti vincoli descritti nel testo (da quelli di legge a quelli di "buon senso"), sarebbe bene che non fossero "sparsi" nel testo ma concentrati in una tabella del DB od in un file di configurazione.

1. la parte di "caricamento dati" descritta nel funzionamento dell'applicazione non è interessante ai fini della tesi (caricamento infermieri, caricamento richieste ferie, ...), suggerisco di mantenerla al minimo assoluto (l'interfaccia di gestione di questi dati porterebbe via moltissimo tempo), o quasi a zero.

Con queste due precisazioni, la proposta è accettate.
