### ISSUE TITLE
Programmazione ottimale per visite turistiche

### ISSUE THREAD

**Issue by rubenIng93** [TdP-prove-finali/Introduzione#28]
### Studente proponente

s236819 Berteletti Ruben

### Titolo della proposta

Programmazione ottimale per visite turistiche

### Descrizione del problema proposto

L'applicazione si propone di consigliare all'utente una sequenza di monumenti da visitare in base al tempo di permanenza in una città, in maniera da rendere l'esperienza il più godibile possibile prestando attenzione ad un budget massimo messo a disposizione ed a eventuali preferenze soggettive. Come funzionalità aggiuntiva verrà fornito uno strumento per valutare, nel caso in cui un monumento dovesse divenire momentaneamente inagibile al pubblico, la perdita in termini monetari che risentirebbe la città coinvolta.

### Descrizione della rilevanza gestionale del problema

Spesse volte i visitatori di una città non hanno una messa a fuoco precisa sul programma da seguire per ammirare le migliori opere e soprattutto non hanno mai un dato qualitativo sul budget necessario: l'applicazione risolverà questi problemi.
Lo strumento di valutazione per l'inagibilità può fornire importanti informazioni all'ente responsabile riguardo all'impatto di un ipotetico restauro.

### Descrizione dei data-set per la valutazione	

Verrà creato un data-set ad hoc registrando città per città ogni monumento ed a questi attribuito un punteggio di rilevanza. Parte integrante dell'applicazione sarà quella di consentire da parte della città l'inserimento delle proprie opere.

### Descrizione preliminare degli algoritmi coinvolti	

L'ottimizzazione della visita verrà implementata mediante un algoritmo ricorsivo che andrà a trovare la lista di monumenti ottima in base ai parametri forniti dall'utente, quali la permanenza nella città, il budget, la preferenza per un particolare monumento (o uno da evitare,  magari perchè già visto in una visita precedente) e il tempo che vuole dedicarne.
L'algoritmo considererà anche il vincolo di ogni sito dell'orario di apertura al pubblico.
Il tool per l'inagibilità sarà completato mediante un confronto tra due simulazioni: dato un campione di 'x' persone, una prima simulazione calcolera il guadagno della città prima di dichiarare l'inagibilità e una seconda a provvedimento avvenuto, tenendo conto che in base all'importanza del monumento chiuso, una percentuale di 'x' non sarà più attirata nel visitarla.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione avrà un'interfaccia dedicata a seconda del tipo di utente:
-Il visitatore dovrà scegliere una città, indicare il tempo di permanenza, il budget, eventuali monumenti da escludere, e le ore da dedicare alla visita. Come risultato avrà la lista ottimale da visitare in base alle proprie esigenze e l'indicazione del costo totale;
-L'amministrazione della città avrà la possibilità di mantenere il database aggiornato mediante l'applicazione inserendo una nuova opera oppure indicare come inagibile per restauro un'opera già presente e potrà prima di effettuare quest'ultima operazione, averne un resoconto economico qualitativo.

**Comment by fulcorno** [comment]
Sono necessari maggiori informazioni relativamente al data-set. Quali informazioni ti servono per ciascun documento? Quanti documenti e/o quante città devi caricare? Perché non possono funzionare elenchi già pronti come ad esempio http://www.datiopen.it/it/opendata/Mappa_dei_monumenti_in_Italia ? (eventualmente integrandole con orari e costi, su un sottoinsieme campione di città).

Dubbi riguardo all'algoritmo: l'itinerario è sempre comunque interno ad una sola città, è corretto?

La parte sulla simulazione non mi è chiara... che cosa viene simulato? un flusso di turisti? e come faccio a sapere le preferenze (budget e tempo) di tali turisti?

Suggerirei di concentrare la proposta su una delle due parti: o la ricerca del percorso ottimale, oppure la simulazione dei periodi di inagibilità.

Per favore verifica questi punti ed aggiorna la proposta.

**Comment by rubenIng93** [comment]
Per i data-set: ho controllato gli elenchi presenti nel sito che mi ha linkato e sono per la maggior parte incompleti, ad esempio "Mappa dei monumenti in Italia" fa riferimento solo a monumenti commemorativi; mentre altri registrano o solo fontane o solo siti archeologici ecc.. ed in maniera incompleta (ad esempio per la città di Roma non è presente il Colosseo...). Io ho usato il termine monumento in senso improprio perchè la mia idea era quella in realtà di considerare per una città tutti i siti di interesse colturare quindi costruzioni, fontane, musei e quant'altro. Adatti a questo scopo ho trovato solo data-set relativi a Firenze, Palermo e la Regione Sardegna.
Altrimenti potrei ripiegare sui soli musei, che godono di un elenco completo per il panorama italiano e comunque a mio avviso rimarrebbe sensato perchè tipicamente sono le visite che "fatto perdere più tempo".
In ogni caso pensavo di integrare i dati con oltre che orari e costi, con la permanenza necessaria per la visita e un punteggio intero per l'importanza del sito (es. da 1 a 5 --> se 5 visita imprescindibile, se 1 trascurabile) in maniera da privilegiare i migliori nel caso in cui l'utente avesse poco tempo a disposizione.

Per l'algoritmo: si, l'utente può selezionare solo una città e ottimizzare la visita su quella.

Per la simulazione: avevo in mente tenere fisso per campione il numero di persone che ha intenzione di visitare una città, trovare con la ricorsione l'itinerario migliore per una giornata di visita ed avviare una prima simulazione che calcoli il guadagno della città. Dopo aver salvato il valore parte una seconda simulazione che ha impostati come parametri, a seconda del punteggio di importanza del sito inagibile, una probabilità dell'utente di decidere di non iniziare nemmeno la visita (esempio: se Tizio è a conoscenza dell'inagibilità degli Uffizi, decide di non visitare Firenze); verrà salvato il guadagno della città e confrontato con il risultato della prima simulazione e tramite differenza si ricaverà qualitativamente la perdità. Per un valore più affidabile, pensavo di far partire più simulatori di entrambi i tipi per usare poi come output finale i valori medi.

Dal momento che i data-set non sono del tutto affidabili, temo che la simulazione avrebbe risultati di scarso interesse, quindi mi concentrerei sulla ricorsione e quindi sulla visita ottima.
