### ISSUE TITLE
Ottimizzazione della gestione e contabilità direzionale in agriturismo

### ISSUE THREAD

**Issue by viscontidavide** [TdP-prove-finali/Introduzione#29]
### Studente proponente

s227038 Visconti Davide

### Titolo della proposta

Ottimizzazione della gestione e contabilità direzionale in agriturismo

### Descrizione del problema proposto

L'obiettivo del programma è quella di consentire la gestione della parte economica in un agriturismo in tutto il suo ciclo di vita, dall'acquisto dei prodotti che saranno in seguito serviti alla gestione degli impiegati, attraverso la creazione di un opportuno data-set.

### Descrizione della rilevanza gestionale del problema

A mio avviso è rilevante dal punto di vista gestionale perchè si tratta di creare un programma che aiuti a tenere sotto controllo i maggiori aspetti e che permetta così di ottimizzare la gestione dell'agriturismo permettendo di svolgere i calcoli economici di maggiore interesse.

### Descrizione dei data-set per la valutazione	

Dato che l'azienda è un'azienda reale situata nell'astigiano vicino a dove abito, la mia intenzione era quella di creare un data-set basandomi su dati reali a cui posso agevolmente avere accesso, cambiando solamente i nomi in modo da mantenere un buon grado di anonimità; il data-set immagino comprenderà essenzialmente i vari fornitori, i lavoratori e le diverse categorie di spesa, in modo da avvicinarsi i più possibile alla realtà e essere veramente utilizzato in azienda come strumento di aiuto al controllo.

### Descrizione preliminare degli algoritmi coinvolti	

L'applicazione dovrà essere in grado di svolgere alcuni tra i più rilevanti calcoli economici in un ristorante, come ad esempio valutare l'incidenza delle spese fisse e variabili, calcolare il break even point, valutare gli indici di rotazione del magazzino di prodotti deperibili e non per ottimizzare gli acquisti, valutare l'incidenza delle tasse nella gestione e potrebbe contenere un algoritmo di simulazione ad eventi che permetterebbe di aiutare a organizzare la preparazione di una serata impostando alcuni parametri riguardanti l'arrivo dei clienti e la scelta del menù degustazione che farà ognuno (nel caso concreto l'agriturismo permette ai propri clienti di decidere una tra tre formule di menù degustazione e di aggiungere a essi dei supplementi quali ad esempio vini partoclari).

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione sarà dotata di un'interfaccia grafica intuitiva e avrà lo scopo di esere realmente usata nel quotidiano come aiuto nella gestione dell'agriturismo e permetterà all'utente di raggruppare le diverse spese sostenute per gruppo o periodo e andare a calcolare i margini di guadagno o, come già detto nel punto precedente, gli indici economici più utili alla gestione (a questo proposito chiederò aiuto e consiglio a colui che poi dovrà utilizzare l'applicazione, un ragazzo laureato in economia, mio coetaneo e amico che mi assisterà con interesse). Inoltre l'applicazione dovrà essere in grado di stampare a video i parametri utili della simulazione ad eventi e permettere di inserire dinamicamente tutti i dati utili alla gestione contabile all'interno del database ogni qualvolta risulti necessario che un evento venga registrato (nuova spesa,nuovo fornitore, cambio cameriere, ecc...).

**Comment by fulcorno** [comment]
La proposta è interessante, ma non mi pare molto centrata sui contenuti algoritmici del corso.
Si tratta di una grossa parte di gestione di dati di tipo "anagrafico" (prodotti, fornitori, clienti, ...), sicuramente utilissima ma algoritmicamente molto povera (oltre che terribilmente dispendiosa in termini di tempo di sviluppo, vista la quantità di FORM e di controlli che devono essere fatti). Il tempo necessario ad implementare queste parti sarà di gran lunga maggiore dei 3 crediti che puoi spendere con la tesi.

Il calcolo degli indicatori economici, inoltre, mi sembra la "pura" applicazione di una serie di formule già definite. Anche qui molto utile aziendalmente, ma banale algoritmicamente.

La parte sulla simulazione potrebbe essere la più interessante, ma dal testo non si capisce molto in che cosa consiste (andrebbe dettagliata meglio).

I miei suggerimenti sono:

- proponi di sviluppare l'applicazione sotto forma di stage per l'azienda (eventualmente retribuito, perché no?), in cui c'è una gran parte di sviluppo ma una difficoltà algoritmica tutto sommato gestibile. In tal caso:
    - valuta bene se sia opportuno fare un'applicazione JavaFX (che sarebbe utilizzabile da un solo PC) oppure non sia meglio fare un'applicazione Web
    - ricerca se non esista un qualche "gestionale open source" già pronto che supporti tutte le attività (abbastanza standard) che sono necessarie
- identifica invece un sotto-problema (di simulazione o di ottimizzazione) e focalizza la proposta di tesi su quel problema.

Scrivimi pure qui se hai dei dubbi o domande.

**Comment by fulcorno** [comment]
esempi: https://www.icstools.it/elenco-gestionali-italiani-opensource/

**Comment by viscontidavide** [comment]
Va bene, grazie per i suggerimenti e per la sua disponibilità. Nei prossimi giorni cercherò di riformulare la proposta per renderla più attinente alla tematica del corso ed incentrarla su una parte prevalentemente algoritmica.

**Comment by viscontidavide** [comment]
Ho pensato ad una possibile variazione che riduca al minimo la parte di creazione e gestione dati e si concentri maggiormente sull'algoritmo di simulazione permettendo all'utente di simulare lo svolgimento di una manifestazione all'aperto nel quale l'agriturismo (nonchè organizzatore) fornirà servizio di ristorazione.

Nel dettaglio, l'applicazione permetterà all'utente di selezionare un evento da svolgersi all'aperto tra quelli proposti; l'evento sarà caratterizzato da un costo fisso di organizzazione e da un numero di persone (variabile casualmente nelle diverse simulazioni anche dello stesso evento) che vi prenderà parte. Vi saranno diverse classi di persone che saranno utilizzate a seconda della manifestazione selezionata al fine di  tenere conto delle differenti preferenze culinarie e quindi delle diverse spese (anchesse variabili in un range predefinito) che ognuno potrebbe affrontare (ad esempio si pensi alla diversità tra un raduno di motociclisti e uno spettacolo per famiglie); vi saranno inoltre molteplici piatti da poter scegliere, non tutti presenti in tutti gli eventi, e ognuno sarà caratterizzato dal proprio prezzo
e da un tempo di preparazione.

L'utente infine potrà selezionare un numero di camerieri che si occuperanno di servire al bancone i clienti e avviare la simulazione; il programma dovrà tenere traccia degli acquisti fatti dai partecipanti, dei clienti che risulteranno insoddisfatti perchè hanno aspettato troppo tempo in coda; dovrà inoltre calcolare il guadagno della serata al netto di tutte le spese e aiutare quindi a decidere, attraverso diverse simulazioni, l'evento più redditizio (o meno dispendioso in termini di preparazione) da svolgersi.

**Comment by fulcorno** [comment]
Dal tuo ultimo commento, mi pare che la simulazione proposta si discosti parecchio rispetto all'idea iniziale. Ad esempio, il data-set che hai citato prima direi che non c'entra più nulla (o molto poco) con i dati che servono per simulare gli eventi di richiesta/preparazione/consegna piatti.

Il mio suggerimento è di provare a riscrivere la proposta per intero, in modo coerente, togliendo le parti che non c'entrano più.
Puoi incollarla qui come un commento, oppure aprire una nuova issue.
