### ISSUE TITLE
Gestione scorte di un magazzino musicale

### ISSUE THREAD

**Issue by GJGits** [TdP-prove-finali/Introduzione#3]
### Studente proponente

s204471 Marco Clemente Nanci

### Titolo della proposta

Gestione scorte di un magazzino musicale

### Descrizione del problema proposto

Il problema proposto consiste nel dover gestire gli ordini del negozio, ricevuti dai clienti ed emessi verso i fornitori,e occuparsi della logistica del magazzino.

### Descrizione della rilevanza gestionale del problema

L'interesse consiste nella gestione della domanda, in modo tale da poter effettuare previsioni sulla stessa al fine di selezionare i livelli di scorte da tenere in magazzino per minimizzare i costi ad esse associati.

### Descrizione dei data-set per la valutazione	

Allego un link da dove scaricare uno screenshot riguardante il database(da scaricare come zip): https://mega.nz/#F!TFZQwYRB!X7OubngQDDSAnib4zpC80w  nella tabella strumenti la dimensione è espressa in metri cubi.

### Descrizione preliminare degli algoritmi coinvolti	

- Inserimenti record: es. nuova transazione(vendita,ordine per fornitore,richiesta di un cliente di un articolo presente in magazzino o solo nel catalogo).

- Ricerca record: es. informazioni su un articolo.

- Previsione domanda nel periodo(basandosi sullo storico vendite).

-sistemazione magazzino: implementazione di un metodo che basandosi sulla domanda e sulla disponibilità di spazio in magazzino permette di selezionare la combinazione ottimale di prodotti da ordinare e da stoccare al fine di minimizzare i costi. Variabili quali il costo di stoccaggio e il costo di ordinazione si suppongono noti(ed impostabili) da chi utilizza il programma.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

Il programma permetterà di:

 - Visualizzare e aggiornare informazioni quali storico vendite, situazione magazzino,stato degli ordini effettuati verso i fornitori e ricevuto dai clienti.

- Effettuare previsioni sulla domanda per il periodo fornito dall'utente.

- Visualizzare suggerimenti sugli ordini da effettuare e il livello di scorte da mantenere in magazzino.

**Comment by GJGits** [comment]
Aggiunta nuova Issue(centrale telefonica)

**Comment by fulcorno** [comment]
Il fatto di voler gestire il magazzino (ragionando soprattutto per "volume") è certamente possibile, ma secondo me si può fare di meglio.
In effetti, in questa proposta non si tiene conto del fatto che i prodotti non sono "black box" qualsiasi, ma sono articoli musicali. Sarebbe bello lavorare su delle problematiche algoritmiche che tengano conto delle specificità del prodotto. Forse il "suggerimenti sugli ordini" va un po' in quella direzione, ma attualmente è appena accennato.

**Comment by GJGits** [comment]
Per quanto riguarda la sistemazione in magazzino si potrebbe tener conto di un vincolo di fragilità per esempio non posso posizionare una scatola contenente un microfono sotto un oggetto molto pesante e si potrebbe anche inserire un filtro per il riempimento del magazzino fornendo all’utente la possibilità di poter scegliere per esempio se massimizzare il numero di prodotti stoccati o massimizzare il valore del magazzino mentre per “suggerimenti sugli ordini” intendo sostanzialmente un forecasting che mi aiuta a generare un MPS.

**Comment by fulcorno** [comment]
Viste le due proposte, consiglio di procedere con quella della Centrale Telefonica, visto che mi pare più solida dal punto di vista dei dati disponibili, ed anche dal punto di vista degli algoritmi coinvolti.
