### ISSUE TITLE
Gestione e ottimizzazione di un evento culinario in agriturismo

### ISSUE THREAD

**Issue by viscontidavide** [TdP-prove-finali/Introduzione#32]
### Studente proponente

s227038 Visconti Davide

### Titolo della proposta

Gestione e ottimizzazione di un evento culinario in agriturismo

### Descrizione del problema proposto

L'applicazione permetterà di scegliere un evento da svolgersi tra diversi possibili (es. esibizione di un gruppo musicale, spettacolo per bambini, cabaret,...) a cui prenderanno parte alcuni tipi di persone con diversi budget e nei quali verranno serviti dei piatti. 

### Descrizione della rilevanza gestionale del problema

A mio parere l'argomento è rilevante perchè tratta della gestione di un evento concentrandosi sulla convenienza economica e sulla soddisfazione dei clienti che ne prendono parte, due fattori importanti in un'azienda che intende organizzare avvenimenti di questo tipo.

### Descrizione dei data-set per la valutazione	

I data-set comprenderanno le tipologie di eventi caratterizzati da un numero indicativo di persone a cui ne prenderanno parte, caratterizzate a loro volta da un budget utilizzabile (sia il numero di persone che il budget di ognuna saranno variabili anche in eventi dello stesso tipo) e da un prezzo.
Infine vi saranno i piatti caratterizzati da un prezzo, da una difficoltà e da un tempo di preparazione.

### Descrizione preliminare degli algoritmi coinvolti	

L'algoritmo sarà essenzialmente un algoritmo di simulazione; deciso un evento simulerà l'arrivo delle persone che ne prenderanno parte e i loro acquisti, tenendo traccia delle spese di ognuno, dei tempi di attesa e della loro soddisfazione in base ad essi.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente dovrà selezionare una tipologia di evento, i piatti da servire e un numero di aiutanti al bancone; il programma svolgerà la simulazione tenendo traccia dei parametri sopra descritti e come risultato stamperà il guadagno totale della serata, i piatti di ogni tipo serviti e il numero di clienti insoddisfatti per la troppa attesa. Attraverso simulazioni diverse (anche dello stesso evento dato che il numero di persone sarà variabile da un avvenimento all'altro in percentuale) l'utente potrà farsi un'idea dell'evento più conveniente in termini economici e di soddisfazione da organizzarsi e della convenienza e fattibilità di ognuno.

**Comment by fulcorno** [comment]
Ok, direi che questa proposta può andare bene.
RIcordati di precisare (nella relazione finale) come è stato ricavato il data-set.
Nella parte di simulazione, si potrebbe anche pensare che il programma "automaticamente" compia più simulazioni (variando i parametri stocastici) e presenti all'utente dei "range" di possibili risultati ottenibili.
Dò per scontato che il "guadagno" citato tenga conto anche dei costi (del personale, innanzitutto, ma forse anche delle materie prime, dell'allestimento, ecc) e non solo dei ricavi.
