### ISSUE TITLE
Analisi di percorsi tra aeroporti americani

### ISSUE THREAD

**Issue by Ghassane-Ben** [TdP-prove-finali/Introduzione#33]
### Studente proponente

s236843 Ben el aattar Ghassane

### Titolo della proposta

Analisi di percorsi tra aeroporti americani 

### Descrizione del problema proposto

A partire dai dati relativi ai collegamenti aeroportuali negli USA,l'obiettivo è quello di verificare agilmente il miglior percorso tra due posizioni geografiche,oltre all'esistenza stessa di un collegamento diretto tra due aeroporti. 

### Descrizione della rilevanza gestionale del problema

Dal punto di vista gestionale,il problema assume importante rilevanza,in particolar modo per le aziende la cui parte integrante dell'attività di impresa consiste nel trasporto di merci e/o persone tra mete diverse (in questo caso negli USA). 

### Descrizione dei data-set per la valutazione	

Il data-set utilizzato è USA Airports,la cui descrizione originale è :"This dataset is a record of 3.5 Million+ US Domestic Flights from 1990 to 2009. It has been taken from OpenFlights website which have a huge database of different travelling mediums across the globe".

### Descrizione preliminare degli algoritmi coinvolti	

Dal punto di vista algoritmico,si andranno ad analizzare i vari aeroporti come vertici di un grafo orientato(non è scontata la presenza di un volo di ritorno da un aeroporto ad un altro) e pesato,i cui archi rappresentano l'esistenza di un volo tra due mete e il peso la loro distanza. Possibile l'esistenza di eventuali cicli all'interno del grafo. 
L'obiettivo del programma è verificare la connettività tra due vertici tramite DFS/BFS,ovvero la presenza di voli tra due aeroporti,oltre alla minima distanza tra due vertici (con algoritmi di ricerca di cammini minimi,es.: Dijkstra single-source shortest path). Il programma verrà implementato tramite paradigmi MVC e DAO .

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione software permetterà all'utente di selezionare due aeroporti (ad esempio,San Francisco e Portland) tramite apposite ComboBox,oltre all'informazione da ricavare (connettività e/o distanza minima) che verranno processate nel Model. Le informazioni verranno elencate in una casella di testo nella parte inferiore dell'applicazione grafica.

**Comment by fulcorno** [comment]
L'esercizio proposto è troppo semplice per poter essere accettato come tesi. Non è molto di più di esercizi già svolti durante il corso (anche se su un data-set più limitato), e di fatto consiste nel caricare un grafo e lanciare una visita sullo stesso.
Sarebbe opportuno cercare di identificare un problema applicativo più pratico e realistico, che si possa risolvere ricorrendo alle tecniche conosciute, e non semplicemente usare algoritmi predefiniti sui grafi.
Tra l'altro, il problema dei cammini minimi qui non ha senso, perché non ci sono gli orari dei voli. Esistono invece dei dati relativi al numero di voli e di passeggeri per ogni mese, dati che nella proposta attuale non vengono sfruttati.
Ti invito quindi a rielaborare una nuova proposta più completa, ed inserirla come nuovo commento a questa Issue.

**Comment by Ghassane-Ben** [comment]
Salve,la ringrazio per la risposta. Ho letto attentamente la sua analisi e rivisto il data-set e la proposta precedente.
Rielaborando la costruzione del programma,lei ritiene che,dato un arco temporale specificato (es.: 2000-2005) dall'utente e una distanza massima percorribile,un programma che elabori una serie di tratte che massimizzino il numero di passeggeri totali  (calcolando per ogni tratta il numero medio di essi nel periodo) possa essere sufficientemente valido ed interessante? Si risolverebbe un problema di ottimizzazione mediante algoritmo ricorsivo,che  dovrebbe essere una concretizzazione di un problema Knapsack 0/1 (in cui i pesi sono le distanze e i valori i totali di passeggeri). 
Il programma permetterebbe di verificare un sottoinsieme funzionale di tratte più utili relazionate ad un dato periodo temporale.
Mi piacerebbe anche includere eventualmente altre opzioni,quali la possibilità già proposta di verificare la connettività di aeroporti (come funzione ausiliaria),per rendere il programma più versatile a diverse richieste. 
La ringrazio per l'attenzione.

**Comment by fulcorno** [comment]
Il problema anche qui è abbastanza artificiale, ma comunque è accettabile come proposta di tesi.
Fai solo molta attenzione alla dimensione del database (la ricorsione potrebbe essere molto profonda...).
