### ISSUE TITLE
Applicazione per gestione itinerario e tempo in una giornata di sci 

### ISSUE THREAD

**Issue by Mattia-Delleani** [TdP-prove-finali/Introduzione#38]
### Studente proponente

s248900 Delleani Mattia

### Titolo della proposta

Applicazione per gestione itinerario e tempo in una giornata di sci

### Descrizione del problema proposto

L'applicazione mediante alcuni parametri di input, quali numero di partecipanti, il rispettivo livello di esperienza, una località di partenza e di arrivo, ora di partenza e ora di arrivo, permetterà di calcolare un itinerario sciistico il più variegato possibile al fine di massimizzare il divertimento dei partecipanti, rispettando i vincoli da essi imposti e gestendone al meglio il tempo, calcolando il cammino minimo tra due punti e quello massimo, con l'opzione di scegliere se calcolarlo con la possibilità di effettuare più volte la stessa pista o meno.

### Descrizione della rilevanza gestionale del problema

A mio parere l'argomento è rilevante perchè tratta il problema della scelta di un determinato itinerario sciistico cercando di rendere una giornata di sci il meno monotona possibile (potendo scegliere piste diverse da quelle già effettuate) e gestendone il tempo in funzione degli orari introdotti in input, in modo da evitare ritardi o eccessivi anticipi nel termine dell’attività, che in grandi comprensori sciistici è un problema molto ricorrente e che comporta situazioni poco piacevoli ad esempio la chiusura di impianti di collegamento, oppure per i maestri sci il ritardo nel termine dell’attività comporta la perdita del cliente dell'ora successiva e il troppo anticipo comporta uno scontento al cliente.

### Descrizione dei data-set per la valutazione	

Non sono riuscito a trovare data-set relativi a questo tipo di tematica, in alternativa sono disposto a realizzarli basandomi su dati reali (sia cartacei sia reperibili online). Nel caso avrei deciso di realizzarlo sul comprensorio sciistico ViaLattea (https://www.vialattea.it/Ski-Area/Ski-Map) in quanto è composto da più stazioni di sci con collegamenti tra le diverse località. Il dataset sarebbe composto da diverse tabelle, quali: 
-PISTE(IdPista, StazioneMonte, StazioneValle, Colore(indica il livello), lunghezza);
-IMPIANTO(IdImpianto, StazioneValle, StazioneMonte, località, tipologia, posti, tempoRisalita, intervalloTempo, iniziale);
-COLLEGAMENTO(idCollegamento, localita1, localita2, tipo, idTipo); [il tipo di collegamento puo’ essere una pista o un impianto e idTipo è il rispettivo identificatore];
Volendo è possibile introdurre altre informazioni (dislivelli, tempo medio in coda, ecc.).

### Descrizione preliminare degli algoritmi coinvolti	

Il problema verrà affrontato mediante la teoria dei grafi, in cui i vertici sono le stazioni, gli archi sono orientati e pesati (dove il peso corrisponde al tempo). Pensavo di utilizzare un multigrafo orientato e pesato, in quanto supponiamo una stazione (valle) è collegata ad un’altra stazione (monte) mediante un impianto per risalire (ha un determinato verso) ed impiega un determinato tempo (peso). Dalla stazione di monte le piste collegano a loro volta le stazioni (con un determinato verso) e una stazione di monte puo’ essere collegata alla stessa stazione di valle mediante piste diverse (per questo opterei per un multigrafo orientato e pesato).
Come operazioni sul grafo avrei intenzione di effettuare il cammino minimo tra due vertici (scelti in input dall’utente) per calcolare il cammino piu’ veloce in termini di tempo che collega due punti se questo fosse possibile in funzione del livello del gruppo di partecipanti (il colore delle piste puo’ essere blu, rosso, nero e rappresentano il minimo livello per percorrerle rispettivamente principiante, intermedio ed esperto). Inoltre, il peso (tempo) di un arco costituito da una pista viene calcolato come lunghezza*velocitàMedia, dove la velocità media è un parametro fisso che varia a seconda del livello dell’utente.
Oltre al cammino minimo, tramite apposito bottone, selezionando località di partenza e località di arrivo (che possono coincidere) è possibile calcolare il cammino massimo mediante un algoritmo ricorsivo che utilizzi archi diversi nel rispetto dei vincoli di orario. Se questo non fosse realizzabile, stampare messaggio di errore. 
In aggiunta al tempo di risalita proprio dell’impianto viene aggiunta una componente di tempo d’attesa legata al gruppo (ad esempio un gruppo di otto persone che si appresta a prendere una seggiovia biposto, dovrà necessariamente prendere 4 seggiovie diverse e quindi attendere l’arrivo di queste) calcolata come {IntervalloTempo * (nPersone/posti)} arrotondato logicamente per eccesso.
Nel caso riuscissi a reperire i dati relativi ai tempi di coda per la salita sull’impianto sarebbero considerati nel calcolo del tempo totale, facendo distinzione nella gestione dei tempi se la giornata scelta sia in settimana, weekend o festa.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente dovrà selezionare un numero di sciatori e il rispettivo livello (principiante, intermedio, esperto) una stazione di partenza e di arrivo che possono anche differire tra loro (come località è intesa il comune e parametro Impianto.iniziale=1, ossia raggiungibile dalla strada). Tramite apposito bottone puo’ calcolare il cammino minimo tra i due e con un altro bottone invece è possibile ricercare il cammino massimo con l’opzione di poter effettuare solo piste diverse oppure riutilizzare piste già percorse. Inoltre, mediante un menù a scelta multipla sarà possibile selezionare quali località distinte si vuole visitare tra quelle comprese nel comprensorio ed effettuare nuovamente gli algoritmi sulla base delle scelte effettuate. 
L’applicazione sarà composta anche da una interfaccia per l’utilizzo a scopo professionale e quindi alla gestione di gruppi sci di notevoli dimensioni (ad esempio le scolaresche) che permette di inserire il numero di principianti, intermedi ed esperti in tre diverse caselle di input e scegliendo sempre punto di partenza, punto di arrivo e gli orari con i quali sarà possibile calcolare i cammini massimo e minimo, e in base agli orari di arrivo sarà possibile vedere quanto tempo si ha ancora a disposizione al fine dell’attività e nel caso di troppo anticipo viene comunicata la possibilità di effettuare nuovamente alcune piste (anche già effettuate in precedenza) al fine di occupare il tempo rimanente, ovviamente se possibile.

**Comment by fulcorno** [comment]
La tipologia di applicazione è rilevante e l'algoritmo di ricerca può essere adeguato. Se però il tutto si risolvesse in un calcolo di cammini minimi, non sarebbe ammissibile (viene richiesto di risolvere un problema che utilizzi un algoritmo ricorsivo).
Ti chiederei di formulare meglio il problema per capire quale tipo di algoritmo sia necessario.

Come osservazione collaterale, mi sembra molto interessante la costruzione di questo data-set, ti chiederei di farlo "bene" (concordando anche la struttura delle tabelle), perché potrebbe essere interessante per svolgere esercizi durante il corso.

**Comment by Mattia-Delleani** [comment]
Oltre al cammino minimo, tramite apposito bottone, selezionando località di partenza e località di arrivo (che possono coincidere) è possibile calcolare il cammino che permetta di raggiungere la destinazione cercando di massimizzare un punteggio calcolato su diversi aspetti (piste diverse, difficoltà della pista, livello dello sciatore e lunghezza della pista) al fine di rendere il meno monotono e più entusiasmante possibile il percorso nel rispetto dei vincoli di tempo selezionati di input. 
Dunque, nella realizzazione si avrà una classe arco che oltre ai vertici che collega ci sara anche una tipologia (PISTA o IMPIANTO). Nel caso vi fossero più soluzioni (stesso punteggio) si andrà a selezionare come migliore, l’itinerario più lungo in termini di lunghezza piste.
Il punteggio (interpretato come soddisfazione del cliente) viene calcolato come la somma dei punteggi delle singole piste. Il punteggio di una singola pista viene calcolato rispetto alla sua difficoltà e a quella dello sciatore, ad esempio per uno sciatore esperto fare piste troppo facili porterebbe ad annoiarsi quindi si potrebbero avere i seguenti punteggi: pista NERA= 3pt, pista ROSSA = 2pt, pista BLU=1pt, mentre per uno sciatore di livello intermedio si potrebbe avere: pista ROSSA=3pt, pista BLU= 2pt; in quanto le piste ROSSE per uno sciatore di livello intermedio risultano più competitive e quindi meno noiose. (Per i principianti si ha solo la possibilità di svolgere piste BLU con valore 3pt). 
Al fine di rendere più entusiasmante e meno monotono l’itinerario, pensavo che nel calcolo del punteggio totale venga considerato come fattore negativo lo svolgimento multiplo della stessa pista (monotonia dell’itinerario), che comporta ad una diminuzione del 50% del punteggio unitario della pista per ogni discesa della stessa ( es. pista NERA per sciatore esperto: prima discesa ->3pt, seconda discesa ->1,5pt, terza discesa -> 0,75pt).
Inoltre, nel calcolo del punteggio avrei intenzione di introdurre una componente che tenga conto della lunghezza della pista mediante l’uso di un parametro K che dipende sia dalla difficoltà della pista sia dal livello dello sciatore e che ha come unità di misura [pt/km]. Ad esempio, supponiamo un valore di K=0,5[pt/km] per una pista ROSSA eseguita da uno sciatore ESPERTO, mentre per uno sciatore INTERMEDIO si avrebbe K=0,8[pt/km] per una pista rossa.
Un esempio della scala da utilizzare potrebbe essere:
SCIATORE ESPERTO: NERA->0,8[pt/km], ROSSA->0,5[pt/km], BLU->0,2[pt/km];
SCIATORE INTERMEDIO: ROSSA->0,8[pt/km], BLU->0,4[pt/km];
SCIATORE PRINCIPIANTE: 0,8[pt/km] pista blu;

Riassumendo per un dato livello dello sciatore il punteggio di una data pista viene calcolato come somma del suo valore unitario in funzione del numero di ripetizioni e della lunghezza moltiplicata per il fattore di scala K. Esempio:  pista rossa con lunghezza 750m affrontata da uno sciatore di livello ESPERTO. Alla prima discesa di tale pista si totalizzerà il seguente punteggio : pt= 3pt + 0,5*(750/1000)pt = 3,375; alla seconda discesa di tale pista si avrà pt= 1,5pt +  0,5*(750/1000)pt = 1,875pt
La stessa pista per uno sciatore di livello INTERMEDIO restituisce punteggio diversi:
pt= 3pt + 0,8*(750/1000)pt = 3,6; alla seconda discesa di tale pista si avrà pt= 1,5pt +  0,8*(750/1000)pt = 2.1 pt

**Comment by fulcorno** [comment]
ok, un po' contorto ma si vede che hai molte idee sulla creazione dell'itinerario ottimale. Per me puoi procedere, fai solo attenzione a definire chiaramente quale sia la funzione obiettivo da massimizzare, per non rischiare di avere del codice troppo contorto.
