### ISSUE TITLE
Centrale telefonica

### ISSUE THREAD

**Issue by GJGits** [TdP-prove-finali/Introduzione#4]
### Studente proponente

s204471 Marco Clemente Nanci

### Titolo della proposta

Centrale telefonica

### Descrizione del problema proposto

Il problema consiste nel dover gestire i movimenti degli operatori della centrale telefonica al fine da permettere all'azienda di massimizzare il numero di operazioni effettuate sul territorio nell'arco di un determinato periodo di tempo(1 giorno,1 settimana).

### Descrizione della rilevanza gestionale del problema

L'organizzazione delle mansioni da affidare agli operatori ricopre una notevole rilevanza gestionale , una buona strategia permette infatti di raggiungere gli obbiettivi prefissati che si traducono in ricavi per l'azienda. Nei vari ambiti dell'organizzazione interna i trasporti ricoprono certamente un ruolo fondamentale perché il tempo è una risorsa limitata, quindi la corretta gestione degli stessi permette all'azienda di ottenere ricavi utili e di guadagnarci in immagine nei confronti dei clienti.

### Descrizione dei data-set per la valutazione	

I dati verranno prelevati da una famosa azienda telefonica. Il database sarà formato da una  tabella riguardante le centrali così composta: idCentrale(chiave primaria),latidute e longitude che indicano le coordinate geografiche,numeroOperatori:indica il numero di operatori disponibili in centrale. Una riguardante le operazioni così composta: idOperazione(chiave primaria), zona:indica la zona di appartenza, la città infatti è suddivisa in classi: A-B-C dove A indica la zona metropolitana e C le zone periferiche, latitude e longitude: indicano le coordinate del luogo dove sarà fatta l'operazione(dati ricavati da https://developers.google.com/maps/documentation/geocoding/intro ), tempoMedio: indica il tempo medio che impiega l'operatore a svolgere l'operazione una volta arrivato sul posto.  

### Descrizione preliminare degli algoritmi coinvolti	

. lettura e scrittura da/su database: ottenere le operazioni, aggiungerne una nuova
. ricorsione?: calcolare il miglior percorso

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione permetterà di aggiungere un'operazione,una volta conclusa eliminarla dal database e permetterà di calcolare e visualizzare il percorso migliore per massimizzare il numero di operazioni compiute nell'arco di tempo prestabilito(inseribile dall'utente).

**Comment by fulcorno** [comment]
I miei dubbi in merito a questa proposta sono:

1. i dati (centrali, operatori, operazioni) sono "reali"? Soprattutto le operazioni, prevedi di ottenere dati reali o di costruire dati fittizi?
1. per quanto riguarda le operazioni, i dati rappresentano delle richieste (da evadere nel futuro), oppure lo storico delle operazioni effettuate? Ovviamente, anche disponendo dello storico, si può "fingere" che siano richieste, per verificare se sia possibile ottenere uno scheduling più efficiente
1. nella parte sugli algoritmi, sarebbe bene approfondire meglio che cosa si vuole ottenere (leggere/scrivere da database è scontato, non citiamolo neppure), per capire quale potrebbe essere la difficoltà di un eventuale algoritmo ricorsivo.

**Comment by GJGits** [comment]
I dati sono reali e ovviamente sono semplificati perché le operazioni fanno riferimento a diversi interventi sul territorio(installazioni,riparazioni guasti…) e il tempo medio è ovviamente un tempo stimato, ma realistico e a tal proposito si potrebbe aggiungere una variabilità. La lista delle centrali non è completa perché non mi sarebbe concesso fornire l’intera mappatura del territorio quindi lavorerei ipotizzando che esistano solo una parte di esse. Anche il numero di operatori è reale anche se nell’applicazione si ipotizzerà che tutti siano in grado di portare a termine tutte le tipologie di operazioni da compiere sul territorio. I dati fanno riferimento all’anno 2016/2017 e ovviamente verranno omessi dati riguardanti operazioni ancora da portare a termine, però come da lei proposto si potrebbe ipotizzare che alcune di esse siano ancora da completare. Per quanto riguarda la parte algoritmica l’obbiettivo sarebbe quello di calcolare il percorso che gli operatori devono compiere per massimizzare le operazioni portate a termine nell’arco di tempo stabilito per esempio una giornata o una settimana e a tal proposito si potrebbe creare un grafo pesato che collega le operazioni, ipotizzando che le operazioni vengano smistate verso la centrale più vicina, e dove il peso dell’arco corrisponde al tempo necessario per arrivare sul posto e  portare a termine l’operazione. Si potrebbe infine simulare disposizioni diverse degli operatori tra le centrali per valutare strategie migliori.

**Comment by fulcorno** [comment]
Ok, con i chiarimenti formiti per me il progetto va bene, puoi procedere.
