### ISSUE TITLE
LATE (Lightweight Airport Testing Environment)

### ISSUE THREAD

**Issue by augustocolo** [TdP-prove-finali/Introduzione#40]
### Studente proponente  
s246235 Colongo Augusto

### Titolo della proposta  
LATE (Lightweight Airport Testing Environment)

### Descrizione del problema proposto  
L'applicazione intende fornire uno strumento per il calcolo del traffico massimo che un aeroporto può gestire attraverso un approccio simulativo in cui verranno effettuati degli stress test.

L'obiettivo della simulazione è quello di fornire all'utente dei KPI _(Key Performance Indicator)_ atti ad analizzare la risposta dell'infrastruttura aeroportuale a valori diversi di input di traffico. 

### Descrizione della rilevanza gestionale del problema  
Il calcolo della capacità di un'infrastruttura è di notevole rilevanza progettuale e gestionale.

Nel primo caso i benefici sono lampanti: in fase di progettazione si devono garantire dei minimi livelli di servizio in termini di efficienza dell'infrastruttura.

In fase di gestione, questo strumento potrebbe aiutare la valutazione dell'impatto di manutenzioni e imprevisti.
Un esempio pratico potrebbe essere la chiusura di una parte di un terminal per ristrutturazione: in tal caso si potrebbero escludere dal modello i gate coinvolti, lanciare la simulazione e valutare l'impatto dell'evento sull'efficienza aeroportuale.

### Descrizione dei data-set per la valutazione   
I dati che utilizzerà l'applicazione sono:

* **Dati sull'infrastruttura aeroportuale**:
I dati verranno importati dai modelli aeroportuali creati dalla comunità del simulatore XPlane che si possono trovare e scaricare gratuitamente dal sito https://gateway.x-plane.com/.
Tutti gli scenari presenti sul sito sono gratis e pubblicati sotto la licenza GPLv2. L'importazione di questi scenari fornirà la mappa delle piste, delle taxiways, dei gate e delle principali procedure per l'arrivo e la partenza degli aeromobili.
Inoltre, XPlane ha rilasciato un software per la creazione di questi scenari che permetterà all'utente di crearne di immaginari o di apportare delle modifiche a quelli esistenti.

* **Dati sugli aerei:**
I dati sugli aerei verranno presi da un catalogo dell'FAA _(Federal Aviation Administration)_ che si può trovare al seguente link: https://www.faa.gov/airports/engineering/aircraft\_char\_database/.
I dati che ci interessano sono principalmente le dimensioni degli aeromobili e le loro velocità di atterraggio.

Il traffico non sarà basato sul traffico aeroportuale reale, in quanto lo scopo dell'applicazione non è di simulare una situazione preesistente, ma di sottoporre l'infrastruttura a carichi variabili in modo da calcolarne la capacità massima.

### Descrizione preliminare degli algoritmi coinvolti   
I principali algoritmi coinvolti saranno:

* Un algoritmo simulativo a eventi discreti che costituirà la parte principale dell'applicazione: simulerà l'interazione degli aeroplani con il modello aeroportuale.

* Un algoritmo di pathfinding per fornire agli aerei un percorso da seguire per arrivare al gate e ritornare alla pista una volta effettuate le operazioni di sbarco e di imbarco.

### Descrizione preliminare delle funzionalità previste per l’applicazione software   
L'applicazione sarà strutturata nel seguente modo:

* Nella prima pagina l'utente sarà in grado di:

  * Definire un percorso file per l'importazione del modello aeroportuale.
Dopo la corretta importazione del file, all'utente verranno presentati dei dati sull'aeroporto. 
  
  * Settare la proporzione in cui verranno scelti i vari modelli di aerei per la simulazione.
  
  * Impostare altre variabili della simulazione (ad esempio il tempo di interarrivo medio iniziale, l'incremento ad ogni step simulativo, il tempo massimo della finestra di simulazione, etc...)

* Successivamente alla simulazione, una schermata proporrà i vari KPI e grafici che aiuteranno l'utente all'analisi dello stress test. Alcuni indici che, per ora, voglio implementare sono:
  * Tempo di attesa medio per aereo
  * Gate più utilizzati
  * Tempo di utilizzo dei vari servizi aeroportuali

Tuttavia, mi riservo di eventualmente sostituire gli indici elencati sopra nel caso in cui io voglia aggiungerne di nuovi.

**Comment by fulcorno** [comment]
Devi essere appassionato di aerei ed aeroporti per avere queste conoscenze approfondite...
Probabilmente nella relazione finale dovrai spiegare bene il problema che stai risolvento (stress test), perché richiede la comprensione dei dettagli di funzionamento degli aeroporti e delle loro componenti.
La proposta mi pare adeguata come contenuti e come algoritmi proposti. Puoi procedere.
