### ISSUE TITLE
Tool per organizzatore di festival di musica dal vivo

### ISSUE THREAD

**Issue by matteo-rizzi** [TdP-prove-finali/Introduzione#41]
### Studente proponente

s244853 Rizzi Matteo

### Titolo della proposta

Tool per organizzatore di festival di musica dal vivo

### Descrizione del problema proposto

L’applicazione si propone l’obiettivo di aiutare un organizzatore di festival di musica dal vivo nella ricerca di artisti da ingaggiare per il proprio festival. L’utente potrà cercare da sé gli eventuali artisti, oppure potrà lasciare il compito all’applicazione, che dovrà trovare l’insieme ottimale di artisti in base al budget dell’organizzatore.

### Descrizione della rilevanza gestionale del problema

Una buona parte di concerti di musica dal vivo è composta dai festival musicali, in cui più cantanti/band hanno la possibilità di suonare nell’arco della stessa giornata e ciò fa sorgere il problema della scelta di quali artisti ingaggiare. L’applicazione quindi intende aiutare nella ricerca di tali artisti e nell’ottimizzazione della gestione del budget a disposizione dell’organizzatore, in modo da massimizzare il numero di presenze al festival.

### Descrizione dei data-set per la valutazione	

I dati sono racchiusi in un’unica tabella, di seguito allegata in formato .xlsx. La tabella in questione, ad oggi solo parzialmente completa, presenta innanzitutto i dati riguardanti i cantanti e le band in attività, dati relativi ad uno degli ultimi tour dell’artista in questione (racchiusi nei campi- biglietti_venduti, numero_di_show, numero_medio_biglietti_venduti), i quali sono estrapolati dai siti https://en.wikipedia.org/ e https://touringdata.wordpress.com/. Inoltre è presente un campo riguardante il cachet medio percepito, le cui fonti sono http://www.eventresourcespresents.com/ e https://www.celebritytalent.net/ e un campo contenente il genere musicale di appartenenza e il nome della band o del cantante in questione. Vi è, infine, un campo riguardante il numero di ascolti medi sulla piattaforma streaming on demand Spotify nell’ultimo mese (campo che, al momento, è ancora vuoto e che verrà aggiornato successivamente).

[artisti.xlsx](https://github.com/TdP-prove-finali/Introduzione/files/4776816/artisti.xlsx)

### Descrizione preliminare degli algoritmi coinvolti	

Il programma presenta due funzioni principali, la prima implementata tramite un algoritmo di ricerca, la seconda mediante un algoritmo di ricorsione:
1.	Per quanto riguarda la parte di ricerca, dove sarà fondamentale l’utilizzo del Pattern DAO, sarà possibile filtrare i vari artisti in diversi modi (si potranno visualizzare tutti gli artisti, un artista in particolare, oppure tutti gli artisti facenti parte di un dato genere musicale, o che abbiano venduto almeno un certo numero medio di biglietti, ecc.). Poiché  l’utente di riferimento dell’applicazione è l’organizzatore di un festival, che potrebbe essere verosimilmente a conoscenza di dati relativi ad ulteriori artisti o di eventuali dati aggiornati di artisti già inseriti, potrà inserire, modificare, eliminare i dati degli stessi. 
Da questa interfaccia, infine, l’utente potrà selezionare uno o più artisti e aggiungerli direttamente nella soluzione ottima che verrà trovata tramite l’algoritmo ricorsivo descritto nel punto successivo (questo perché magari l’organizzatore ha già avuto la disponibilità degli artisti selezionati, che quindi faranno sicuramente parte del festival).
2.	L’algoritmo ricorsivo, impostato un budget massimo e tenuto conto degli artisti già aggiunti(se la somma del cachet percepito da quelli già inseriti dovesse superare l’importo del budget verrà notificato l’errore e l’utente dovrà modificare la lista degli artisti inseriti oppure il budget), troverà l’insieme di artisti che rientra nel budget inserito e che garantirebbe il maggior pubblico possibile al festival. A scelta dell’utente, la massimizzazione del pubblico può essere fatta sulla base della media dei biglietti venduti dell’artista, oppure sulla base degli streaming totalizzati dallo stesso su Spotify nell’ultimo mese. Sarà inoltre possibile specificare altri vincoli, tra cui il numero di artisti da ingaggiare, e selezionare quali generi musicali considerare. Rispetto a quest’ultimo vincolo sarà inoltre possibile identificare dei generi, tra quelli selezionati, “privilegiati”: gli artisti che rientrano in tale genere musicale, al momento dell’avvio della ricorsione, avranno un peso maggiore in termini di biglietti venduti/streaming. Il peso da dare ai generi “privilegiati” può essere impostato attraverso uno slider (con valori che vanno da 1, ovvero nessun privilegio, a 2, ovvero con peso doppio rispetto agli altri).

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione avrà tre interfacce grafiche principali. La prima interfaccia sarà quella in cui l’utente, tramite appositi nodi, potrà consultare il database secondo i tipi di filtraggio proposti (per genere musicale, per numero medio di biglietti venduti, ecc.). Da qui si potranno inoltre aggiungere gli artisti che faranno parte della soluzione dell’algoritmo ricorsivo. Una volta premuto il bottone di aggiunta, si aprirà automaticamente l’interfaccia relativa alla ricorsione (che può essere raggiunta anche dal menu iniziale bypassando lo step precedente). In questa seconda interfaccia l’utente potrà gestire tutti i vincoli della parte ricorsiva e, una volta eseguito l’algoritmo ricorsivo, potrà visualizzare l’insieme ottimale di artisti e il budget rimanente. La terza interfaccia, infine, sarà quella relativa alla modifica dei dati del database, in cui l’utente potrà inserire, modificare, eliminare i dati.

**Comment by fulcorno** [comment]
Il problema è rilevante e gli algoritmi proposti sono adeguati. In particolare, la parte ricorsiva mi pare una versione con qualche vincolo custom del classico (e ben noto) problema dello zaino.
Secondo me la "terza interfaccia" (gestione dell'anagrafica cantanti) è molto lunga da implementare, e non aggiunge nulla al valore della tesi, direi quindi di considerare ai fini della tesi solo le prime due interfacce. Con questa precisazione, puoi procedere.
