### ISSUE TITLE
Applicazione per la gestione di un servizio di bike sharing

### ISSUE THREAD

**Issue by umferrari** [TdP-prove-finali/Introduzione#42]
### Studente proponente

s246061 Ferrari Umberto

### Titolo della proposta

Applicazione per la gestione di un servizio di bike sharing

### Descrizione del problema proposto

La mobilità urbana è un argomento sempre di maggior interesse, da un lato per motivi ecologici e dall'altro, attualmente, a causa dei rischi della pandemia da Covid-19. Infatti, si sta incentivando l'uso di mezzi di trasporto quali il bike sharing in sostituzione al normale trasporto pubblico, perciò si suppone che nei prossimi mesi si assisterà ad un aumento nel numero di utenti di questo tipo di servizi. Dall'altro lato però si renderà necessaria una maggiore attività da parte del gestore dal punto di vista della sanificazione delle superfici di biciclette e colonnine.

L'obiettivo è quello di presentare all'utente una visione d'insieme sull'utilizzo del servizio in caso di aumento dell'utenza e di fornire uno strumento adeguato a pianificare l'attività di sanificazione del sistema.

### Descrizione della rilevanza gestionale del problema

L'applicazione intende fornire uno strumento per la gestione di un servizio di bike sharing.

Questo strumento può essere utile al gestore del servizio per metterne in luce i punti critici, per la gestione del sistema e per pianificare eventuali miglioramenti che potrebbero rivelarsi necessari a causa del probabile aumento di noleggi.

Inoltre, l'applicazione permetterà di pianificare la sanificazione del sistema, ritenuta fondamentale per un utilizzo sicuro del servizio, in modo da permettere al gestore di organizzare al meglio questa attività e simularne i risultati, così da comprenderne l'utilità e la fattibilità dal punto di vista economico.

### Descrizione dei data-set per la valutazione	

I dati che utilizzerà l'applicazione sono relativi al servizio di bike sharing della città di Londra (*Santander Cycles*):

- **Dati relativi alle stazioni di noleggio (*bike points*):**
  I dati verranno ricavati tramite l'API fornita da TfL (*Transport for London*) dal sito https://api.tfl.gov.uk/ e verranno importati dal formato `JSON` ad una database `SQL` tramite una funzione apposita (l'API non verrà integrate nell'applicazione ma utilizzata una sola volta per creare il dataset).

- **Dati sui noleggi:**
  I dati sui noleggi verranno estratti dal sito di TfL (*Transport for London*) al seguente link https://cycling.data.tfl.gov.uk/ dove sono disponibili divisi per periodo di interesse. 
  Essendo i dati di grandi dimensioni non saranno scaricati tutti ma verrà inserito un solo periodo di noleggi nel database. 
  L'applicazione permetterà all'utente di definire un percorso per l'importazione di uno o più file di dati scaricati dal sito sopraindicato i quali potranno essere sovrascritti o aggiunti ai dati già presenti. Anche in questo caso i dati verranno importati dal formato `CSV` in un database `SQL` tramite una funzione apposita. 

Tutti i dati sono rilasciati con licenza `Open Government Licence 2.0` (https://tfl.gov.uk/corporate/terms-and-conditions/transport-data-service) che permette un libero uso dei dati, richiedendo di riconoscere TfL come fonte delle informazioni.

### Descrizione preliminare degli algoritmi coinvolti	

I principali algoritmi coinvolti saranno:

- Un algoritmo simulativo a eventi discreti. Potrà essere eseguito secondo diversi parametri inseriti dall'utente:
  - Intervallo temporale da simulare, indicato come date future (di conseguenza saranno utilizzati i dati sui noleggi dello stesso periodo dell'anno precedente se presenti o i dati scelti dall'utente).
  - Aumento percentuale dell'utenza che usufruisce del servizio.
  - Restringere la simulazione solo a giorni festivi oppure lavorativi.
- Un algoritmo che generi, sulla base dei dati "storici" inseriti e dei valori in input, i noleggi del periodo da simulare, in modo che quest'ultimi non siano deterministici ma realistici rispetto ai dati inseriti.
  Per esempio: l'aumento del traffico giornaliero inserito porterà all'inserimento di nuovi noleggi nelle ore di punta, oppure nel caso in cui siano state inserite nuove stazioni di cui non sono disponibili noleggi, l'algoritmo si occuperà di generarli tenendo conto del traffico nelle stazioni vicine.
- Un algoritmo ricorsivo che identifichi il percorso per ogni addetto alla sanificazione in modo da coprire l'intera rete di stazioni nel minor tempo possibile e da massimizzare il numero di biciclette sanificate. Sarà richiesto l'inserimento del numero di addetti all'attività e l'orario di lavoro.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione prevede le seguenti funzionalità:

- Nella prima schermata verrà mostrato un riassunto dei dati attualmente caricati nel database, in particolare il periodo dei noleggi attualmente memorizzati. 
  Inoltre l'utente sarà in grado di aggiornare i due dataset, inserendo manualmente una nuova stazione o selezionando il percorso del file da cui importare i nuovi dati sui noleggi.
- Nella seconda schermata sarà possibile effettuare la simulazione, eventualmente inserendo i parametri richiesti. 
  Al termine della simulazione verrà mostrata una mappa di Londra con segnate le diverse stazioni codificate secondo una scala di colore rispetto ai problemi verificatisi. I quali possono essere:
  - Stazioni vuote, quindi utenti che non sono riusciti a noleggiare una bicicletta.
  - Stazioni piene in cui gli utenti non sono riusciti a consegnare la bicicletta e che si sono dovuti recare in un'altra stazione per terminare il noleggio.
  - Stazioni ad alto traffico, per cui sarebbe utile un miglioramento.
- Nella terza schermata sarà possibile pianificare la sanificazione in un dato giorno tra quelli simulati, verranno forniti come risultati:
  - Il percorso di ogni addetto.
  - Il numero di biciclette sanificate e nel caso in cui non sia possibile eseguire il lavoro su tutta la rete, le stazioni in cui gli addetti si sono recati.

Il numero di biciclette sanificate (intese come idBike univoci) verrà calcolato sulla base dei dati ottenuti dalla simulazione, in particolare quali biciclette si trovano depositate in una certa stazione nell'orario in cui l'addetto si reca a sanificarla.

**Comment by fulcorno** [comment]
Il dominio applicativo, i data-set proposti e gli algoritmi sono adeguati, puoi procedere con il lavoro.
Potrai valutare, durante il lavoro, se concentrarti sulla parte di simulazione (sviluppando la possibilità di gestire scenari diversi), ed in questo caso la parte sulla ricorsione potrebbe anche essere omessa.
