### ISSUE TITLE
Tragitto casa-lavoro, emissioni di CO2 e Smart Working

### ISSUE THREAD

**Issue by luciomas17** [TdP-prove-finali/Introduzione#43]
### Studente proponente

s231464 Panebianco Omar

### Titolo della proposta

Tragitto casa-lavoro, emissioni di CO2 e Smart Working

### Descrizione del problema proposto

Determinare il tragitto casa-lavoro più breve per i dipendenti di qualsiasi azienda di Torino.
Raccogliere dati sul numero di giorni in Smart Working di ogni dipendente e sulle caratteristiche dell'autoveicolo utilizzato dal dipendente stesso per percorre il tragitto casa-lavoro.
Confrontare le aziende inserite a sistema sulla base dei dati raccolti.

### Descrizione della rilevanza gestionale del problema

Si ottimizza il tragitto casa-lavoro per ciascun lavoratore in modo da ridurre al minimo le emissioni di CO2. 
Si ottiene una stima delle emissioni di CO2 risparmiate da ogni dipendente durante l'anno grazie al lavoro in Smart Working.
Si individua, tra quelle inserite a sistema, l'azienda di Torino i cui dipendenti hanno il minor impatto ambientale sul tragitto casa-lavoro.

### Descrizione dei data-set per la valutazione	

Numerazione civica - Portale OpenData del Comune di Torino (aperto.comune.torino.it): contiene le informazioni toponomastiche relative ai civici della Città di Torino, georiferiti secondo il sistema di coordinate WGS84. Serve ad agevolare l'introduzione da parte dell'utente degli indirizzi richiesti dal form di input dell'applicazione.
Datasets for All Model Years (1984–2021) - Portale FuelEconomy del US Department of Energy (www.fueleconomy.gov): contiene le specifiche tecniche di oltre 40000 veicoli. Serve ad ottenere le informazioni sul veicolo utilizzato dall'utente per il tragitto-casa lavoro ed in particolare la quantità di emissioni di CO2 in grammi per chilometro.

### Descrizione preliminare degli algoritmi coinvolti	

Inserimento dati sull'azienda e sul dipendente dell'azienda. Inserimento dati sul veicolo utilizzato dal dipendente dell'azienda.
Ricerca del tragitto casa-lavoro più breve tramite API di Google.
Calcolo della quantità di emissioni di CO2 prodotta dal veicolo del dipendente durante il tragitto casa-lavoro su base giornaliera e su base annua.
Calcolo della quantità di emissioni di CO2 risparmiata dal dipendente grazie al lavoro in Smart Working su base annua.
Ricerca ponderata dell'azienda i cui dipendenti producono la più grande quantità di emissioni di CO2 su base annua.
Ricerca ponderata dell'azienda i cui dipendenti risparmiano la più grande quantità di emissioni di CO2 su base annua grazie al lavoro in Smart Working.
Rappresentazione grafica delle ricerche descritte.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione sarà suddivisa in tre tab. 
Il primo tab conterrà il form per l'inserimento dei dati richiesti: nome dell'azienda, indirizzo dell'azienda (se non presente già a sistema), codice fiscale dell'utente, indirizzo dell'utente, veicolo dell'utente, numero di giorni lavorativi all'anno dell'utente, numero di giorni lavorativi in Smart Working all'anno dell'utente. Una volta inviati i dati, l'applicazione genererà un password casuale per accedere alla visualizzazione dei propri dati personali nel secondo tab.
Il secondo tab conterrà, dopo l'inserimento del proprio codice fiscale e la propria password, una view di Google Maps con il tragitto casa-lavoro più breve ed i relativi dati sulla distanza totale, sulla quantità di emissioni di CO2 prodotte e sulla quantità di emissioni di CO2 risparmiate grazie al lavoro in Smart Working.
Il terzo tab conterrà l'output delle analisi dei dati inseriti da tutti gli utenti che hanno utilizzato l'applicazione trattati in modo anonimo. In particolare si individueranno tre sezioni differenti: la prima mostrerà un grafico di comparazione tra le aziende inserite; la seconda mostrerà una classifica delle aziende i cui dipendenti hanno mediamente il peggior impatto ambientale durante il tragitto casa-lavoro; la terza mostrerà una classifica delle aziende i cui dipendenti hanno mediamente risparmiato la più grande quantità di emissioni di CO2 grazie al lavoro in Smart Working.

**Comment by fulcorno** [comment]
non sono presenti algoritmi di ricorsione o simulazione.
