### ISSUE TITLE
Sistema di time tracking inclusivo di overtime, holidays e flying desks management 

### ISSUE THREAD

**Issue by marcopulita** [TdP-prove-finali/Introduzione#45]
### Studente proponente

s242664 Marco Pulita

### Titolo della proposta

Sistema di time tracking inclusivo di overtime, holidays e flying desks management 

### Descrizione del problema proposto

L'applicativo proposto e' adatto alla tipica societa' di consulenza con i collaboratori che lavorano presso il cliente.
Avrebbe lo scopo di tracciare il tempo speso dai dipendenti su singoli progetti nonche'
tracciare a livello HR il numero di ore giornaliere lavorate per progetto, gestire le ferie e dare la possibilita' ai collaboratori,
qualora avessero necessita' di lavorare nella sede principale, di prenotare l'uso di flying desks.

### Descrizione della rilevanza gestionale del problema

- gestione dell'allocazione dei membri di un team su piu'progetti
- gestione ferie (sia come permessi che come public holiday)
- gestione di dipendenti partime con relativo ammontare diverso di ore allocabili e ferie disponibili
- reportistica per la fatturazione al cliente delle ore sul singolo progetto
- reportistica per il saldo delle ore lavorate del singolo collaboratore 

### Descrizione dei data-set per la valutazione	

Il dataset non è esistente ma può essere generato in maniera molto veloce e con nominativi fittizi.

### Descrizione preliminare degli algoritmi coinvolti	

- Algoritmi di ricerca per interrogare l'applicativo
- *Possibili* Algoritmi di ottimizzazione dell'allocazione di risorse scarse per l'allocazione dei 
  collaboratori sui progetti e per l'allocazione delle flying desks 
- Algoritmi per la generazione di report

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

First start: Alla prima esecuzione dovranno essere inserirti i dati relativi all'azienza, inserire una serie di parametri
di configurazione dell'applicativo come l'uso delle flying desks, il numero massimo di ore lavorabili giorno, max numero di ore overtime, eseguire un import 
da file dei collaboratori ...

L'applicativo deve prevedere la possibilita' di inserire le seguenti entita'
- progetto
- collaboratore
- holiday request (che deve essere approvata dal manager)
- flying desk booking
- overtime request
- daily time track
- allocazione del collaboratore al progetto, per ore o per finestra temporale (es dal 10 giugno - al 20 giugno)

Ad inizio anno sara' necessario inserire il nuovo monte ore holidays (che dovra' essere addizionato al monte ore dell'anno precedente)
e le public holiday riconosciute dall'azienda.

Dovra' essere prevista la possibilita' di estrapolare i dati relativi alle ore totali del collaboratore e il suo report ferie.
in contrapposizione con le ore sui singoli progetti.
I dati relativi alle ore totali ed overtime sono necessari per una questione di fatturazione interna (stipendio del dipendente),
quelli relativi alle ore sui singoli progetti per la fatturazione al cliente. A tal scopo il report interno dovra' avere focus sul collaboratore
generando quindi la lista collaboratori e ore lavorate, overtime e ferie. Il report esterno generera' il monte ore allocato sul singolo progetto 
e il numero di collaboratori assegnati.

**Comment by fulcorno** [comment]
La rilevanza gestionale della proposta è evidente, ma purtroppo non rispetta i requisiti algoritmici per il corso. È necessario proporre un'applicazione che faccia uso di ricorsione (per ricercare/ottimizzare qualcosa) o di simulazioni ad eventi discreti.
Inoltre questa applicazione consiste nel 90%+ di funzionalità di "anagrafica" (inserimento e modifica dati) e di reportistica, che portano via molto tempo e non contribuiscono nulla dal punto di vista algoritmico.
Pertanto in questa forma la proposta non è accettabile.
