### ISSUE TITLE
Sviluppo di un software per la generazione automatica di una playlist musicale

### ISSUE THREAD

**Issue by walterdec** [TdP-prove-finali/Introduzione#47]
### Studente proponente
s227538 De Carne Walter

### Titolo della proposta
Sviluppo di un software per la generazione automatica di una playlist musicale

### Descrizione del problema proposto
Il problema nasce dall’assenza di una funzione automatica per la creazione di una playlist personalizzata all’interno dell’applicazione Spotify. L’applicazione proposta consentirebbe l’automazione della generazione di playlist ottimizzata sulla base delle preferenze dell’utente.

### Descrizione della rilevanza gestionale del problema
Il software risulterebbe di interesse per l’azienda stessa, in quanto andrebbe ad aggiungere un nuovo servizio alla propria offerta, oppure ad un’azienda terza, che potrebbe fornire lo stesso servizio avendo accesso all’account Spotify dell’utente.
Il software sarebbe comunque flessibile all’utilizzo su un qualsiasi altro servizio di musica in streaming, ampliando il target verso più aziende, previo adattamento del nuovo dataset al format e agli indici utilizzati.

### Descrizione dei data-set per la valutazione
L’applicazione si basa sul dataset contenente la Top 50 annuale di ogni anno dal 2010 al 2019, stilata da Billboard che classifica le canzoni più ascoltate negli Stati Uniti. Ogni brano è rappresentato da un record che contiene, oltre a un numero progressivo da 1 a 603, il titolo, l’artista, il genere e l’anno in cui il brano si è classificato nella Top 50. Inoltre, vi sono una serie di parametri:
- bpm, beats per minute;
- nrgy (energy), indica quanto una canzone è energica;
- dnce (danceability), indica quanto è danzabile;
- dB, indica i decibel;
- live, più è alto il valore maggiore è la probabilità che sia live;
- val (valence), indica quanto mette di buon umore;
- dur (duration), indica la durata;
- acous (acousticness), indica quanto è acustica;
- spch (speechiness), più è basso più è strumentale;
- pop (popularity), indica la popolarità.
Il dataset è stato estratto da qui: https://www.kaggle.com/leonardopena/top-spotify-songs-from-20102019-by-year

### Descrizione preliminare degli algoritmi coinvolti
La prima parte sarà costituita da algoritmi di ricerca per la visualizzazione di record e l'elaborazione dei dati estratti.
Per la seconda parte, si utilizzerà un algoritmo ricorsivo che creerà la playlist ottimale. Affinché la canzone sia aggiunta alla playlist, sarà vincolante essere al di sotto della soglia di tolleranza, selezionabile dall’utente. In questo modo le canzoni che si discostano troppo dalle preferenze saranno scartate, in modo tale da garantire maggiore affidabilità.

### Descrizione preliminare delle funzionalità previste per l’applicazione software
Quest’applicativo, nel primo tab, permetterà la ricerca di brani per artista (ricercabile tramite textfield, mostrerà tutte le canzoni di quell’artista con le varie informazioni; se non sarà presente restituirà un messaggio di errore) e per genere (selezionandolo dal choice box), mostrando delle statistiche a riguardo (durata media, artista più frequente per quel genere, popolarità media, danceability media, ecc.)

Nel secondo tab, sulla base delle preferenze (ad esempio valence, popolarità, ecc.) selezionabili dall’utente tramite slider, sarà possibile creare una playlist di canzoni. L’utente dovrà inoltre scegliere il numero massimo di canzoni che saranno contenute nella playlist ed una “soglia di tolleranza” tra 3 valori (bassa, media e alta).
La playlist sarà generabile comprendendo tutte le canzoni o, in alternativa, all’utente sarà data possibilità di spuntare i suoi generi preferiti e/o gli anni, andando così a restringere le preferenze. Saranno mostrati grafici che analizzano le caratteristiche della playlist generata.

**Comment by fulcorno** [comment]
Il problema è interessante ed il data-set è valido.
Ho un dubbio sull'algoritmo proposto. Mi pare che il problema si possa risolvere definendo semplicemente una "funzione di gradimento" (che mappa per ogni canzone un valore numerico che rappresenta la preferenza dell'utente sulla base delle informazioni che ha dato in input), e poi ordinando semplicemente le canzoni usando quel valore.
Non riesco a capire dove intervenga la necessità di un algoritmo di ottimizzazione ricorsivo.
Se riusciamo a chiarire questo punto, la proposta può essere accettata.

**Comment by walterdec** [comment]
Modifico l'algoritmo ricorsivo come segue: l'utente sceglierà la durata della playlist (ad esempio, se volesse creare una playlist da ascoltare nel tragitto casa-lavoro o una per l'allenamento, eventi che hanno appunto una durata quasi sempre fissa), in questo modo l'algoritmo genererà la migliore combinazione di canzoni per quella durata complessiva, rispettando i vincoli già precedentemente esposti ed eventualmente altri vincoli che verranno aggiunti in fase di sviluppo. Si tratterebbe quindi di un problema dello zaino.

**Comment by fulcorno** [comment]
ok, va bene. Cercherei di intendere il vincolo di tempo in modo "flessibile" (a differenza dello zaino, una "tolleranza" di qualche secondo può essere accettata).
