### ISSUE TITLE
Analisi/comparazione modelli di previsione

### ISSUE THREAD

**Issue by salva78Github** [TdP-prove-finali/Introduzione#48]
### Studente proponente

s232047 Salvatore Dipace

### Titolo della proposta

Analisi/comparazione modelli di previsione

### Descrizione del problema proposto

In più corsi si è affrontato il tema della previsione del comportamento di una grandezza negli istanti t+1, t+2, ... t+N
a partire da un set di dati storici. In letteratura si trovano molti algoritmi: alcuni semplici, altri più complessi che 
possono anche sfruttare le capacità di apprendimento delle reti neurali.
Un confronto tra più algoritimi di stima sullo stesso dataset potrebbe permettere di capire quale di questi è più adatto a modellare il comportamento del sistema osservato secondo le metriche scelte (precisione, velocità, ecc...).

### Descrizione della rilevanza gestionale del problema

Nel corso di Programmazione e Gestione della Produzione si sono studiati alcuni semplici algoritmi di previsione 
per le stime della domanda indipendente di prodotti a partire da dati storici a disposizione. Per poter pianificare
sul breve/medio periodo è indispensabile affidarsi a stime il più possibile precise.
L'applicazione di questi algoritmi è però molto ampia. Si possono per esempio utilizzare con modelli matematici che 
simulano il comportamento del traffico autorstradale per prevenire le congestioni di traffico oppure per
analizzare gli effetti dei parametri parassiti sui segnali che attraversano i cavi elettrici di potenza.

### Descrizione dei data-set per la valutazione	

Si vorrebbero trattare più dataset per la comparazione degli algoritmi. 
Per esempio i dati del contagio del covid-19. A partire dai dati di Marzo, Aprile, Maggio e Giugno,
stimare i dati dei primi giorni di Luglio e verificare poi quanto siano affidabili.
Alcuni dataset a riguardo si trovano qui https://github.com/mcicolella/covid19-opendata
Si potrebbero considerare per esempio dataset relativi alla domanda di produzione di 
alcuni prodotto in commercio o i consumi di energia 
(https://openei.org/datasets/dataset/electric-power-monthly-monthly-data-tables/resource/038d75a3-42e6-4ff8-8b05-4492a0414eb4)
L'interfaccia utente permetterà di scegliere il dataset da considerare per l'analisi.
Si potrebbe studiare la base dati per ospitare categorie diverse di osservazioni storiche sulle stesse tabelle.
Ogni categoria sarà identificata da un codice univoco. 

### Descrizione preliminare degli algoritmi coinvolti	

Gli algoritmi di stima considerati saranno principalmente quelli studiati nel corso di 
Programmazione e Gestione della Produzione. Quindi la media mobile, l'exponential smoothing con e senza trend e
il metodo di Winter. Altri se ne trovano in letteratura.
Si tratta di algoritmi che dipendono dalla stima calcolata al tempo t-1: quindi le implementazioni in java
dovranno seguire gli schemi degli algoritmi ricorsivi.
Gli algoritmi scelti per l'analisi comparativa su un dataset costituiranno i nodi di un grafo pesato i cui pesi
dipenderanno dai risultati ottenuti in termini di precisione o velocità di esecuzione.
L'utente potrà poi visualizzare la classifica dell'algoritmo più preciso o più veloce costruito con algoritmi di 
ricerca su grafo studiati nel corso di Tecniche di Programmazione.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente potrà scegliere il dataset da analizzare e la profondità dei campioni storici e di quelli futuri stimati.
Potrà selezionare gli algoritmi oggetto dell'analisi e lanciare poi la simulazione. 
Terminata, potrà scegliere il criterio di confronto (precisione e stima) e poi chiedere una classifica
partendo dal più performante o dal meno efficiente. 
Alcuni parametri potrebbero richiedere l'inserimento runtime di alcuni coefficienti.
Si potrebbero prevedere anche funzionalità per l'aggiornamento dei dataset.

**Comment by fulcorno** [comment]
Caro Salvatore, innanzitutto mi scuso per il ritardo nella risposta.
La proposta che hai descritto è eccessivamente generica, in quanto vuole applicare "molti" algoritmi diversi (ciascuno con la sua specificità) a "molti dataset" (ciascuno con le sue particolarità).
La parte di costruzione del grafo tra i risultati degli algoritmi mi risulta molto poco chiara... fatico a dare un senso agli archi del grafo stesso. L'affermazione che un modello predittivo calcola i dati a tempo t sulla base di t-1 va bene, ma ciò non implica affatto che l'algoritmo debba essere ricorsivo.

Ti suggerirei di preparare una nuova proposta molto più concreta, che affronti UN problema specifico con UN data-set adeguatamente selezionato.
