### ISSUE TITLE
Capacity Management per gli aeroporti dello stato di New York

### ISSUE THREAD

**Issue by 203574** [TdP-prove-finali/Introduzione#5]
### Studente proponente

s203574 Varaldo Arianna

### Titolo della proposta

"Capacity Management per gli aeroporti dello stato di New York"

### Descrizione del problema proposto

Si vuole creare un’applicazione che sia in grado di determinare il numero di persone che circolano in una certa fascia oraria di un determinato giorno della settimana all'interno di un mese in un aeroporto, suddivise fra partenze e arrivi.
Lo svolgimento del problema deve tenere conto che la persona si muove nell'aeroporto secondo un percorso prefissato nelle diverse aree con tempistiche che dipendono dalle diverse tipologie di volo: nazionale o internazionale.

### Descrizione della rilevanza gestionale del problema

L’applicazione sarebbe utile per la gestione efficace dei servizi forniti da un aeroporto commerciale e del suo indotto. Il traffico determinerà il dimensionamento e la turnazione del personale addetto a check-in, security, assistenza e permetterà di pianificare l’offerta di carattere commerciale quali duty free shop , ristorazione , shopping, parcheggi, trasferimenti ecc.

### Descrizione dei data-set per la valutazione	

Il dataset di base è quello già utilizzato a lezione Openflight, che verrà filtrato per i soli voli domestici, in partenza o arrivo, dagli aeroporti dello stato di New York. Inoltre, i dati saranno integrati con il db Airline On-Time Performance, proveniente  da https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236&DB_Short_Name=On-Time, per ricavare gli scheduling dei voli.
Manualmente, verranno inseriti le capacità degli aeromobili che operano quelle rotte, e l'occupazione media mensile, dove presente, verrà ricavata da https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=309&DB_Short_Name=Air%20Carriers.
I dati si riferiscono a tutti i mesi dell'anno 2016.

### Descrizione preliminare degli algoritmi coinvolti	

-Integrazione di più basi di dati con normalizzazione delle stesse.
-Creazione di indici per ottimizzare le query.
-Query al database per ottenere tutti i dati necessari.
-Algoritmo di simulazione: in funzione della tipologia di volo, nazionale o internazionale, della fascia oraria e dell'ora di partenza o arrivo si creeranno degli eventi ad hoc, per determinale il numero di persone transitanti nell'area "Departures" e nell'area "Landings".  
L'algoritmo terrà conto che per i voli nazionali i passeggeri arriveranno in aeroporto un'ora prima del decollo e non effettueranno il check-in, mentre per quelli internazionali è previsto l'arrivo dei passeggeri due ore prima e il check-in per il carico dei bagagli in stiva.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione graficamente sarà composta da 4 menù a tendina per selezionare rispettivamente aeroporto da analizzare, fascia oraria, mese e giorno della settimana in questione. Tramite un pulsante "Visualizza voli", in due finestre di testo, distinte in partenze e arrivi, verranno visualizzati tutti i voli che verranno presi in considerazione per lo studio del traffico aeroportuale. Per ogni volo verranno visualizzate compagnia aerea, numero del volo, orario di partenza/arrivo, passeggeri previsti e aeroporti di partenza e arrivo. 
Inoltre, cliccando sul pulsante "Avvia simulazione", su una nuova finestra di testo appariranno relativamente a partenza e arrivo il numero di persone che hanno transitato nelle varie aree distinte.
Per le partenze si avranno : check-in, security control, area shop e imbarco.
Ai fini del calcolo si assume che le persone siano impegnate nelle rispettive aree:
-check-in (solo per voli internazionali) 60 min;
-security control 15 min;
-area imbarco mezz'ora antecedente al decollo;
-duty free variabile (differenza temporale tra uscita dal security e arrivo all'imbarco). 
Nel caso degli arrivi, invece, verranno visualizzate le persone in fase di atterraggio e trasporto nell'aeroporto (20 min), al ritiro bagagli (voli internazionali) (30 min) e infine nei pressi dell'uscita, in cui sarà possibile avvalersi dei servizi di trasporto pubblico o privato.

**Comment by fulcorno** [comment]
La proposta è coerente con gli obiettivi ed è descritta in modo dettagliato e completo.
Per me è approvata.
L'unico appunto: i tempi di permanenza nelle varie aree dell'aeroporto sono fortemente variabili in funzione della dimensione degli aeroporti (Los Angeles è diverso da Torino ...), sarebbe utile tenerne conto. Idem, alcuni aeroporti sono in realtà composti da più "Terminal" indipendenti (non so se questa informazione sia disponibile).

**Comment by 203574** [comment]
Purtroppo l'informazione relativa ai terminal degli aeroporti non c'è nel database. Tuttavia, potrei cercare di affinare la questione dei tempi di attesa, ragionando sul numero di voli nell'aeroporto (aeroporti più grandi hanno un traffico maggiore) oppure sui singoli voli impostando ad esempio l'apertura di un gate check-in ogni tot persone che devono effettuarlo.

**Comment by fulcorno** [comment]
ok, erano solo suggerimenti, se riesci a tenere conto di questi fattori è meglio, altrimenti fa lo stesso. 
In ogni caso se ti limiti agli aeroporti nello stato di NY, non dovrebbero essere molti dati (da reperire dai siti web ed inserire a mano...).

**Comment by 203574** [comment]
Ok ci provo. Quindi posso iniziare a lavorare? c'è un repository?
