### ISSUE TITLE
Pasto’ improving post covid

### ISSUE THREAD

**Issue by VillaAlberto** [TdP-prove-finali/Introduzione#52]
### Studente proponente

S245184 Villa Alberto

### Titolo della proposta

Pasto’ improving post covid

### Descrizione del problema proposto

Ottimizzare e valutare i possibili investimenti che può attuare il gestore di una piccola attività di ristorazione (25 coperti circa) per far fronte alle nuove regolamentazioni imposte della legislazione sul covid. Alla luce di queste stabilire quali siano gli investimenti e le scelte di gestione ideali per ottimizzare l’attività attuale e aumentare al massimo il tasso gradimento della clientela nell’ottica futura di avviare un’espansione dell’attività.

### Descrizione della rilevanza gestionale del problema

Partendo da dati reali di un’attività ben avviata effettuare simulazioni con il software in fase di progetto per aiutare il titolare dell’impresa nelle strategie future di sviluppo dell’attività. In particolare analizzare i punti critici bottleneck odierni e indagare quali siano le scelte strategiche per risolvere la problematica. La nuova legislazione prevede una riduzione di coperti all’interno del locale. Ipotizzare tramite una simulazione l’opportunità di creare un dehors esterno per recuperare i tavoli interni. Per ottimizzare la situazione odierna stabilire se sia opportuno aumentare la varietà di proposte del locale (piatti freddi oppure piatti che richiedono un diverso tipo di preparazione più immediato e un processo parallelo, avviare un sistema di asporto che non sempre aggrada il cliente ma può ridurre la congestione nel locale).

### Descrizione dei data-set per la valutazione	

I dati sono ottenuti dal sistema attualmente utilizzato per la gestione dei clienti. Il software permette di conservare le comande effettuate, il momento in cui si presenta il cliente al locale con una comanda fittizia, il tempo di evasione dell’ordine è facilmente ottenibile, infine dall’orario dello scontrino rilevo il momento in cui il cliente si allontana soddisfatto: la varietà del locale si basa sull’utilizzo di diverse farine pregiate per la preparazione di piatti che hanno circa stesso tempo di preparazione, in alternativa sono prevedibili altri due tipi di portate da gestire secondo un diverso processo, tutte queste informazioni sono desunte dall’esperienza del personale del locale che collabora al riempimento del dataset con misurazioni sul campo. Anche tutte queste informazioni sono memorizzate dal database e saranno da base per lo sviluppo della simulazione a eventi discreti.

### Descrizione preliminare degli algoritmi coinvolti	

Il sistema è previsto per lavorare sull’ultimo periodo a regime dell’attività (mesi di gennaio e febbraio anno corrente) al termine della pausa estiva il database dovrà essere nutrito con i dati quotidiani in modo tale da avere stime e simulazioni che si modellano nel tempo secondo il reale afflusso di clienti all’attività. (È molto difficile fare inferenza sull’afflusso di clienti in questo periodo incerto è quindi ideale fare previsioni che si modifichino secondo i dati effettivamente registrati)
Attraverso un algoritmo ricorsivo si vuole estrapolare dal database un insieme di giornate (per valutare un investimento è bene prendere un worst-case di una settimana tra gli ultimi due mesi di dati raccolti presenti nel database e in continuo aggiornamento esempio max numero di clienti e min fatturato). Il sottoinsieme di dati dunque sarà alla base di una simulazione su parametri modificabili dal gestore per simulare l’introduzione di upgrade e nuovi investimenti sull’attività. La grande mole di dati ben organizzata e strutturata sarà utile per fare considerazioni sulle preferenze dei clienti e sull’adattamento a diversi fattori (cambiamenti climatici possono influire sulla scelta dei piatti o sull’utilizzo dell’eventuale dehors e quindi suggerire un approccio diverso da parte della cucina).

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’interfaccia dell’applicazione dovrà prevedere una sezione per l’input dei dati giornalieri (in modo che le stime siano sempre su dati attuali anche in seguito alla tesi in modo tale da rimanere utile supporto per il gestore del locale). È prevedibile poi una sezione statistica che permetta di vedere un insieme di dati aggregati rilevanti sulla situazione effettiva (non simulata). Una schermata dovrà poi permettere l’interazione del titolare per variare i parametri della simulazione (che corrispondono a ipotizzabili migliorie es.aumento di posti conseguente all’investimento per l’installazione di un dehors esterno, riduzione del tempo di preparazione degli alimenti dovuto a piatti con un diverso processo di produzione per sgravare la cucina. Permettere di definire un grado di fiducia del titolare: quale insieme di dati desidero ottenere dalla ricorsione? Prendo come riferimento una settimana a carico ordinario oppure faccio una stima più ottimistica o pessimistica? Dipende dal tipo di scelta da effettuare. Altri valori da stabilire in base all’osservazione diretta del fenomeno). A questo punto è da sviluppare un’adeguata interfaccia che permetta il confronto tra la situazione pre-post introduzione della miglioria in modo da agevolare il lettore nelle sue analisi economiche basate sulla soddisfazione dei clienti e sulla corretta gestione delle richieste da parte dello staff.

**Comment by fulcorno** [comment]
Il problema affrontato e gli algoritmi coinvolti sono adeguati, quindi la proposta è accettata.
È importante fare attenzione al database utilizzato, che poiché verrà allegato al progetto non potrà contenere dati sensibili per l'azienda (forse conviene lavorare su una copia con valori "falsati").
