### ISSUE TITLE
Strumento per la valutazione e la selezione d’investimenti nel mercato immobiliare

### ISSUE THREAD

**Issue by alessiosoru** [TdP-prove-finali/Introduzione#54]
### Studente proponente

s235059 Soru Alessio

### Titolo della proposta

Strumento per la valutazione e la selezione d’investimenti nel mercato immobiliare

### Descrizione del problema proposto

L’applicazione si pone l’obiettivo di consentire all'utente immobiliarista di avere un quadro generale, attraverso la visione di precise statistiche, sulla situazione immobiliare nella città presa in considerazione. In seguito a una fase preliminare di analisi, consiglierà un elenco ottimale di immobili da acquistare che andranno a creare un “portafoglio immobiliare” personalizzato a seconda della forza economica posseduta e delle preferenze indicate.

### Descrizione della rilevanza gestionale del problema

Il problema ha una forte rilevanza per soggetti operanti nella compravendita di beni abitativi, consistendo nell'assunzione di uno strumento che permetta una immediata visione della gestione del proprio capitale. In base ai propri requisiti e alle risorse finanziare disponibili, fornirà un elemento aggiuntivo di confronto che possa supportare la valutazione del mercato preso in esame, appoggiando o confutando le osservazioni qualitative ottenute durante una fase di analisi preliminare.

### Descrizione dei data-set per la valutazione	

https://www.kaggle.com/harry007/philly-real-estate-data-set-sample

Per la creazione dell’applicazione, verrà utilizzato un data-set di compravendita immobiliare della città di Philadelphia i cui dati sono ottenuti da phila.gov.
Ogni riga della tabella individua una proprietà immobiliare, identificata dal suo indirizzo. Per ogni immobile sono disponibili i dati di alcune caratteristiche peculiari, tra le quali si possono precisare le più notevoli ai fini dello sviluppo dell’applicazione:
o	Address (indirizzo);
o	Postal code (codice postale);
o	Violent crime rate (tasso di criminalità);
o	School score (punteggio medio delle scuole della zona);
o	Zillow estimate (stima del valore di mercato dell’immobile fatta da Zillow, compagnia immobiliare di elevata rilevanza negli USA);
o	Rent estimate (stima del possibile rendimento dell’affitto dell’immobile);
o	Year built (anno di costruzione);
o	Finished SqFt (piedi quadrati dell’immobile completato);
o	Bedrooms (numero di camere da letto);
o	Bathrooms (numero di bagni);
o	PropType (tipologia di immobile);

Inoltre, per completare i dati, verrà utilizzato un ulteriore data-set che mette in relazione i nomi dei quartieri con i codici postali ad essi associati.

### Descrizione preliminare degli algoritmi coinvolti	

L’applicazione prevederà una prima parte di ricerca di statistiche estratte dal database tramite semplici algoritmi di selezione dei record richiesti.
Il principale algoritmo implementato sarà di tipo ricorsivo e svolgerà la funzione di ricerca di un “portafoglio immobiliare” ottimale personalizzato in base ai valori indicati dall'utente. In particolare, verrà generato un elenco di immobili da acquistare (sostanzialmente un problema dello zaino) in base ai seguenti parametri indicati dall'utente:

- Obbligatori:
	N. minimo di case che si vogliono acquistare (il massimo viene imposto dall'applicazione per motivi di complessità algoritmica);
	Budget disponibile;
- Opzionali (sarà possibile selezionare al massimo 1/2 vincoli opzionali, una volta selezionato/i il/i vincolo/i non sarà possibile selezionarne altri):
	Tipologia di immobili;
	Stima del rendimento degli affitti (media dell’elenco degli immobili selezionati);
	Crime rate;
	Anno di costruzione;
	Range tra massimo e minimo di metri quadri dell’immobile (convertiti dai piedi quadrati);
	Numero di camere da letto minime per ogni immobile;
	Numero di bagni minimo per ogni immobile;
	Quartiere in cui si vogliono acquistare gli immobili (o almeno un immobile se non sono presenti immobili in vendita a sufficienza);
	Immobile da inserire necessariamente nell'elenco.
Inoltre, si eseguirà l’algoritmo ricorsivo in modo da sfruttare al massimo il budget per ottenere il numero minimo di immobili con le caratteristiche richieste (acquisto il numero minimo di immobili ma con valore di mercato maggiore, privilegia la qualità) oppure in modo da ottimizzare l’elenco minimizzando la spesa dal budget e inserendo il maggior numero possibile di immobili con le caratteristiche richieste (acquisto di un numero elevato di immobili ma con basso valore di mercato, privilegia la quantità).

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione sarà suddivisa in due sezioni:

- La prima permetterà di raccogliere una serie di record sul contesto immobiliare della città, individuati in modo da dare all'utente una panoramica della situazione generale. In particolare, l’utente avrà la possibilità di visualizzare le statistiche medie per ogni zona della città, osservando sia la zona con valori massimi e minimi per ogni caratteristica che decide di selezionare dal data-set, sia gli elenchi dei quartieri ordinati in base alla caratteristica in quel momento selezionata. Con caratteristiche si intendono le quantità medie per zona dei valori tabulari del data-set come il crime rate, lo school rate, l’anno di costruzione medio degli immobili, affitti medi, valore medio di mercato, tipologia principale di immobili.

- La seconda richiederà i valori necessari alla ricerca di un “portafoglio immobiliare” ottimale, permettendo l’inserimento dei parametri obbligatori (budget disponibile, n. minimo di immobili che si vuole acquistare, scelta booleana tra privilegiare la quantità o la qualità degli immobili) e poi richiederà di selezionare una/due caratteristiche opzionali dalla lista estratta dal database, per la generazione del “portafoglio immobiliare” personalizzato (elenco ottimale che verrà visualizzato dall'utente in seguito alla selezione dei parametri e l’invio della richiesta) che, appunto, varierà in base alle caratteristiche selezionate dall'utente. In particolare, per esempio, l’utente avrà la possibilità di indicare un immobile che vuole necessariamente acquistare e che perciò dovrà essere obbligatoriamente inserito nel portafoglio, di conseguenza l’applicazione darà la possibilità di ricalcolare la soluzione ottima in base al nuovo parametro imposto.

**Comment by fulcorno** [comment]
L'applicazione proposta e gli algoritmi coinvolti sono congrui, la proposta è dunque accettata.
