### ISSUE TITLE
Applicazione per creare la rosa perfetta del Fantacalcio

### ISSUE THREAD

**Issue by JacopoDBadino** [TdP-prove-finali/Introduzione#55]
### Studente proponente

s248726 Badino Jacopo Dylan

### Titolo della proposta

Applicazione per creare la rosa perfetta del Fantacalcio.

### Descrizione del problema proposto

Dai videogiochi alla vendita di diritti, il calcio è oggi un vero e proprio settore di mercato a sè stante.
Recentemente, in particolare, sembra essere esplosa la moda del "Fantacalcio", un gioco che può essere svolto tra amici o in rete, e nel quale ognuno di noi può diventare allenatore di una squadra di calcio, costruita aquistando giocatori tramite aste o basandosi su prezzi prefissati, a fronte ovviamente di un budget limitato di "fantamilioni", deciso precedentemente.
Dopo aver acquistato i giocatori necessari, il "fantallenatore" dovrà schierare la propria formazione di giornata in giornata, e otterrà un punteggio che varierà a seconda dei voti assegnati dalle redazioni dei quotidiani sportivi e a seconda di "bonus" e "malus" (gol, assist, ammonizioni, espulsioni...) attribuiti ai suoi 11.
Anche in questo ambito non sono tardati ad arrivare brand dedicati come "Fantacalcio.it" che ha iniziato a vendere prodotti a tema, ma anche applicazioni per gestire i risultati e studiare tattiche. La mia applicazione intende seguire questo filone, cercando di fornire consigli sui giocatori migliori e di aiutare gli utenti ad ottenere grandi risultati con la minima spesa. 

### Descrizione della rilevanza gestionale del problema

Per quanto si tratti in fondo soltanto di un passatempo, e per quanto nell'effettivo successo finale della squadra abbia un ruolo fondamentale anche la fortuna, questa può essere sicuramente aiutata da un mercato svolto oculatamente. Ed è in questo mercato che entra in gioco il nostro lato manageriale.
Sarà importante gestire bene i nostri "fantamilioni", individuare i giocatori che stanno facendo meglio durante la stagione in corso e il cui prezzo è ancora conveniente, bilanciare i reparti (Portiere, Difesa, Centrocampo e Attacco). In generale sarà nostro obiettivo ottimizzare le spese per la nostra rosa, riuscendo ad ottenere giocatori migliori sulla carta spendendo il minimo possibile.

### Descrizione dei data-set per la valutazione	

Per il data-set mi sono appoggiato al sito "Fantacalcio.it", scaricando prima i file riguardanti le statistiche sui giocatori (_https://www.fantacalcio.it/statistiche-serie-a_) e poi quelli sulle quotazioni (_https://www.fantacalcio.it/quotazioni-fantacalcio_) tramite le due sezioni messe a disposizione dal sito. Entrambi i file erano inizialmente in formato xlsx e ho quindi provveduto a convertirli in formato sql per poterli poi sfruttare come visto a lezione.
Si noti come i dati in questione si riferiscono alla stagione appena terminata. L'applicazione potrebbe essere maggiormente utile a stagione in corso, utilizzando quindi dati parziali e che possono essere sfruttati per il prosieguo della stagione.
Il database è dunque formato da 2 tabelle.
La prima, '**quotazioni**', contiene informazioni sui prezzi dei giocatori.

Le colonne indicano:

- Id: Un identificativo univoco per il giocatore in questione, chiave primaria della tabella;
- R: Il ruolo del giocatore, indicato da un carattere (P per Portiere, D per Difensore, C per Centrocampista, A per Attaccante);
- Nome: Il nome del giocatore;
- Squadra: Il nome della squadra di appartenenza del giocatore;
- QtA: La quotazione attuale del giocatore, aggiornata dopo l'ultima giornata disputata;
- QtI: La quotazione iniziale del giocatore, ad inizio stagione;
- Diff: La differenza tra quotazione attuale ed iniziale.

La seconda, '**statistiche**', contiene invece informazioni sulla stagione in corso:

Le colonne indicano:

- Id: Un identificativo univoco per il giocatore in questione, chiave primaria della tabella;
- R: Il ruolo del giocatore, indicato da un carattere (P per Portiere, D per Difensore, C per Centrocampista, A per Attaccante);
- Nome: Il nome del giocatore;
- Squadra: Il nome della squadra di appartenenza del giocatore;
- Pg: Il numero di partite disputate dal giocatore;
- Mv: La media voto del giocatore;
- Mf: La media fantavoto del giocatore, che tiene conto di bonus e malus (gol, assist, ammonizioni, espulsioni...);
- Gf: I gol segnati dal giocatore;
- Gs: I gol subiti dal giocatore;
- Rp: I rigori parati dal giocatore;
- Rc: I rigori calciati dal giocatore;
- R+: I rigori segnati dal giocatore;
- R-: I rigori sbagliati dal giocatore;
- Ass: Gli assist del giocatore;
- Asf: Gli assist da fermo del giocatore;
- Amm: Le ammonizioni rimediate dal giocatore;
- Esp: Le espulsioni rimediate dal giocatore;
- Au: Gli autogol del giocatore.

### Descrizione preliminare degli algoritmi coinvolti	

La prima parte dell'applicazione sfrutterà semplicemente operazioni di tipo inserimento/ricerca, oltre a qualche semplice operazione svolta sui dati.
La seconda parte dell'applicazione utilizzerà invece un algoritmo di ricorsione per la ricerca della migliore squadra possibile, dopo aver settato i filtri del caso.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione sarà divisa in due parti.

La prima parte presenterà un menù a tendina dal quale sarà possibile scegliere una delle squadre iscritte al campionato in corso. Cliccando su un apposito bottone, verrano visualizzati per la squadra selezionata alcuni giocatori chiave:

- Top Player: Il giocatore con la media fantavoto più alta della rosa;
- Sorpresa: Il giocatore con il rapporto media fantavoto /  quotazione iniziale più alto della rosa;
- Muro: Il difensore con la media voto pulita più alta della rosa;
- Assistman: Il giocatore con più assist all'attivo della rosa;
- Flop: Il giocatore con la media fantavoto più bassa della rosa.

La seconda parte presenterà invece un campo di testo attraverso il quale l'utente potrà specificare i crediti a disposizione e dei menù attraverso i quali potrà scegliere quanti giocatori per ruolo sta cercando. Dopo aver settato i filtri della ricerca, cliccando su un apposito bottone, l'applicazione calcolerà per lui la migliore soluzione in termini di giocatori da acquistare con quel budget.
Sarà inoltre possibile specificare se si sta cercando la rosa migliore in termini di fantavoto o di voto pulito.

Si noti che tutti i giocatori presi in considerazione dal programma dovranno aver preso parte ad almeno il 50% delle partite.

**Comment by fulcorno** [comment]
È un po' troppo vala la definizione di quale sia la "squadra migliore" o la "rosa migliore": sulla base di quali parametri viene valutata la soluzione? quali sono i vincoli che possono influenzare la scelta? come entrano in gioco tutti i campi di quotazione e statistiche?

**Comment by JacopoDBadino** [comment]
Potrei cambiare l'ultima parte così:

La seconda parte presenterà invece un campo di testo attraverso il quale l'utente potrà specificare i crediti a disposizione e dei menù attraverso i quali potrà scegliere quanti giocatori per ruolo sta cercando. Dopo aver settato questi filtri, cliccando su un apposito bottone, l'applicazione calcolerà per lui:

- Best Mf Team: la rosa migliore ottenibile in termini di fantavoto, ovvero una squadra composta da tanti giocatori per ruolo quanti richiesti dall'utente, il cui prezzo complessivo (calcolato sommando le quotazioni attuali) sia minore o uguale al budget indicato, e con la somma delle medie fantavoto più alta possibile.

- Best Mv Team: la rosa migliore ottenibile in termini di voto pulito, ovvero una squadra composta da tanti giocatori per ruolo quanti richiesti dall'utente, il cui prezzo complessivo (calcolato sommando le quotazioni attuali) sia minore o uguale al budget indicato, e con la somma delle medie voto più alta possibile.

Per esempio, si potrebbe effettuare una ricerca anche per un singolo giocatore: impostando come filtro **1 Portiere, 0 Difensori, 0 Centrocampisti e 0 Attaccanti** e come massimo budget **10 fantamilioni**.
Richiedendo il **Best Mf Team**, il programma troverà il portiere con la miglior fantamedia acquistabile con quel budget (_in questo caso Dragowski della Fiorentina, con Mf=5 e Qta=9_).
Richiedendo invece il **Best Mv Team**, il programma troverà il portiere con la miglior media acquistabile con quel budget (_Sirigu del Torino, con Mv=6,43 e Qta=8_).

Richiedendo più giocatori l'algoritmo ricorsivo del programma andrà a cercare il miglior compromesso tra i reparti rispettando il budget.

Si noti che tutti i giocatori considerati dal programma dovranno aver preso parte ad almeno il 50% delle partite.

**Comment by JacopoDBadino** [comment]
Ho provato a sviluppare il programma.
Funziona tutto correttamente, anche se aggiungerei due specifiche nel testo:
- Il vincolo che la “Sorpresa” calcolata abbia una media fantavoto almeno sufficiente, evitando così che le sorprese siano giocatori col solo merito di avere una quotazione iniziale molto bassa;
- Il vincolo di selezionare un massimo di 3/4 giocatori nel calcolatore di rosa finale (anche sul programma verrebbero aggiunti controlli), per evitare di bloccare il programma.
Immaginavo che aumentando il numero di giocatori/crediti sarebbe rallentato vistosamente il processo, ma in fondo il sistema è pensato più per essere un “tappabuchi” con pochi crediti che non un generatore di un intera formazione.
Facendo qualche esempio, sarà quindi possibile cercare 2 difensori e 1 portiere con 45 crediti, o ancora 3 attaccanti con 50 crediti, ma non 2 portieri, 4 difensori e 5 centrocampisti con 230 crediti.

**Comment by fulcorno** [comment]
ok, va bene con i chiarimenti che hai aggiunto
