### ISSUE TITLE
Collezionisti LEGO - gestione magazzino

### ISSUE THREAD

**Issue by salva78Github** [TdP-prove-finali/Introduzione#56]
### Studente proponente

s232047 Salvatore Dipace

### Titolo della proposta

Collezionisti LEGO - gestione magazzino

### Descrizione del problema proposto

Considerato un magazzino di pezzi LEGO ampliato negli anni attraverso l'acquisto di set o di mattoncini sfusi,
si vuole sviluppare un'applicazione che permetta di analizzare le potenzialità dello stesso in termini di numero massimo 
di set (ufficiali o mock proposti da appassionati) costruibili contemporaneamente con i pezzi a disposizione in base ad alcuni requisiti
(set appartenenti alla stessa linea, set con numero massimo di pezzi < N, ecc..)
 
### Descrizione della rilevanza gestionale del problema

Si tratta di un problema di gestione di risorse a disposizione per ottimizzare una funzione obiettivo.
L'interesse verso questo gioco è rimasto immutato negli anni e coinvolge non solo bambini, ma anche adulti collezionisti.
Per alcune persone si tratta anche una forma di investimento che si rivaluta negli anni dopo che un set viene messo fuori produzione.
Potrebbe essere interessante fornire uno strumento che permetta di capire come ottimizzare il magazzino a disposizione.

### Descrizione dei data-set per la valutazione	

Il data-set è reperibile qui: https://www.kaggle.com/rtatman/lego-database/.
Per ogni set commercializzato fino al 2017 (tabella sets) sono elencati tutti i pezzi necessari (tabella inventory_parts).
Serve una tabella nuova per gestire il magazzino dei pezzi sfusi a disposizione del collezionista 
(struttura simile alla tabella parts con un campo per tenere conto della quantità a disposizione).

### Descrizione preliminare degli algoritmi coinvolti	

Stabilito i criteri per la ricerca dei set costruibili con quanto a disposizione in magazzino,
si ricercherà l'insieme ottimo di set attraverso la ricorsione considerando tutte le combinazioni 
che rispettano i criteri scelti dall'utente (problema simile a quello dello zaino)
Per la parte di analisi dei set si vorrebbe costruire un grafo pesato su cui ricercare i set che 
converrebbe acquistare per minimizzare i costi e massimizzare il numero di set costruibili.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

- semplici funzionalità di gestione del magazzino per
	-- aggiungere pezzi sfusi (si seleziona il pezzo da una tendina e si specifica la quantità acquistata)
	-- aggiungere i pezzi di un set acquistato (si seleziona il set da una tendina e si recuperano i pezzi dal db)
- funzione per introdurre un nuovo prodotto o mock (caricare quindi i pezzi necessari per costruirlo)
- l'utente che intende conoscere l'insieme di set che può costruire con i pezzi in magazzino sceglie, se vuole,
  alcune caratteristiche dei set da considerare (i temi dei set, gli anni di produzione, il numero minino o massimo di pezzi)
  e l'obiettivo della ricerca, per esempio l'insieme con più set;
- scelto un insieme di set prodotti (anche in questo caso scegliendo alcune condizioni), si costruisce un grafo pesato dove
	-- il set è un nodo
	-- definito un coefficiente di accoppiamento, esiste una connessione tra due nodi se questo è > 0
  Il coefficiente di connessione è 0 se tra due set non ci sono pezzi in comune. Vale 1 se l'unione dei pezzi tra due set permette di costruirli entrambi.
  Su questo grafo si può cercare la sequenza più lunga di set con più alto accoppiamento.
  Questa sequenza dovrebbe essere quella che se non acquistata interamente, permette al collezionista di risparmiare di più sull'acquisto dei pezzi mancanti.

**Comment by fulcorno** [comment]
La proposta è accettabile.
Non sono sicuro di avere capito una cosa: il programma affronterà due problemi diversi, giusto?
1. dati i pezzi in mio possesso, quali sono i "set" che potrei costruire (o vendere - massimizzando il profitto)
2. dati i pezzi in mio posseso ed un gruppo di set a cui sono interessato, dimmi quanti/quali pezzi mi mancano e quali siano i set che conviene acquistare per riempire il 'gap'
Sono problemi distinti o sono due aspetti dello stesso problema?

**Comment by salva78Github** [comment]
Sì, io li vedrei come due problemi diversi. 
Per il primo (cosa posso fare) applicherei la ricorsione, per il secondo (dato un obiettivo, analizzare cosa manca per raggiungerlo dando indicazioni eventualmente su cosa conviene fare) costruirei un grafo.

grazie

**Comment by fulcorno** [comment]
ok

**Comment by salva78Github** [comment]
Buongiorno,
ho letto il regolamento che ha pubblicato, ma vorrei una conferma su due punti

1.   per la sessione di laurea di Dicembre la scadenza per l'iscrizione è il 12/11. Per motivi di lavoro non riuscirò a
     consegnare gli elaborati prima del 2/11 sera. Vede problemi?

2.   Non riesco a committare i sorgenti nello spazio https://github.com/TdP-prove-finali/DipaceSalvatore che
     ha creato. Lo farà Lei a partire dallo zip che le condividerò. Torna?

Grazie.
Cordiali saluti

**Comment by fulcorno** [comment]
Ho rischiato di non vedere questo commento perché l'hai aggiunto ad una issue chiusa anziché aprire una nuova issue.
Confermo che se consegni il lavoro entro il 2/11, riuscirò a correggerlo ed a registarlo in settimana.

Riguardo al repository, devi effettivamente fare Push tu direttamente. 
Dovresti avere ricevuto a suo tempo una mail di invito da GitHub. Se no, puoi andare qui per entrare:
https://github.com/TdP-prove-finali/DipaceSalvatore/invitations

**Comment by salva78Github** [comment]
aperto issue #61

grazie
