### ISSUE TITLE
Applicazione per playlist musicali

### ISSUE THREAD

**Issue by alessiasortino** [TdP-prove-finali/Introduzione#57]
### Studente proponente

s249682 Alessia Sortino

### Titolo della proposta

Applicazione per creare playlist musicali 

### Descrizione del problema proposto

Il programma mira a creare una playlist che possa andare bene per ogni singolo utente. Infatti quest'ultimo potrà selezionare alcuni parametri rilevanti per  capire i propri gusti in campo musicale, come genere, anno, ecc..  Il programma partendo da questi input creerà una selezione musicale che  possa assecondare l'utente.

### Descrizione della rilevanza gestionale del problema

Il programma mira alla creazione di un insieme ottimo basato su input dati dal cliente.
Negli ultimi anni la personalizzazione è una peculiarità sempre più  richiesta dagli utenti. Essi, infatti,   vogliono che tutto ciò  che viene da loro utilizzato sia adattato ai propri gusti.
In particolare, l'utente  potrà indicare da quanti brani deve essere composta la sua playlist e il programma dovrà trovare  la selezione migliore di brani dati gli input.

### Descrizione dei data-set per la valutazione	
I data- set sono reperibili al https://www.kaggle.com/danield2255/data-on-songs-from-billboard-19992019 e identificano 4 diverse classifiche musicali (billboard, rria, grammy e spotify) nell'arco del ventennio che va dal 1999 al 2019. Io utilizzerò le tabelle relative alle canzoni e non agli album.

### Descrizione preliminare degli algoritmi coinvolti	
I metodi utilizzati saranno, principalmente,  quello di ricerca di un artista, anche mediante filtri,  e quello che mi permetterà di visualizzare tutte le info relative a quell'artista. Successivamente,  sulla base del genere selezionato, si creerà un grafo, in cui i nodi sono gli artisti e gli archi rappresentano il numero di premi vinti. Si utilizzerà inoltre un metodo di ricorsione per stabilire qual è l'insieme ottimo di brani, partendo dall'artista selezionato.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	
L'utente potrà creare due tipi di playlist:
1) per artista:
* sarà possibile cercare un artista, eventualmente utilizzando dei filtri. (genere musicale/sesso/ se gruppo o artista singolo, ecc), oppure visualizzare l'artista vincitore di un dato  premio per un dato anno.

* una volta visualizzato tale artista sarà possibile avere una panoramica dei premi vinti e delle  relative canzoni.

*a questo punto l'utente potrà creare una playlist inserendo il numero di canzoni che desidera. Si partirà dall'artista selezionato e verranno aggiunti soltanto brani appartenenti a artisti che fanno lo stesso genere dell'artista selezionato e che hanno vinto un numero di premi >= all'artista sorgente.

2) per anno
* l'utente indicherà l'anno di interesse e verrà fatta una selezione musicale sulla base di genere e anno selezionato.

**Comment by fulcorno** [comment]
Ho alcuni dobbi che ti chiederei di chiarire.

- un grafo in cui i nodi siano gli artisti e gli archi i premi vinti non mi convince. Un premio è vinto da un solo artista. Un arco collega 2 artisti. Forse un grafo non è necessario, in questo problema?

- non mi è chiaro il criterio di ottimizzazione... sarebbe sufficiente inserire tutti i brani dello stesso autore (o dello stesso genere), ordinati per numero di premi, ed avrei fatto la playlist migliore; non serve un algoritmo complesso per fare ciò. Forse ci sono dei vincoli o dei criteri di ottimizzazione che non ho percepito...

**Comment by alessiasortino** [comment]
Buongiorno,
ha ragione, non mi sono espressa bene ed, effettivamente, non ha molto 
senso questa impostazione.
L’idea era quella di creare un collegamento coerente tra le canzoni 
della playlist.
Volendo si potrebbe modificare in questo modo: l’utente seleziona un 
artista x, dopodiché trovo gli artisti che fanno lo stesso genere e che 
hanno un’altra caratteristica in comune ( tipo il numero di followers).
Da ognuno di questi artisti prendo una canzone da aggiungere alla 
playlist. Se il numero di artisti è minore del numero di canzoni ( 
richieste dall’utente) per la playlist, prendo più canzoni per artista. 
Su quale sia effettivamente la playlist migliore potrei crearmi qualche 
metodo che valuta la playlist nel complesso e assegna un voto ad 
esempio..
Spero di essermi spiegata meglio.

Alessia Sortino


Il 2020-08-27 12:10 Fulvio Corno ha scritto:

**Comment by fulcorno** [comment]
Scusami se insisto, ma continua a non essermi chiaro il concetto di playlist "migliore". 
Tu hai descritto un metodo (arbitrario, euristico) per costruire una playlist, ma perché quella dovrebbe essere meglio di un'altra? Se non abbiamo un "obiettivo" da raggiungere o una "metrica" da valutare, stiamo producendo dei risultati "a buon senso", senza alcun controllo vero. Non mi pare molto ingegneristico, come approccio...

Forse conviene fare un passettino di formalizzazione ulteriore del problema.
Abbiamo delle canzoni.
Queste hanno un grado di similarità (e definiamo in base a che cosa: autori? genere? ...)
Ciascuna ha poi un livello di qualità (follower? media giudizi? ...)
L'utente ha un interesse (espresso come? autori? genere? canzoni di esempio?)
A questo punto l'algoritmo sceglie un insieme di brani che massimizza una certa metrica (definiamo quale!), e che deve rispettare alcuni vincoli (quali sono? continuo a non vedere cosa mi impedisce di prendere sempre le N canzoni più votate).
Infine, una playlist ha un ORDINE specifico dei brani. Dati gli stessi brani ABC, esiste un meccanismo che ci dice se sia "meglio" (secondo la nostra metrica) A B C o B A C?

**Comment by alessiasortino** [comment]
Buonasera professore,
io non partirei dalle canzoni, come le dicevo, ma dagli artisti. 
L'utente manifesta l'interesse nel momento in cui sceglie un artista, quindi  si stabilisce la similarità tra artisti,  basata  su generi musicali e followers ( parametro della tabella Artist).
Noti gli artisti simili, alla playlist verranno aggiunte le canzoni, appartenenti agli artisti trovati e che abbiano , ad esempio, il maggior numero di premi vinti. L'ordine invece non credo sia importante, infatti l'intento è proprio quello di trovare una playlist casuale, ma che comunque rispetti i vincoli imposti dall'utente. Non sono, quindi, soltanto le N canzoni più votate poiché appartengono a un sottoinsieme di artisti. In definitiva da un lato la playlist accontenta i gusti dell'utente, dall'altra le canzoni vengono scelte sulla base di dati, che abbiamo nelle tabelle, che definiscono quanto la canzone piaccia al pubblico.( In generale una canzone che ha vinto molti premi è una canzone che piace).

**Comment by fulcorno** [comment]
Mi permetto di insistere.
1. L'utente sceglie un artista.
2. Sulla base di questo artista, per ogni brano stabilisci una misura di "similarità" (qui ti serve un grafo? probabilmente no, ma dipende da come definisci questa misura)
3. A questo punto, il programma non fa altro che ordinare i brani in base al valore di tale misura, e prendere i primi N.

Non ci vedo nessun algoritmo di ottimizzazione o ricerca.

**Comment by fulcorno** [comment]
Cara Alessia, per favore fammi sapere se intendi procedere con questa proposta o se la dobbiamo chiudere (ovviamente potrai sempre presentarne una nuova, su un tema simile o su un tema diverso).

**Comment by alessiasortino** [comment]
Salve Professore, può chiudere questa proposta in quanto sto scrivendo la tesi con un altro relatore. La ringrazio comunque.

**Comment by fulcorno** [comment]
ok
