### ISSUE TITLE
Proposta tesi

### ISSUE THREAD

**Issue by Enrico97** [TdP-prove-finali/Introduzione#58]
### Studente proponente

s238835 Marando Enrico

### Titolo della proposta

Organizzazione reale di un magazzino "irreale"

### Descrizione del problema proposto

Il problema che si cerca di risolvere è abbastanza semplice ed intuitivo in ogni realtà commerciale, ovvero, avendo a disposizione una certa somma di denaro da spendere, come suddividere tale cifra nei diversi reparti del magazzino affinché i clienti possano trovare ciò che cercano, restando quindi soddisfatti? Ovviamente un acquisto di un prodotto in un reparto piuttosto che in un altro comporta prezzi diversi e di conseguenza anche quantità finali disponibili diverse. E' ovvio che anche le probabilità che un cliente acquisti un prodotto piuttosto che un altro sono diverse, il programma dovrà infatti tener conto di questo dato così come dovrà valutare il fatto che, in mancanza del prodotto richiesto (perché il magazzino ha finito le scorte), c'è una probabilità che il cliente acquisti da un altro reparto (probabilità che varia a seconda del reparto di partenza e del reparto sostituto) oppure andare via insoddisfatto.   

### Descrizione della rilevanza gestionale del problema

Il problema mira a gestire la crescita di "fama" e di conseguenza anche economica di un'attività commerciale, effetti che vanno di pari passo con il giusto soddisfacimento dei clienti. Si cerca quindi di gestire nel miglior modo possibile una somma di partenza, investendola in modo da soddisfare il maggior numero di clienti possibili.

### Descrizione dei data-set per la valutazione	

In quanto illusionista, ho lavorato come commesso e consulente per diversi anni in un negozio di magia di Torino, nel quale ero anche a mia volta cliente, perciò i vari dati quali prezzi e probabilità dei diversi comportamenti dei clienti, derivano dalla diretta esperienza personale sul campo.

### Descrizione preliminare degli algoritmi coinvolti	

Verrà usato principalmente un algoritmo di simulazione che, una volta inseriti i parametri di partenza, simulerà nell'arco di una giornata di lavoro l'arrivo dei vari clienti e di conseguenza le diverse scelte che quest'ultimi possono fare, tenendo conto dell'andamento del magazzino e di conseguenza della percentuale di clienti soddisfatti.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente dovrà selezionare la cifra scelta (ad esempio 1000-2000-3000 €) per riempire il magazzino, specificando anche quanto di quella cifra usare nei singoli reparti (ipotizzati tre reparti per semplicità). Fatto ciò parte la simulazione che restituirà come risultato la percentuale di clienti soddisfatti. L'utente può perciò variare le cifre nei singoli reparti per rendersi conto dell'andamento della percentuale di soddisfacimento giornaliero dei clienti.  

[dati.pdf](https://github.com/TdP-prove-finali/Introduzione/files/5167379/dati.pdf)

**Comment by fulcorno** [comment]
Il problema è certamente interessante e pertinente.
La sua descrizione però mi pare abbastanza superficiale. Il problema della gestione di un magazzino è studiatissimo, ci sono già molti modelli esistenti in campo gestionale, quindi bisognerebbe rifarsi a qualcuno di tali modelli senza apportare delle semplificazioni troppo riduttive.
Ad esempio, non ha senso che la creazione del magazzino sia fatta solo con un investimento iniziale. I negozi si riforniscono continuamente (molti settimanalmente), andando a rimpiazzare gli oggetti venduti.
Molto critiche sono anche le definizioni delle varie probabilità: sarebbe bello poterle desumere da dati oggettivi (ad esempio l'andamendo degli acquisti reali nel negozio), e non solo dall'esperienza personale.

La mia opinione è che si possa lavorare sulla proposta per renderla più completa e realistica.

**Comment by Enrico97** [comment]
Buongiorno professore,
Ho già parlato col titolare del negozio e sono in attesa di ricevere le ricevute di vendita in modo tale da poter definire in modo oggettivo le varie probabilità a cui facevo riferimento. Ho inoltre pensato di aggiungere una quarta categoria al magazzino (libri didattici). Parlando sempre col titolare ho pensato di ragionare in questo modo: effettuare la simulazione su un mese (24 giorni) con 20 clienti al giorno, ogni settimana il magazzino viene riempito a capienza massima (con le quantità scelte in partenza dall’utente), perciò ogni cliente in caso di prodotto esaurito può decidere se aspettare la settimana prossima o se andare via senza acquistare ed essere quindi insoddisfatto. In questo modo l’unica probabilità lasciata all’esperienza personale rimane quella che definisce se un cliente aspetta o meno una settimana per avere il prodotto o se invece decide di cambiare negozio, tutte le altre probabilità saranno appunto dedotte dall’andamento annuale del negozio. Volevo sapere, nell’attesa di ricevere i dati, se così il problema fosse più realistico.
Grazie,
Enrico

**Comment by fulcorno** [comment]
Sì, tenendo conto dei dati aggiuntivi che potrai reperire, e con la simulazione "più fedele" del magazzino, ritengo che il progetto sia accettabile.
