### ISSUE TITLE
Previsione per gestione mezzi di trasporto rifiuti

### ISSUE THREAD

**Issue by antonio-mnt** [TdP-prove-finali/Introduzione#59]
### Studente proponente

s249152 Monteleone Antonio 

### Titolo della proposta

Previsione per gestione mezzi di trasporto rifiuti

### Descrizione del problema proposto

L’applicazione si pone l’obiettivo di effettuare una previsione annuale sulla raccolta dei rifiuti partendo da dati reali dell’anno precedente. L’idea è quella di permettere all'utente attraverso una simulazione ad eventi di inserire una quantità di mezzi per il trasporto rifiuti con la relativa capienza espressa in Kg in modo da poter programmare la gestione dei trasporti per l’anno successivo. Inoltre, l’utente sarà in grado di effettuare alcune operazioni di ricerca ottenendo una media dei kg di rifiuti prodotti o smaltiti selezionando alcuni parametri.

### Descrizione della rilevanza gestionale del problema

L’applicazione implementa uno dei problemi principali di programmazione e gestione per un’azienda, la previsione.                                                                                                                                                  L’azienda partendo dai dati acquisiti durante l'anno potrà programmare gli investimenti per l'anno successivo.
Essa potrà verificare quanti mezzi siano necessari in modo da gestire al meglio i trasporti dei rifiuti.
Inoltre, potrà capire se sia conveniente acquistare i mezzi di trasporto rifiuti o noleggiarli.

### Descrizione dei data-set per la valutazione	

Il data-set mi è stato gentilmente offerto dall'azienda multiservizi AMIU Taranto da cui ho successivamente estratto i dati utili. Disponibile sul drive al seguente link: https://drive.google.com/drive/folders/1vm_bYuSfqc6DLfxFXCAkC7MdKXXKBSp7?usp=sharing. Il data set contiene una sola tabella composta da undici colonne.                                                                                          1) Data_Registrazione
2) Ragione_Sociale_Produttore
3) Ragione_Sociale_Trasportatore
4) Ragione_Sociale_Smaltitore
5) C_E_R (Catalogo Europeo Rifiuti)
6) Descrizione_Europea1
7) Peso_Netto_Rifiuto_in_Kg
8) Zona_di_raccolta
9) Riferimento_Rifiuto
10) Descrizione_Unita_Locale_Produttore
11) Tipo_movimento

### Descrizione preliminare degli algoritmi coinvolti	

Il principale problema algoritmico è la simulazione ad aventi. L’utente sarà in grado di scegliere una Descrizione_Europea1 in base al quale verranno generati gli eventi ordinati secondo la Data_Registrazione. In base a tale scelta l’utente dovrà inserire la quantità di mezzi di trasporto da utilizzare con la relativa capienza espressa in Kg per ogni Ragione_Sociale_Trasportatore che in quell'anno si è occupata del trasporto dei rifiuti corrispondenti alla Descrizione_Europea1 selezionata. I dati sono riferiti all'anno 2019 per cui si farà una previsione per l’anno 2020 considerando che gli stessi eventi del 2019 si possano verificare nel 2020. Il Peso_Netto_Rifiuto_in_Kg potrà variare secondo una probabilità p inserita dall'utente. L’utente inoltre, dovrà inserire un percentuale massima entro cui tali misure possano variare ed un numero massimo di viaggi al giorno consentiti per i mezzi. Al termine della simulazione il risultato sarà quello di verificare la quantità di rifiuti che non si è potuto trasportare per ogni Zona_di_Raccolta in modo da poter capire la quantità di mezzi su cui investire e verificare i giorni di inattività dei mezzi per capire se sia conveniente l’acquisto o il noleggio.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione prevederà un’interfaccia divisa in due sezioni. Una inerente alle operazioni di ricerca in cui l’utente potrà selezionare una Ragione_Sociale_Produttore o una Ragione_Sociale_Smaltitore ed un mese oppure l’anno intero. Successivamente verrà fornita la media in Kg dei rifiuti secondo i parametri selezionati. La seconda sarà inerente alla simulazione ad eventi con tutte le opzioni di inserimento dei parametri descritti al punto precedente.

**Comment by fulcorno** [comment]
L'argomento è interessante ed il data-set è valido.
Ho un dubbio sulla finalità della simulazione. Non mi pare che dal data-set si possano determinare i MEZZI impiegati (almeno dalle colonne non si evince), quindi come è possibile condurre una simulazione variando il numero di mezzi? Dovrai fare delle ipotesi aggiuntive sulla capienza e sui tempi di raccolta e trasporto. Bisognerà in qualche modo garantire che queste ipotesi aggiuntive siano coerenti (ad esempio, deve esistere una combinazione di valori per cui si arrivi agli stessi risultati del data-set).

Con questa precisazione, il progetto è approvato.
