### ISSUE TITLE
Richiesta tesi - Analisi del sistema GTFS

### ISSUE THREAD

**Issue by dennisfeno** [TdP-prove-finali/Introduzione#6]
### Studente proponente

Dennis Feno – mat. 215337

### Titolo della proposta

Analisi del sistema GTFS

### Descrizione del problema proposto

Si vuole risolvere il problema di gestione delle linee di trasporto pubblico di una qualsiasi città che utilizzi il sistema GTFS (che definisce un formato comune per gli orari dei trasporti pubblici e le relative informazioni geografiche). In particolare, si vuole proporre un sistema che permetta di calcolare il percorso migliore tra due punti, tenendo in considerazioni diverse variabili, ed eventualmente simulare i flussi di passeggeri all’interno di alcune linee per valutare la soddisfazione o meno degli utenti. 

### Descrizione della rilevanza gestionale del problema

L’interesse dal punto di vista gestionale può essere ricondotto al problema di calcolo di un percorso ottimo, impiegando il minor tempo possibile o, eventualmente, il più economico. Un altro aspetto rilevante dell’applicazione consiste nell’analizzare i flussi di utilizzo dei mezzi pubblici, per poter avere un’idea di come ottimizzare il passaggio o l’arricchimento di questi su una linea. Il problema della corretta gestione del trasporto pubblico è molto rilevante dal punto di vista della “customer satisfaction” e dal punto di vista economico, pertanto è di grande rilevanza gestionale riuscire a fornire un’idea su come poter migliorare i flussi sopra citati.

### Descrizione dei data-set per la valutazione	

Le fonti dai quali verranno prelevati i dati fanno riferimento al data-set del sistema di trasporti GTT presente sul sito del corso. Dopo aver visualizzato il sistema di archiviazione dei dati, GFTS, è stato riscontrato che dovrebbe essere uno standard per la trascrizione di dati di questo tipo. All’interno del database, in particolare, sono presenti differenti tabelle che rappresentano rispettivamente le fermate all’interno della rete, le linee, le tratte, gli orari delle fermate, le frequenze e altre tabelle di supporto per la rappresentazione dei dati. Può essere considerato un data-set completo e flessibile: è possibile reperire su internet dati relativi a differenti città e questo potrebbe consentire l’eventuale portabilità dell’applicazione. 

### Descrizione preliminare degli algoritmi coinvolti

Oltre ai classici algoritmi di inserimento, visualizzazione, modifica e ricerca di dati all’interno del database, saranno presenti algoritmi di ottimizzazione e simulazione di eventi. In particolare, per quanto riguarda l’ottimizzazione, verranno confrontati differenti percorsi calcolati con algoritmo di tipologia Dijkstra, proponendone differenti in base a differenti criteri di selezione. Per quanto riguarda l’algoritmo di simulazione dei flussi, è necessario stimare la quantità di persone che necessitano di una determinata linea in base alle fermate più frequentate e, tramite una serie di eventi di salita e discesa di passeggeri, verificare che le linee presenti all’interno del database, riescano a soddisfare la richiesta e, in caso contrario, può essere proposta una modifica dei passaggi per testare se la soluzione proposta possa risolvere eventuali problemi di sovraffollamento e/o inutilizzo di una determinata linea. Essendo i dati molto relazionati tra loro sarà sicuramente possibile rappresentarli tramite strutture dati come grafi e di conseguenza eseguire operazioni su questi. 

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

A livello di previsione generale, l’applicazione permetterà di visualizzare tramite interfaccia grafica i dati di maggiore rilevanza presenti nel database. Idealmente, sarà quindi possibile inserire, modificare o eliminare dati tramite finestre dedicate. Come descritto in precedenza, si vogliono suddividere le funzionalità dell’applicazione in due macro-categorie, pertanto saranno presenti differenti aree all’interno dell’interfaccia grafica che delineeranno le differenze; in particolare, nell’interfaccia di ricerca del percorso migliore, sarà possibile selezionare un punto di partenza, un punto di destinazione ed un eventuale orario di partenza. Verranno quindi forniti dall’applicazione i possibili risultati proposti. Per quanto riguarda la parte di simulazione, verrà richiesto dall’utente la selezione di una linea o di una fermata e verrà fornito l’esito della stessa. Verrà ricercata una modalità di visualizzazione delle informazioni che renda più immediata la comprensione dei dati in uscita.

**Comment by fulcorno** [comment]
La tematica è adeguata ed il data-set proposto va bene.
Di seguito alcuni commenti:
- Ritengo che la proposta sia troppo ampia: mi limiterei solo alla ricerca dei percorsi, oppure solo alla simulazione.
- Di conseguenza, dovresti scegliere una delle due modalità (ricerca percorsi o simulazione traffico/passeggeri), ed approfondirle un po' di più. Ad esempio, la ricerca percorsi, da quali dati di partenza parte? due posizioni? o anche l'orario? può comprendere dei tratti a piedi? ecc... Analogamente, se scegli la simulazione, allora che cosa viene simulato di preciso? persone? mezzi? e con quale/i criterio/i? In altre parole, va descritto il problema da risolvere (e non genericamente "faccio una ricerca di percorso").
- Le funzioni di inserimento/modifica di dati non hanno senso, in quanto il GTFS fornisce dati "definitivi" che non dobbiamo modificare.
- Dal punto di vista algoritmico, non sono sicuro che algoritmi come Dijkstra siano in grado di gestire grafi di quelle dimensioni. Sarebbe da verificare. Di sicuro non gestiscono informazioni aggiuntive nel grafo (ad esempio gli orari di passaggio). Ancora una volta, è necessario prima avere definito bene il problema da risolvere, e solo dopo analizzare i possibili algoritmi risolutivi.

Una volta selezionato e descritto meglio l'algoritmo, la proposta potrebbe andare bene.

**Comment by dennisfeno** [comment]
## Studente proponente
Dennis Feno – mat. 215337
## Titolo della proposta
Analisi del sistema GTFS
## Descrizione del problema proposto
Si vuole risolvere il problema di gestione delle linee di trasporto pubblico di una qualsiasi città che utilizzi il sistema GTFS (che definisce un formato comune per gli orari dei trasporti pubblici e le relative informazioni geografiche). In particolare, si vuole proporre un sistema che permetta di simulare i flussi di passeggeri all’interno di alcune linee per valutare la soddisfazione o meno degli utenti. Più in dettaglio, si vuole simulare la salita di passeggeri su una determinata linea, con la possibilità che questi possano cambiare, rimanere sullo stesso mezzo o giungere a destinazione. Lo scopo è quindi quello di verificare se il passaggio di mezzi relativi ad una determinata linea è sufficiente a soddisfare la richiesta degli utenti stessi o se sia necessario incrementare il passaggio.
## Descrizione della rilevanza gestionale del problema
Un aspetto rilevante dell’applicazione consiste nell’analizzare i flussi di utilizzo dei mezzi pubblici, per poter avere un’idea di come ottimizzare il passaggio o l’arricchimento di questi su una linea. Il problema della corretta gestione del trasporto pubblico è molto rilevante dal punto di vista della “customer satisfaction” e dal punto di vista economico, pertanto è di grande rilevanza gestionale riuscire a fornire un’idea su come poter migliorare i flussi sopra citati. 
Descrizione dei data-set per la valutazione
Le fonti dai quali verranno prelevati i dati fanno riferimento al data-set del sistema di trasporti GTT presente sul sito del corso. Dopo aver visualizzato il sistema di archiviazione dei dati, GFTS, è stato riscontrato che dovrebbe essere uno standard per la trascrizione di dati di questo tipo. All’interno del database, in particolare, sono presenti differenti tabelle che rappresentano rispettivamente le fermate all’interno della rete, le linee, le tratte, gli orari delle fermate, le frequenze e altre tabelle di supporto per la rappresentazione dei dati. Può essere considerato un data-set completo e flessibile: è possibile reperire su internet dati relativi a differenti città e questo potrebbe consentire l’eventuale portabilità dell’applicazione.
## Descrizione preliminare degli algoritmi coinvolti
L’applicazione sarà quindi sviluppata principalmente tramite un algoritmo di simulazione di eventi. In particolare è necessario stimare la quantità di persone che necessitano di una determinata linea in base alle fermate più frequentate e, tramite una serie di eventi di salita e discesa di passeggeri, verificare che le linee presenti all’interno del database, riescano a soddisfare la richiesta e, in caso contrario, può essere proposta una modifica dei passaggi per testare se la soluzione proposta possa risolvere eventuali problemi di sovraffollamento e/o inutilizzo di una determinata linea. Una struttura dati come un grafo potrebbe rappresentare alla perfezione la rete di trasporti, dove i vertici potrebbero rappresentare le differenti fermate, mentre i nodi rappresenterebbero i collegamenti tra le varie fermate forniti dalle varie linee. Si valuterà successivamente se utilizzare un grafo con archi pesati o meno. Un possibile sviluppo per l’applicazione è quello di ricevere in input tramite interfaccia grafica il numero di utenti medio che sale al capolinea di una determinata linea e il numero di utenti che sale o scende ad ogni fermata, con una probabilità che l’utente cambi linea o giunga a destinazione. Dati questi input, l’applicazione simulerà il flusso di passeggeri tramite una coda di eventi e verranno stilate delle statistiche riguardo la soddisfazione dei clienti. La simulazione potrà essere ripetuta fino a trovare la giusta combinazione tra clienti soddisfatti e costi di gestione dei mezzi.
## Descrizione preliminare delle funzionalità previste per l’applicazione software
A livello di previsione generale, l’applicazione permetterà di visualizzare tramite interfaccia grafica i dati di maggiore rilevanza presenti nel database. Oltre a questo, saranno presenti delle aree di input all’interno delle quali si potranno inserire, come descritto in precedenza, i parametri della simulazione. Verrà quindi richiesto all’utente di selezione una linea o una fermata di rilevanza e verrà fornito l’esito della stessa. Verranno chiaramente effettuati dei controlli per quanto riguarda la coerenza dei dati. Verrà ricercata una modalità di visualizzazione delle informazioni che renda più immediata la comprensione dei dati in uscita.

**Comment by fulcorno** [comment]
ok, proposta approvata
