### ISSUE TITLE
Prova finale - problemi push - issue #56

### ISSUE THREAD

**Issue by salva78Github** [TdP-prove-finali/Introduzione#61]
Continuo ad avere problemi con il push sul progetto che mi ha creato.
Ho provato a seguire le indicazioni 

"
Riguardo al repository, devi effettivamente fare Push tu direttamente.
Dovresti avere ricevuto a suo tempo una mail di invito da GitHub. Se no, puoi andare qui per entrare:
https://github.com/TdP-prove-finali/DipaceSalvatore/invitations
"

ma la prima volta GIthub ha detto che l'invitation era scaduta. Dopodiché per i tentativi successivi ho sempre ottenuto l'errore
"
Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account
"

Io il lavoro ce l'ho qui:
https://github.com/salva78Github/GestioneMagazzinoLego

In attesa di una nuova invitation, può iniziare a vederlo.

Grazie
Cordiali Saluti

**Comment by fulcorno** [comment]
ho cancellato e rifatto la condivisione, vedi se ti è arrivato un nuovo invito

**Comment by salva78Github** [comment]
Riuscito. Caricato tutti i file.
grazie

**Comment by fulcorno** [comment]
bene. Il progetto è finito (lo posso valutare)? In caso affermativo, fai domanda di conclusione sul Portale, così ricevo la notifica e posso registrarlo.
