### ISSUE TITLE
Simulazione e previsione furti in un supermercato

### ISSUE THREAD

**Issue by eugeniomassini** [TdP-prove-finali/Introduzione#62]
### Studente proponente

s236883 Eugenio Massini

### Titolo della proposta

Simulazione e previsione furti in un supermercato

### Descrizione del problema proposto

L'obiettivo che l'applicazione si pone è quello di individuare il numero di possibili ladri e i beni maggiormente taccheggiati per poter migliorare l'efficacia della sicurezza e dei controlli. Ogni anno i furti danneggiano i distributori per miliardi di euro e nei prossimi anni con l'aumento dei servizi per velocizzare la spesa (es. Pronto Spesa di Esselunga) è un trend che potrebbe aumentare se non venissero adottate le giuste misure di prevenzione e controllo. Attraverso una simulazione ad eventi sarà possibile settare vari parametri per analizzare i fattori in moda da diminuire il rischio di furti.

### Descrizione della rilevanza gestionale del problema

L'applicazione si pone come strumento per un manager di un particolare supermercato, in cui sia presente un servizio per velocizzare la spesa come "Pronto Spesa" di Esselunga, per essere aiutato per le principali decisioni nell'ambito delle attività di prevenzione dei furti. Sarà per lui possibile inserire dati in suo possesso per personalizzare la simulazione, si potranno inserire il numero di clienti e scegliere l'orizzonte temporale su cui eseguire la simulazione e decidere anche su che aspetti concentrarsi, come ad esempio la categoria di beni da controllare maggiormente, eventualmente per notare se ci sono pattern nei furti.

### Descrizione dei data-set per la valutazione	

Il dataset è disponibile a questo link https://bit.ly/3flMhju, è un dataset molto ricco, provvederò a eseguire una riduzione dei dati per non rendere eccessivamente lento il programma visto che alcuni file contano 1 milione di righe.
Al momento è l'unico che mi permetta di dividere i prodotti in categorie per poter creare dei filtri*.
[*Per ora lo considero definitivo, sto comunque continuando a cercare nel caso riuscissi a trovare qualcosa che possa ugualmente servire il mio scopo in ottica anche migliorativa]

### Descrizione preliminare degli algoritmi coinvolti	

L'idea è quella di partire dalla creazione di un grafo analizzando tutti gli ordini presenti nel dataset per avere un'indice di correlazione che leghi i prodotti in base agli acquisti (es. "se ho acquistato pasta, uova, pecorino sarà più probabile acquistare il guanciale).
Dopo aver creato il grafo si procederà con il simulare l'interazione del cliente nel supermercato, la simulazione dovrà essere ideata in modo che il Cliente "interagisca" in maniera consistente con i prodotti in base ai pesi nel grafo e che si sfruttino in modo adeguato gli input dell'utente quali ad esempio probabilità di furto, probabilità di controllo, categorie di prodotto da controllare sempre.
Inoltre sarà di particolare importanza la corretta creazione delle strutture dati per raccoglierli in maniera semplice da sfruttare e successivamente visualizzare.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente avrà a disposizione una dashboard in cui inzializzare il grafo in base ai dati presenti nel database, una volta creato correttamente potrà far partire la simulazione, selezionando per prima cosa l'orizzonte temporale su cui si vuole operare: giorno, settimana, mese.
Successivamente potrà scegliere se eseguire una simulazione rapida, basata su valori standard presi da articoli e studi di settore, oppure una simulazione personalizzata.
Per quest'ultima sarà possibile inserire:
-la probabilità che il cliente sia un ladro
-il numero giornaliero di clienti per il supermercato
-la probabilità di controllare un cliente
-le categorie di prodotti da controllare 
-scegliere se controllare in base al numero di articoli nel carrello e quanti articoli controllare

Al termine dalla simulazione saranno visualizzati graficamente i dati in modo da evidenziare al meglio i risultati ottenuti.

**Comment by fulcorno** [comment]
Scusa per l'enorme ritardo.... se sei ancora interessato, per me la proposta è accettabile. Ma magari nel frattempo ti sei già laureato... Fammi sapere grazie

**Comment by eugeniomassini** [comment]
Buongiorno Professor Corno, non si preoccupi, purtroppo o per fortuna mi sono laureato. La ringrazio comunque di tutto, il suo corso è stato uno dei miei preferiti durante la triennale.

**Comment by fulcorno** [comment]
bene per la laurea, scusa ancora per il disguido. In bocca al lupo per il proseguimento degli studi.
