### ISSUE TITLE
Applicazione di supporto alla costruzione della rosa al Fantacalcio

### ISSUE THREAD

**Issue by giacomo13** [TdP-prove-finali/Introduzione#63]
### Studente proponente

s246827 Giacomo Maggio

### Titolo della proposta

Applicazione di supporto alla costruzione della rosa al Fantacalcio

### Descrizione del problema proposto

Il Fantacalcio è un gioco nel quale ogni partecipante costruisce la rosa della propria squadra per poi competere con altre squadre all'interno di un torneo o campionato. 
La parte cruciale del gioco risiede nella costruzione della rosa, la quale avviene tramite l'acquisto simulato di giocatori reali. Ogni squadra possiede infatti un budget di crediti prestabilito e attraverso la spesa di questi è possibile acquistare i giocatori desiderati. In base alle prestazioni reali dei giocatori acquistati le squadre ottengono punti utili alla classifica finale.

Obbiettivo dell'applicazione è aiutare l'utente nella costruzione della propria rosa attraverso un'interfaccia che permetta la ricerca di dati utili e uno strumento che permetta l'ottimizzazione dei crediti posseduti in base alle necessità.

### Descrizione della rilevanza gestionale del problema

Nonostante non sia possibile prevedere il futuro, è possibile comunque cercare di investire al meglio i propri crediti puntando ai giocatori con le migliori prestazioni dell'anno precedente. Allo stesso tempo però il budget fornito non consentirà di acquistare tutti i migliori giocatori per ogni reparto, dunque è solo attraverso lo studio che è possibile massimizzare il risultato, visto il numero di crediti limitato.
Il compito dell'applicazione è dunque quello di semplificare questo studio, andando a velocizzare il processo di analisi del rendimento dei giocatori senza tralasciare il loro prezzo di acquisto.

### Descrizione dei data-set per la valutazione	

I data-set utili sono disponibili in formato .xlsx sul sito www.fantacalcio.it, nello specifico verranno utilizzati i seguenti database:
- quotazioni e  ruolo specifico dei calciatori (www.fantacalcio.it/quotazioni-fantacalcio/mantra)
- statistiche dei calciatori della stagione 2019-2020 (www.fantacalcio.it/statistiche-serie-a/2019-20/fantacalcio/medie)

I database verranno convertiti in formato .sql al fine di essere utilizzati per l'applicazione.

### Descrizione preliminare degli algoritmi coinvolti	

La prima parte e la seconda parte dell'applicazione prevedono l'utilizzo di algoritmi di selezione, ricerca ed ordinamento.
La terza parte dell'applicazione prevede l'utilizzo di un algoritmo ricorsivo.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

1) Ricerca giocatori e statistiche 

Dopo aver selezionato un ruolo e una squadra, l'applicazione restituisce una lista di giocatori di quella squadra che giocano in quella posizione, mostrando inoltre le seguenti statistiche:
- media voto
- media fantavoto
- gol
- assist
- presenze
- rapporto fantamedia/prezzo
È possibile inoltre selezionare una statistica, così da ordinare la lista dei giocatori in modo decrescente rispetto ad essa. Nel caso in cui non venisse selezionata alcuna statistica, l'applicazione restituirà i giocatori in ordine alfabetico.

2) Riserve del giocatore

Nel Fantacalcio classico i giocatori sono divisi in 4 macro-ruoli: portiere, difensore, centrocampista ed attaccante.
Esiste però una modalità del Fantacalcio che prevede l'utilizzo di ruoli più specifici, ovvero il Mantra. Nel Mantra i giocatori sono suddivisi ulteriormente, ad esempio i difensori sono suddivisi in difensori centrali, terzini destri e terzini sinistri (un giocatore può avere ruoli Mantra multipli).
Grazie a questa suddivisione è possibile acquistare giocatori della stessa squadra che giocano nello stesso ruolo Mantra, così facendo, nonostante si giochi nella modalità classica, si garantisce di possedere il sostituto di un determinato giocatore selezionato.
Una volta selezionato una squadra ed un ruolo classico (non Mantra), dovrà essere indicato un giocatore: l'applicazione restituirà una lista di giocatori della stessa squadra che possiedono uno dei ruoli Mantra del giocatore indicato, indicando inoltre la loro quotazione e il loro numero di presenze.

3) Ottimizzazione dei crediti 

Dopo aver selezionato un massimo di crediti spendibili ed un ruolo, l'applicazione richiederà una statistica da ottimizzare:
- portieri: minor gol subiti, maggior rigori parati, maggiore media voto, maggiore media fantavoto
- difensori, centrocampisti, attaccanti: maggiore media voto, maggiore media fantavoto, maggior rapporto gol/presenze

L'applicazione, attraverso l'utilizzo di un algoritmo ricorsivo, restituirà una lista di 4 giocatori in quel determinato ruolo in modo da ottimizzare la statistica indicata rimanendo sotto il budget indicato.
A fianco di ogni giocatore verrà inoltre indicata la quotazione (dunque i crediti da spendere) e il dato richiesto durante l'ottimizzazione.
L'algoritmo terrà conto solo di giocatori che avranno totalizzato almeno 18 presenze.

**Comment by fulcorno** [comment]
Scusami per il ritardo nella risposta. Non so se tu sia ancora interessato alla proposta, o se nel frattempo hai trovato un'altra soluzione.

Nel caso in cui ti interessasse continuare, la proposta per me va bene, verifica solo che sia ben distinta da quella di Jacopo Dylan Badino e Paolo Fiorio Plà che hanno lavorato sullo stesso data-set.

**Comment by fulcorno** [comment]
Dopo 4 mesi di inattività, chiudo questa proposta.
Se sei intenzionato a svolgere la prova finale, puoi aprire una nuova Issue.
