### ISSUE TITLE
Simulazione per trasporto di merci su gomma su scala regionale

### ISSUE THREAD

**Issue by davide2809** [TdP-prove-finali/Introduzione#64]
### Studente proponente

s263632 Agostini Davide

### Titolo della proposta

Simulazione per trasporto di merci su gomma su scala regionale.

### Descrizione del problema proposto
Nell’era dell’economia digitale l’e-Commerce si è affermata dapprima con grandi colossi internazionali e successivamente anche nelle piccole aziende locali, con effetti importanti sulla logistica applicata ai trasporti su gomma, su binari o tramite aereo.
Il problema presenta molteplici realtà, difatti sono tantissimi gli aspetti che la logistica stessa deve affrontare, dalla gestione dei magazzini alle consegne in città.
Tale applicazione si sofferma solo su determinati aspetti dell'argomento, in particolar modo i trasporti su gomma da magazzino a città e tralascia ciò che riguarda la gestione dei dipendenti e quella del magazzino.

### Descrizione della rilevanza gestionale del problema

Il problema logistico del trasporto viene spiegato e studiato in diversi casi in quanto variando i vincoli considerati si possono ottenere soluzioni molto diverse tra loro.
Utilizzando data-set non specifici e non di singole aziende, permetto di creare un'applicazione simil-realistica con l'obiettivo di simulare l'andamento di una giornata di lavoro lasciando all'utente la scelta di diversi elementi.
Lo scopo di tale simulazione è dare modo ad una qualsiasi azienda di osservare come il cambiamento di poche variabili sia radicale per il soddisfacimento della domanda esterna.

### Descrizione dei data-set per la valutazione
	
Come dichiarato in precedenza i data-set utilizzati non appartengono ad una specifica azienda, ma sono basati sui comuni e sulla distanza tra essi.
E' importante evidenziare che il calcolo della distanza non viene basato solo su latitudine e longitudine, ma calcolato sulla base delle diverse strade in ogni regione.
In particolar modo è presente sui data-set il tempo "reale" impiegato da un mezzo che parte da un comune per raggiungerne un altro.
I dati presenti sono oltre il milione per ogni regione, ad esempio per la regione Piemonte il dataset offre oltre 8 milioni di dati.
Il data-set utilizzato sarà rielaborato in base alla regione scelta da utente.
-I data-set sui comuni sono disponibili sul sito Istat con il loro codice alfanumerico.
-I data-set sul "reale" minutaggio tra i comuni è presente in questo link: https://www.istat.it/it/archivio/157423
(La scelta di utilizzare data-set cosi grandi può influire negativamente sull'aspetto computazionale ed in particolar modo non permette all'utente
di scegliere numeri elevati di mezzi e di consegne, perciò in caso il problema non riesca ad essere ottimizzato dovrò ricorrere a latitudine e longitudine).

### Descrizione preliminare degli algoritmi coinvolti
	
L'applicazione consiste nella scelta di una tra le seguenti opzioni: simulazione e ricorsione.
In primo luogo verrà chiesto all'utente di dichiarare dei parametri che verranno poi utilizzati in entrambe le opzioni, ovvero: la Regione da considerare, il comune nel quale vi è il magazzino principale e il numero di consegne da effettuare (ovvero il numero di comuni nel quale deve essere effettuata la consegna).
Successivamente verrà creato un grafo utilizzando i data-set della regione considerata.
In particolar modo si creerà un grafo a maglia completa aventi come nodi i comuni nel quale si deve effettuare la consegna e come archi il minutaggio "reale" che intercorre tra un comune ed un altro.
Successivamente l'applicazione fornirà due possibilità:
-La prima è una simulazione dei percorsi effettuati dai veicoli.
Quindi, dopo aver scelto il numero di veicoli e il numero delle consegne massime per percorso, verrà effettuata una simulazione ad eventi discreti riportando i tragitti.
-La seconda permette all'utente di scegliere il minutaggio massimo ed il comune nel quale si vuole effettuare l'ultima consegna.
L'applicazione fornirà di conseguenza il percorso ottimo, ovvero il massimo numero di consegne avendo come vincolo il tempo prestabilito, rivelando i comuni nel quale è passato.
Per la seconda possibilità si userà la ricorsione.
(Come descritto in precedenza la difficoltà risiede nel fare meno chiamate possibili al DB e fare in modo che l'applicazione gestisca più ordini possibili).

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

-Per prima cosa verrà richiesto all'utente di scegliere la regione.
-Si sbloccheranno poi: un menù a tendina con i comuni per scegliere il magazzino principale dal quale i veicoli partiranno ed un textfield che permette di inserire il numero di consegne da effettuare.
-Dopo aver creato il grafo all'utente verranno presentate due opzioni: la prima sarà effettuare la simulazione, la seconda consisterà nell' ottimizzare un percorso.  (Preferibilmente tutto nella stessa pagina)
Nel caso della scelta della simulazione verrà chiesto all'utente di inserire il numero di veicoli ed numero massimo di consegne che questi potranno effettuare, mostrando come risultato il percorso dei veicoli, il numero di consegne effettuate ed il numero di consegne eventualmente non effettuate.
Nel caso di ottimizzazione del percorso viene richiesto all'utente la destinazione e il minutaggio massimo con il quale si vuole che il veicolo arrivi a destinazione.

**Comment by fulcorno** [comment]
Chiedo scusa per il ritardo nella risposta...
Non so se il progetto ti interessi ancora o se nel frattempo hai trovato un'altra tesi.

Se ti interessa, direi che il problema è interessante ed il data-set delle distanze intercomunali è bellissimo.
Mi convincono di meno gli algoritmi proposti, in particolare la creazione di percorsi in cui non è definito a priori l'elenco delle destinazioni. Per ottimizzare il percorso dovrei avere un insieme di destinazioni da raggiungere... altrimenti raggiungo solo i comuni più vicini e gli altri non riceveranno mai alcuna consegna... Mi sfugge quindi il ragionamento che hai fatto nel definire il problema che hai illustrato.

**Comment by davide2809** [comment]
Gentile professore,
Sono ancora interessato a svolgere la tesi con lei e mi metto a disposizione per una discussione sugli algoritmi da me proposti.
In ogni caso cercherò di spiegarli in maniera più chiara possibile esplicando i ragionamenti svolti.

La simulazione ha come obiettivo quello di ricreare l'andamento di più veicoli che raggiungono più destinazioni decise a priori nel punto precedente, quindi al momento della simulazione ad essere simulato è l'andamento e il percorso di ogni veicolo.
Il problema quindi sorge nel fatto che bisogna raggiungere ogni singola destinazione e per farlo vi è un tempo prestabilito (ex. 24 ore), perciò vi è bisogno di un algoritmo del percorso che garantisca ciò.
Qui il problema può essere svolto in due modi:
1- Ottimizzo il percorso del primo veicolo con obiettivo di raggiungere più destinazioni possibili nel tempo massimo e successivamente lavoro sul secondo veicolo considerando che il primo percorso è stato ottimizzato e così via, lavorando quindi come se fosse un problema a più livelli (In questo caso non è necessaria una simulazione).
I problemi di tale considerazione riguardano l'assenza di tempo reale in quanto ogni percorso viene deciso a priori e in questo modo il problema risulta sbilanciato (nella maggior parte dei casi il primo veicolo lavora più degli altri) e inoltre crea un problema computazionale: svolgo tante ricorsioni quanti sono i veicoli e con numero di destinazioni che diminuisce all'ottimizzazione di ogni percorso.
2- Non ottimizzo il percorso, ma lo simulo in tempo reale: a partire è il veicolo con il "tempo minore", ovvero il veicolo che si libera prima.
In questo modo riesco a bilanciare il carico di lavoro sui diversi veicoli a costo di non ottimizzare il singolo percorso e ciò mi permette una sorta di bilanciamento.
L'ispirazione di tale algoritmo non ottimizzato è legata al fatto che cerco di sfruttare ogni mio veicolo preferendo l'utilizzo di tutti i miei lavoratori piuttosto che lasciarli a casa pagandoli.
Con la prima soluzione sono nell'ottica del "proprietario" che ha uno sguardo generale di ogni destinazione all'inizio della giornata, con la seconda sono nell'ottica del "lavoratore" che non conosce il percorso a priori, ma vede solamente la destinazione successiva.
Ho preferito utilizzare il secondo algoritmo in quanto mi permette anche un inserimento (ad occhio) di più dati come ad esempio più mezzi o più destinazioni.
In ogni caso mi sarebbe piaciuto comprendere entrambi gli algoritmi di ottimizzazione dei percorsi (utilizzando dati limitati per non sovraccaricare il computer) per effettuare dei confronti finali.
Il secondo punto della tesi che riguarda la ricorsione (basico) e ho preferito inserirlo per osservare i danni provocati da un eventuale simulazione non ottimizzata.
Dopo aver calcolato i percorsi dei veicoli non ottimizzati posso scegliere un qualunque comune del percorso e utilizzare lo stesso tempo impiegato per svolgere una ricorsione. 
La ricorsione mi garantisce un risultato ottimo sotto il punto di vista del numero delle destinazioni ed è quindi confrontabile con il risultato ottenuto utilizzando la simulazione.

Per quanto riguarda il numero di destinazioni da raggiungere è effettivamente la parte utile del problema: avere dei comuni che non vengono raggiunti dai veicoli indica che necessito di più veicoli per soddisfare la domanda.

Mi metto a disposizione in ogni momento per discussioni via messaggio o via videochiamata (se possibile è anche preferito) e aspetto sue notizie il prima possibile.

**Comment by fulcorno** [comment]
Capisco i due approcci proposti. Però non capisco "bisogna raggiungere ogni singola destinazione": intendi tutti i comuni italiani? (e perché mai bisognerebbe farlo?) o di una provincia/regione selezionata? Nel caso di applicazioni logistiche su scala nazionale, occorrerà pensare a degli "hub" distribuiti da cui partono i mezzi (non ha senso farli partire tutti da Roma).
Questo è l'aspetto che non mi è ancora chiaro, il resto invece va bene.

**Comment by davide2809** [comment]
Buongiorno professore,
l'idea iniziale in realtà era quella di fare un' applicazione logistica su scala nazionale, ma poi ho pensato che, come lei ha giustamente affermato, risulta eccessivamente irreale e non ha senso far partire tutti i mezzi da un unico magazzino. (Problemi legati anche alle isole)
Quindi ho pensato di considerare gli ordini su scala regionale, ovvero dopo aver scelto la regione nell'applicazione le altre regioni risultano come inesistenti. Avevo anche pensato all'utilizzo di più "hub" per regione, ma ho realizzato poi che l'utilizzo di un grande magazzino per regione fosse sufficiente. 
Per quanto riguarda le destinazioni intendo gli ordini  (numero scelto dall'utente), mentre il comune che corrisponde all'ordine viene scelto casualmente all'interno della regione considerata.
L'idea è quella di accettare solo un ordine per comune in modo tale che le "destinazioni" coincidano con gli "ordini", ma se troppo lontano dalla realtà questo problema può essere facilmente risolto.
Nel caso di altri dubbi sull'impostazione o idee per un' applicazione migliore o più "reale" sono a sua completa disposizione.

**Comment by fulcorno** [comment]
ok, va bene, proposta approvata con questi chiarimenti
