### ISSUE TITLE
Applicazione per la gestione di una squadra NBA

### ISSUE THREAD

**Issue by DavideBalossino** [TdP-prove-finali/Introduzione#66]
### Studente proponente

s256558 Davide Balossino

### Titolo della proposta

Applicazione per la gestione di una squadra NBA

### Descrizione del problema proposto

Il problema che si vuole risolvere è quello della gestione di una squadra NBA, rispettando alcuni vincoli come nella realtà: in primis il limite del salary cap, ovvero il fatto che il totale degli stipendi dei giocatori sotto contratto con una franchigia non possa superare una certa soglia, se non in alcune eccezioni descritte meglio nell’ultima sezione; un’altra condizione da tener presente è il numero minimo e massimo di giocatori per squadra.
L’applicativo permette di cercare giocatori in base alle caratteristiche desiderate, e individuare quali atleti della propria rosa cedere per poter arrivare ad acquisire il cestista ambito. Infine è presente la possibilità di liberarsi di alcuni dei propri giocatori e sostituirli con i migliori cestisti per ottimizzare la rosa in base alle caratteristiche cercate.

### Descrizione della rilevanza gestionale del problema

Il problema della gestione di una squadra riguarda direttamente i general manager delle franchigie NBA; ma anche più semplicemente chiunque si cimenti a giocare ai videogiochi della saga “NBA 2K” per PlayStation o XBOX, in cui ci si ritrova a vestire i panni del general manager della squadra scelta con l’obbiettivo di migliorarla e condurla alla vittoria del titolo finale.
Tale problema è quindi strettamente gestionale, le franchigie NBA possono ormai essere considerate a tutti gli effetti delle vere aziende, con valori che, come nel caso dei New York Knicks, arrivano oltre i 4 miliardi di dollari (dato Forbes del 2019). Il successo della squadra dipende in primis da chi ha il compito di assemblarla: il general manager.

### Descrizione dei data-set per la valutazione	

I dati relativi agli stipendi dei diversi giocatori derivano dal data-set al link:
https://www.kaggle.com/isaienkov/nba2k20-player-dataset

I dati relativi invece alle statistiche avanzate dei singoli giocatori derivano dal data-set al link:
https://www.kaggle.com/nicklauskim/nba-per-game-stats-201920

Entrambi i data-set fanno riferimento alla stagione passata, 2019/20, che è stata conclusa lo scorso 12 ottobre. 
In entrambi i casi sono presenti alcune colonne che al fine di questo lavoro contengono dati superflui, e sono quindi state eliminate.
Inoltre nel secondo data-set sono presenti più righe (652 in totale) rispetto al primo (430). Questo perché nel caso di giocatori che abbiano cambiato squadra in corso durante la stagione, nel secondo data-set vengono riportate su più righe sia le medie tenute in ciascuna squadra, sia in totale. Per lo svolgimento del programma si prendono in analisi le medie totali, che fanno quindi riferimento a tutta la stagione, ed il giocatore viene considerato parte della squadra in cui si trovava a fine stagione. 
Le righe superflue del secondo data-set saranno quindi rimosse.

Il formato originale dei dati era CVS, sono stati poi importati in HeidiSQL in modo da poterli gestire come visto a lezione.

### Descrizione preliminare degli algoritmi coinvolti	

Il programma si compone di diverse funzionalità: sarà possibile svolgere operazioni di ricerca, a seguito di un input da parte dell'utente, per trovare i giocatori più idonei ai parametri impostati, ad esempio sarà possibile cercare uno scorer (colui che segna molti punti) oppure un assistman e così via. Per presentare liste di giocatori ordinate in basa alla richiesta fatta ci si baserà sulle statistiche dell’ultima stagione 2019/20 conclusa pochi mesi fa.

Il tool implementa anche un algoritmo di ricorsione utile per individuare i giocatori di cui liberarsi in modo tale da poterne ingaggiare uno nuovo: l’utilità di tale metodo è spiegata meglio nella sezione successiva.

L’applicazione si propone inoltre di risolvere il “Knapsack problem”, ossia problema dello zaino, e per farlo si baserà sull’euristica di greedy: gli oggetti saranno ordinati in base al loro costo unitario, _ci/wi_ , ed esaminati in ordine decrescente. L'oggetto corrente viene inserito se e solo se il suo peso non supera la capacità residua, nel caso di questa applicazione rappresentato dal limite del salary cap.
Per ogni giocatore sarà generato un costo unitario tenendo conto delle statistiche nella specialità indicata dall’utente (ad esempio punti o rimbalzi o assist ecc) dello stipendio e di quanti altri giocatori abbiano tali statistiche (ad esempio essere l’unico ad avere una media di 20 punti a partita darà al giocatore un valore maggiore rispetto al caso in cui vi siano altri 10 giocatori ad avere circa 20 punti di media).
Tale euristica sarà implementata anche attraverso l’uso della ricorsione. 

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione offrirà le funzioni necessarie per gestire al meglio una franchigia NBA nei panni di un general manager: sia nella realtà sia limitatamente al mondo del gaming. 

In primo luogo l’utente dovrà scegliere la squadra di cui curare gli interessi.
Una volta presa tale decisione può sfruttare le diverse funzioni messe a disposizione.

Per gestire una squadra è necessario conoscere e osservare attentamente i giocatori in tutta la lega, sarà infatti permesso di impostare vari parametri di indagine per trovare i giocatori che, sulla base delle loro statistiche, soddisfino maggiormente la ricerca fatta. 
Se un giocatore viene ritenuto particolarmente interessante, o lo si desidera ottenere per un qualunque altro motivo, sarà possibile chiedere all’applicativo di individuare i cestisti della propria squadra da cedere in modo da permettersi, rispettando il salary cap, l’ingaggio del giocatore voluto. Verranno presentate le diverse soluzioni possibili, senza però che il numero di giocatori di cui disfarsi superi 4, in quanto sarebbe irrealistico. Il tutto rispettando il numero minimo e massimo di giocatori che si possono avere in rosa, rispettivamente 13 e 17. 
Nel caso in cui, la squadra possa direttamente permettersi l’ingaggio del cestista desiderato senza doversi prima liberare di alcuni suoi giocatori, l’utente sarà avvisato di tale opportunità.

Il rispetto del tetto salariale massimo è un punto importante per rendere l’esperienza realistica. Il salary cap come detto in precedenza rappresenta il totale degli stipendi dei giocatori e deve essere sotto una certa soglia uguale per tutte le squadre. Vi sono però alcune eccezioni per cui una squadra può trovarsi al di sopra del salary cap, questo è possibile che avvenga solo quando un team si trova a dover rinnovare un giocatore già appartenente alla sua rosa, a cui potrebbe essere offerto un certo compenso anche a costo di sforare il limite salariale.
Tuttavia una volta superato il salary cap la squadra potrà ingaggiare nuovi giocatori solo a condizione che essi abbiano uno stipendio pari al minimo salariale fissato dalla NBA.
Se invece la squadra volesse acquisire un giocatore con un ingaggio superiore al minimo dovrà prima liberarsi di uno (o più) suoi giocatori di modo tale che il 125% della somma dei loro stipendi non superi l’ingaggio del cestista che si vuole ottenere.

Un’ultima funzione messa a disposizione dell’utente permette di scegliere in prima istanza i giocatori della propria rosa ritenuti superflui e di cui liberarsi. A seguire sarà possibile impostare i criteri di ricerca per nuovi giocatori (ad esempio si potrà impostare di volere uno scorer e un assistman, dando a uno dei due la priorità) e verrà proposto dall’applicativo (risolvendo il problema dello zaino) il o i migliori cestisti possibili, in base al numero di giocatori che si era precedentemente deciso di cedere.

**Comment by fulcorno** [comment]
Il problema proposto è rilevante ed il data-set mi pare adeguato. Forse bisogna fare attenzione a porre dei vincoli ulteriori alla ricorsione per evitare esplosione di complessità.

La proposta è approvata.
