### ISSUE TITLE
Applicazione per la gestione e l’ottimizzazione delle prestazioni di una linea di produzione industriale

### ISSUE THREAD

**Issue by FedericoManzetti** [TdP-prove-finali/Introduzione#67]
### Studente proponente

S213240 Manzetti Federico

### Titolo della proposta

Applicazione per la gestione e l’ottimizzazione delle prestazioni di una linea di produzione industriale tramite simulazione

### Descrizione del problema proposto

L’applicazione sviluppata si prefigge di ricavare, tramite simulazione di funzionamento e permettendo l’inserimento dei singoli parametri delle workstation da parte dell’utente, i parametri di lavoro ottimali di una linea di produzione industriale, cercando di ottimizzarne il comportamento adattandosi ai dati di domanda quotidiani multiperiodali ricavati da un database esterno, il tutto con riferimento puntuale alle euristiche e alle formule di ottimizzazione derivate dalla Gestione della produzione e dai dati di benchmarking interno della linea.

### Descrizione della rilevanza gestionale del problema

La rilevanza gestionale del problema risiede nella capacità dell’applicazione di ottimizzare i parametri di lavorazione in base ad una data domanda ricavata dall’esterno, tale da permettere una gestione della produzione misurata sulle esigenze e sulle capacità delle linee a disposizione, oltre che nella possibilità di generare in modo modulare un’intera linea con parametri scelti dall’utente, permettendo quindi una maggiore personalizzazione della situazione analizzata ed un maggior numero di possibili casistiche affrontabili.

### Descrizione dei data-set per la valutazione	

L’applicativo utilizzerà un dataset fornito dal professor Chiabert riguardante l'andamento della domanda quotidiana di 3 prodotti distinti. I dati riguarderanno gli anni 2015-2017, e, nello specifico, consisteranno nella domanda definita giorno per giorno dei 3 prodotti finiti, ognuno dei quali di competenza di un anno differente nell’intervallo considerato.

### Descrizione preliminare degli algoritmi coinvolti	

-Creazione e gestione di varie linee di produzione, con specifiche relative alla natura della linea e degli imprevisti coinvolti incluse in appositi parametri (guasti, setup, rilavorazioni)
-Gestione delle query al database per ricavarne le vendite previste
-Simulazione multiperiodale, giorno per giorno, del funzionamento delle varie linee di produzione in base alle vendite previste del prodotto finito uscente dalla suddetta linea e proposta di miglioramenti sulla suddetta nei casi di problemi, imprevisti o di inefficienze. Si effettuerà un’operazione di ricorsione tra tutte le possibili combinazioni di parametri delle workstation per poter ottenere la linea più efficiente
Possibile, dati i valori dei vincoli iniziali sui parametri considerati.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione sarà fisicamente accessibile tramite un'interfaccia grafica che permetterà di dare in input i parametri di ogni workstation a disposizione per poter creare la linea di produzione ipotetica personalizzata su cui effettuare la simulazione. Tramite un apposito tasto di avvio, si eseguirà la simulazione di produzione sulla linea selezionata per un dato prodotto e, una volta fatto, si otterranno in output l’elenco delle stazioni della linea in questione, i parametri di funzionamento fondamentali della linea (Tempo Ciclo, Throughput e Work in Process) ed una diagnosi con focus sull’utilizzazione (parametro che fa da ago della bilancia tra corretto funzionamento e blocco/sottoutilizzo della stazione).
La simulazione consisterà nella determinazione quotidiana dell'input di materia prima da
immettere a monte della linea di produzione, la quale verrà volta per volta processata da ogni workstation in modo da poter garantire un throughput tale da soddisfare la domanda
del giorno in questione (si suppone di dover produrre per poter vendere o stoccare entro la sera del giorno considerato). Per ogni workstation si valuterà il tempo effettivo di lavorazione, parametro fondamentale per inquadrarne l’efficienza, dati i parametri di normale funzionamento, di varianza, o di funzionamenti particolari precedentemente preimpostati tramite apposita classe (utile ad inquadrare la variabilità di questi valori in una casistica reale). 
Nel caso non ci fossero ostacoli alla normale e prevista produzione, ogni giorno la quantità in uscita dalla linea sarebbe uguale alla domanda, mentre un’utilizzazione troppo alta o troppo bassa porterebbero ad un blocco del flusso di lavoro, rispettivamente per saturazione del collo di bottiglia e per sottoutilizzo. 
Durante la progettazione della sopracitata linea, si può fare anche un’analisi di benchmarking interno, valutando la vicinanza del comportamento della stessa rispetto ad un funzionamento supposto ideale (bassissima variabilità nei tempi effettivi di lavorazione)
L'obiettivo finale diventa quindi la determinazione dei parametri ottimali di ogni
workstation tramite simulazione per poter garantire il soddisfacimento della domanda nel modo più efficiente possibile.
Tutte le informazioni riguardanti i parametri verranno inserite in input dall'utente, in
quanto si ipotizza di eseguire il set-up ex novo della linea, senza riutilizzare workstations già in azienda e per permettere una maggiore elasticità di applicazione del programma e rendere possibile la costruzione modulare di una linea ipotetica. 
La produzione si suppone essere, per amor di semplicità, lineare e “continua”, ovvero supponendo la continuità del servizio di forniture a monte della produzione e tenendo fuori dal computo delle possibilità eventuali scarsità di materiali, prefabbricati o consumabili, da imputare in questo caso a livelli di gestione più alti e non di competenza dell’applicazione o dell’utente.

**Comment by fulcorno** [comment]
Grazie per i chiarimenti sugli algoritmi.
Non mi è ancora del tutto chiara la ricorsione, che se ho ben capito dovrebbe provare ad assegnare tutte le combinazioni possibili di parametri alle Workstation (ma essendo parametri reali, le combinazioni non sono infinite?).

Nel frattempo hai trovato un data-set?

Se risolviamo questi due punti, per me va bene.

**Comment by FedericoManzetti** [comment]
Buongiorno professore,
Inizio col comunicarle che ho finalmente trovato un data-set adatto, riferito agli anni 2019-2021, mentre, per quanto riguarda la ricorsione, devo dire che mi sono spiegato male: la ricorsione viene richiamata alla fine del metodo ottimizza(), il quale prima preleva tutti i valori minimi dei parametri (che, specifico, non sono i tempi di lavorazione, nè il WIP o il throughput, ma sono i coefficienti di variabilità e i valori specifici delle casistiche di guasti, setup e rilavorazioni, valori con estremi solitamente compresi in poche unità) della linea da ottimizzare e poi li memorizza in una apposita list da passare al suddetto metodo. La ricorsione, dunque, non esamina tutte le combinazioni di valori continui dei parametri nel range di operatività, ma li esamina nel discreto con un incremento di 0.1, dal valore minimo fino a quello massimo previsti dal parametro, rimuovendolo poi dalla list temporanea dopo averlo testato; procedendo dal primo parametro di linea fino all'ultimo, incontriamo il punto di terminazione della ricorsione. Gli unici valori rilevanti nel computo dell'ottimizzazione, nonchè gli unici ad essere effettivamente calcolati durante le iterazioni del metodo, saranno l'utilizzazione media delle macchine (con opportuni controlli affinchè non sia troppo alta) ed i tre valori prestazionali della linea (TH, WIP e CT), opportunamente controllati come attributo del SimResult già all'interno del metodo da checkResult() per verificarne l'effettiva efficienza e per accertarsi che non ci siano blocchi pur avendo la massima utilizzazione possibile, in modo tale da arrivare poi a scremare l'OptimizationResult() finale restituito dal metodo ottimizza().
Nel caso avesse bisogno di ulteriori chiarimenti e/o precisazioni sono sempre disponibile.
La ringrazio dell'attenzione.

**Comment by fulcorno** [comment]
ok, grazie per le precisazioni, puoi procedere con il lavoro
