### ISSUE TITLE
Tool per job placement

### ISSUE THREAD

**Issue by GianmariaNavissano** [TdP-prove-finali/Introduzione#68]
### Studente proponente

s257883 Gianmaria Navissano

### Titolo della proposta

Tool per job placement

### Descrizione del problema proposto

L’applicazione intende offrire uno strumento che possa permettere ad un manager in cerca di nuovi impiegati di individuare quali università siano più indicate a fornire i candidati ideali, a seconda dei requisiti e delle competenze richiesti per ottenere la posizione.
La stessa applicazione, divisa in due parti, permetterebbe nella sezione dedicata agli studenti di individuare quali professioni sarebbero più adatte alla preparazione ed alle preferenze del giovane utente in cerca di lavoro.

### Descrizione della rilevanza gestionale del problema

La rilevanza gestionale del problema risiede nella reale necessità in cui può incorrere un ingegnere gestionale, alla ricerca della risorsa ideale per completare il suo team. Il problema descritto rappresenta una situazione che riguarda tutte le aziende, le quali in un certo momento della loro attività (certamente all’inizio, ma anche successivamente a fronte di crescite ed espansioni) si trovano in cerca di nuovi assunti ed hanno dunque bisogno di un criterio per selezionare i candidati. Logicamente nel caso in esame si considerano posizioni per le quali è solitamente richiesto un titolo di studio universitario.
Allo stesso modo degli studenti in procinto di terminare gli studi o recentemente laureati possono trovare in questa applicazione un ottimo strumento per individuare la professione più adatta a loro.

### Descrizione dei data-set per la valutazione	

Per quanto riguarda le università è stato individuato il sito https://www.topuniversities.com il quale offre un report annuale (dal 2018 al 2021) delle migliori università nel mondo secondo dei punteggi che tengono conto di diversi fattori quali il tasso di studenti esteri, la reputazione accademica, le citazioni per la facoltà, il tasso di assunzione. Tale report è reperibile presso Kaggle al link https://www.kaggle.com/divyansh22/qs-world-university-rankings?select=2020-QS-World-University-Rankings.csv

In merito alle professioni è invece presente presso Kaggle un dataset contenente offerte di lavoro da inizio luglio a fine agosto 2019 (per coerenza di periodo considerato si potrebbe utilizzare il ranking delle università relativo al medesimo anno) pubblicate sul sito Naukri. Tale dataset permetterebbe di individuare un grande numero di professioni con relative skills richieste, dettaglio della posizione offerta, esperienza richiesta e salario iniziale. In particolare è stato individuato il campo key_skills il quale fornisce un elenco di competenze richieste per ogni job e potrebbe servire per il calcolo della bontà del job nella fase algoritmica.

### Descrizione preliminare degli algoritmi coinvolti	

L’applicazione viene realizzata in linguaggio java con l’utilizzo dei pattern MVC (Model View Controller) e DAO (Data Access Object) in modo da risultare distinte le parti di codice relative ad interfaccia, logica applicativa ed accesso al database.
I principali algoritmi che verranno implementati saranno di tipo ricorsivo: l’obiettivo sarà quello di ottenere in output un elenco di università/professioni che soddisfi i vincoli in input, oltre ad un vincolo dimensionale (es. 5 elementi nella lista finale).
Il metodo ricorsivo utilizzerà un metodo (o più d’uno) apposito per il calcolo della bontà dell’elemento (università/professione) considerato in base ai valori di input e deciderà dunque se aggiungerlo o meno alla soluzione parziale. Una volta esplorate tutte le possibili combinazioni verrà restituita la lista con gli elementi che meglio soddisfano i vincoli.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione, come anticipato, sarà divisa in due sezioni separate: una dedicata ai professionisti in cerca di candidati per ricoprire una determinata posizione e l’altra per gli studenti che desiderano sapere quali professioni siano più adatte a loro.

I professionisti potranno inserire i livelli di competenze richieste per le diverse aree tematiche (competenze IT, artistiche, manageriali, ecc) utilizzando degli slider nell’interfaccia. Sarà anche possibile selezionare una lingua richiesta, così facendo verranno mostrate tra i risultati solo università situate in paesi dove si parla la lingua scelta. In alternativa da un menù a tendina sarà possibile selezionare una professione tra quelle proposte, in questo modo non sarà necessario dover specificare le singole competenze.
Il risultato della ricerca sarà un elenco di università, ordinate dalla più alla meno adatta, di dimensione fissa (es. 5 atenei) che corrispondono ai criteri di ricerca e rappresentano dunque i campus dove cercare il candidato ideale per la posizione offerta.

Gli studenti, nella sezione dedicata, avranno la possibilità di compilare il proprio Curriculum Vitae con il titolo di studio triennale e magistrale ottenuto, oltre alla propria “best skill”, ovvero una competenza padroneggiata ad alti livelli. Infine sarà possibile selezionare un ambito lavorativo di preferenza, il tutto attraverso l’utilizzo di menù a tendina e come ultimo dato di input sarà possibile selezionare un range di salario tramite uno slider.
Il risultato della ricerca sarà un elenco di professioni, ordinate dalla più alla meno adatta, di dimensione fissa (es 5 lavori) che corrispondono ai criteri di ricerca e rappresentano dunque le professioni per le quali lo studente sarebbe più portato e che dovrebbe dunque cercare di ricoprire.

**Comment by fulcorno** [comment]
Il problema è rilevante dal punto di vista gestionale. I data-set sono adeguati e gli algoritmi proposti soddisfano i requisiti del corso.
La proposta è accettata.
