### ISSUE TITLE
Applicazione per la creazione squadra Ultimate Team (FIFA)

### ISSUE THREAD

**Issue by Borghi98** [TdP-prove-finali/Introduzione#69]
### Studente proponente

s249465 Borgatta Davide

### Titolo della proposta

Applicazione per la creazione squadra Ultimate Team (FIFA)

### Descrizione del problema proposto

In FIFA, gioco di calcio per console, è usata da molti utenti la modalità Ultimate Team, in cui ogni utente deve creare la propria squadra ideale tramite i crediti, risorse virtuali a disposizione di ogni giocatore. I crediti vengono accumulati partecipando a varie competizioni ed è quindi fondamentale avere una squadra competitiva per poter ambire a vincere più crediti possibili e migliorare sempre la propria formazione. La creazione della squadra è sempre molto difficoltosa sia per i vincoli di budget sia per i vincoli di intesa tra i singoli giocatori. L’applicazione si pone l'obiettivo di aiutare l’utente nella creazione della miglior squadra possibile partendo da 4 giocatori scelti dall’utente e costruendo intorno a loro la squadra migliore possibile rispettando i vincoli imposti. Inoltre è importante che la squadra abbia un valore di intesa alto ed è quindi consigliato avere ogni giocatore con un minimo di intesa individuale pari a 7.

### Descrizione della rilevanza gestionale del problema

Nella modalità Ultimate Team esiste una competizione chiamata FUT Champions dove utenti di tutto il mondo si sfidano in 30 partite on-line e vincono premi in base al numero di vittorie conseguite. In questa modalità in cui si sfidano altri utenti è fondamentale avere una squadra competitiva e utilizzare al meglio i propri crediti per acquistare i giocatori giusti ed avere dei ricavi in termini di crediti. Di solito ogni utente ha in mente dei giocatori ideali senza i quali non può far a meno e perde molto tempo nel riuscire a trovare i restanti calciatori in modo da avere un valore di intesa alto e avere allo stesso tempo giocatori forti per cercare di vincere più partite possibili. Quindi il problema è di rilevanza manageriale in quanto con le risorse disponibili (crediti) bisogna riuscire a costruire la migliore squadra possibile, inoltre è fondamentale compiere questa operazione in un lasso di tempo ottimale.

### Descrizione dei data-set per la valutazione	

I dati relativi ai giocatori disponibili in FUT (Fifa ultimate team) derivano dal data-set al link:
https://www.kaggle.com/stefanoleone992/fifa-21-ultimate-team-players-and-prices-dataset?select=fut_bin21_players.csv
In questo data-set verranno considerati solo i giocati oro in quanto unici ad esser utilizzati nel gameplay, inoltre andrò ad estrarre gli attributi che serviranno alla risoluzione del problema:
- id : identificativo univoco di ogni giocatore su FUT
- nome : il nome, in gioco, del calciatore 
- rarita :  attributo che può avere due valori: raro o non raro
- overall : valore del giocatore 
- club : squadra dove il calciatore gioca 
- lega : campionato dove il calciatore gioca
- nazionalita : nazionalità del calciatore 
- posizione : ruolo in campo del calciatore 
- prezzo : prezzo del calciatore in crediti

### Descrizione preliminare degli algoritmi coinvolti	

Il programma riceve dall’utente: il modulo di 11 giocatori da usare, 4 giocatori scelti, il budget massimo da utilizzare e l’opzione se vuole solo giocatori rari. 
A questo punto verrà creato un grafo pesato e non orientato con 11 vertici (gli 11 giocatori) e archi che varieranno in base al modulo selezionato. Come primo passo verranno inseriti i 4 giocatori nelle rispettive posizioni e un controllo andrà a verificare che i giocatori inseriti rispettino i vincoli, se non ci saranno problemi allora inizierà un algoritmo ricorsivo che andrà a valutare le combinazione tra gli 11 giocatori e restituirà la migliore squadra che rispetti i vincoli. Una funzione calcolerà l’overall della squadra facendo la media tra l’overall degli 11 calciatori mentre un'altra funzione andrà a calcolare l’intesa della squadra facendo la somma tra l’intesa individuale degli undici giocatori (valore che può arrivare al massimo a 100). Questi 2 valori calcolati verranno sommati per valutare la squadra con il punteggio più alto (la migliore). 
I vincoli da rispettare sono : non superare il budget inserito dall’utente, non sostituire i 4 giocatori selezionati dall’utente e intesa di ogni giocatore almeno a 7.
L’intesa è un parametro che va a valutare le affinità tra i vari calciatori in rosa e varia da 0 a 10, un parametro molto importante in quanto con un valore inferiore a 7  le prestazioni del calciatore incomincerebbero a risentirne. 
L’intesa del giocatore viene calcolata in base al peso dei suoi archi ed ogni arco del grafo avrà un peso specifico in base a valutazioni di affinità dei calciatori valutata sui tre parametri : club, lega, nazionalità.
Tripla intesa, peso 2, giocatori che hanno in comune tutti e tre gli attributi.
Doppia intesa, peso 1, giocatori che hanno in comune due attributi mentre il terzo è differente.
Singola intesa, peso 0, giocatori che hanno in comune un unico attributo. 
Nessun intesa, peso -1, giocatori che hanno tutti e tre gli attributi differenti. 

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’utente come prima cosa andrà ad inserire il modulo della sua squadra ideale(selezionato tra varie opzioni), inserendo anche 4 giocatori da lui desiderati e il budget a sua disposizione per formare la squadra. A questo punto cliccando sul bottone verifica il programma andrà a controllare se vengono rispettati i vincoli di posizione (ad esempio non si possono scegliere 2 portieri inseriti dall’utente) e i vincoli di budget. Se questi vincolo sono rispettati allora verrà data conferma positiva con messaggio a video, inoltre verrà anche visualizzato il budget restante per gli altri 7 giocatori e l’invito a scegliere se si vuole solo giocatori rari. L’utente a questo punto potrà quindi scegliere di avere in rosa solo giocatori rari e con un altro bottone farà iniziare la ricorsione. Se la ricorsione è riuscita a trovare la squadra migliore allora verranno mostrati a video gli 11 giocatori, il valore complessivo di overall e l’intensa. Se la ricorsione ha avuto esito negativo il programma avviserà l’utente che non ha abbastanza crediti per costruire la squadra e lo inviterà ad aumentare il budget o a rinunciare a uno dei suoi 4 giocatori desiderati per far posto a un calciatore che costi meno.

**Comment by fulcorno** [comment]
Prima di entrare nel merito della proposta, vorrei capire se è analoga a quella già svolta da Alberto De Benedictis (vedi il progetto https://github.com/TdP-prove-finali/DeBenedictisAlberto).
Sarebbe opportuno non risolvere lo stesso problema (sono sicuro che con gli stessi dati si possono fare molte elaborazioni diverse).

**Comment by fulcorno** [comment]
ok, va bene, procedi pure con il progetto
