### ISSUE TITLE
Simulazione ed analisi progetto bag-sharing

### ISSUE THREAD

**Issue by simone-muraro** [TdP-prove-finali/Introduzione#70]
### Studente proponente

s259553

### Titolo della proposta

Simulazione ed analisi progetto bag-sharing

### Descrizione del problema proposto

Il Parlamento europeo e il Consiglio dell’Unione europea nel giugno 2019 hanno adottato la Direttiva sulla riduzione dell’incidenza di determinati prodotti di plastica sull’ambiente “Sup” (Single use plastics/plastica monouso) recepita dall’Italia con legge nazionale nell’aprile di quest’anno e in vigore da sabato 3 luglio 2021.
Il progetto bag sharing mira a risolvere il problema dei sacchetti di plastica monouso nella grande e media distribuzione, tramite dei sacchetti lavabili e riutilizzabili. Il programma, a partire dai dataset contenenti tutti i locali della grande e media distribuzione, crea un grafo e cerca il percorso migliore per il ritiro e la consegna dei sacchetti. Inoltre attraverso una simulazione si vuole stimare il consumo giornaliero di sacchetti, il possibile riutilizzo di parte di questi e se il progetto sia economicamente conveniente

### Descrizione della rilevanza gestionale del problema

Il primo problema affrontato è la scelta del luogo in cui situare i vari centri dell’azienda; tramite grafi per ogni provincia e la ricerca del cammino migliore si riesce a stimare con precisione l’ubicazione dei centri provinciali (che coincideranno con la posizione del supermercato di partenza nella soluzione del cammino migliore). Trovati i centri provinciali si può creare un grafo con essi e cercare il cammino migliore per decidere dove situare l’azienda a livello regionale.
Il secondo problema è un'analisi tramite una simulazione del progetto bag-sharing applicato alla realtà con l’obbiettivo finale di stimare delle variabili (costi/ricavi, fattibilità progetto, numero sacchetti totali) partendo da alcuni parametri (numero clienti giornalieri, media giorni ritorno al supermercato, costo sacchetti, costo lavaggio) alcuni settabili dall’utente, per simulare scenari diversi, altri fissi.

### Descrizione dei data-set per la valutazione	

Entrambi i dataset provengono dal portale OpenData offerto dalla regione Lombardia:
1)	Grandi Strutture di Vendita: https://www.dati.lombardia.it/Commercio/Grandi-Strutture-di-Vendita/haxp-4dkd  (creato nel 2012 ed aggiornato al 11 Giugno 2021). Il dataset è composto da una sola tabella con 479 righe (ogni riga per una specifica struttura di vendita) e da 15 colonne:
a.	ID_PDV: Identificativo
b.	Provincia: Nome Provincia
c.	ISTAT: Codifica ISTAT del Comune
d.	COMUNE: Nome del Comune
e.	TITOLARE: Insegna del titolare della Partita Iva dell'esercizio commerciale
f.	C.C.: Centro Commerciale; possibili valori:SI' / NO
g.	INDIRIZZO: Indirizzo dell'esercizio commerciale
h.	INSEGNA	
i.	Settoremerc.non alim. : Categorie per gli esercizi di tipo non alimentare; 
Possibili valori: A=ABBIGLIAMENTO E SCARPE; B=ELECTRONICS AUDIO, VIDEO E TV; C=MOBILI E ACCESSORI CASE ARREDO; D=SPORT, TEMPO LIBERO, BRICO, LIBRI E CLASSIFICAZIONI RESIDUALI (COMPRENDENTE ANCHE AUTO);	
j.	Sup.alim. : Superficie dedicata alla vendita di prodotti alimentari espressa in mq.	
k.	Sup.non alim. : Superficie dedicata alla vendita di prodotti NON alimentari espressa in mq.
l.	Sup.totale: Superficie totale dedicata alla vendita	
m.	geo_x: Coordinate espresse in Gradi rispetto al sistema di riferimento WGS_84
n.	geo_y: Coordinate espresse in Gradi rispetto al sistema di riferimento WGS_84
o.	location: Coordinate espresse in Gradi rispetto al sistema di riferimento WGS_84
2)	Medie Strutture di Vendita: https://www.dati.lombardia.it/Commercio/Medie-Strutture-di-Vendita/2si5-tumt (creato nel 2021 e aggiornato 11 Giugno 2021) 
Il dataset è composto da una sola tabella con 8.027 righe (una per ogni media struttura di vendita) e 14 colonne:
a.	ID_PDV Identificativo 
b.	ISTAT Codifica ISTAT del Comune 
c.	Comune Nome del Comune 
d.	Provincia Nome Provincia 
e.	C.C. Centro Commerciale;possibili valori:SI' / NO Indirizzo 
f.	Indirizzo dell'esercizio commerciale 
g.	Titolare Insegna del titolare della Partita Iva dell'esercizio commerciale 
h.	Settore merc. non alim. Categorie per gli esercizi di tipo non alimentare; possibili valori: A=ABBIGLIAMENTO E SCARPE; B=ELECTRONICS AUDIO, VIDEO E TV; C=MOBILI E ACCESSORI CASE ARREDO; D=SPORT, TEMPO LIBERO, BRICO, LIBRI E CLASSIFICAZIONI RESIDUALI (COMPRENDENTE ANCHE AUTO); 
i.	Sup.alim. Superficie dedicata alla vendita di prodotti alimentari espressa in mq. 
j.	Sup.non alim. Superficie dedicata alla vendita di prodotti NON alimentari espressa in mq. 
k.	Sup.totale Superficie totale dedicata alla vendita
l.	Lat Coordinate espresse in Gradi rispetto al sistema di riferimento WGS_84
m.	Lng Coordinate espresse in Gradi rispetto al sistema di riferimento WGS_84
n.	Location Coordinate espresse in Gradi rispetto al sistema di riferimento WGS_84

### Descrizione preliminare degli algoritmi coinvolti	

Per la prima parte (grafo-ricorsione):

- Query al database per salvarsi degli oggetti “supermercato”  
- Inserire gli oggetti “supermercato” come vertici di un grafo semplice pesato. 
- Calcolare distanze tra i vertici (tramite un algoritmo per le distanze tra due punti sulla superficie della terra passando come parametro il campo location dei due vertici che fornisce latitudine e longitudine)
- Inserire gli archi che collegano tutti i vertici con peso pari a quello calcolato nel punto precedente 
- Ricerca del percorso migliore (costo minimo) a partire da tutti i vertici del grafo attraverso un algoritmo ricorsivo 
- Ripetere per tutte le provincie trovando tutti i “centriProvinciali” (migliori supermercati per ubicazione nelle rispettive provincie)
- Costruire un grafo con vertici “centriProvinciali” e calcolare gli archi come le distanze tra essi 
- Ricerca percorso migliore tramite algoritmo ricorsivo

Per la seconda parte (simulazione): 
- Input: 
    	Parametri (inseribili dall’utente): costo sacchetti, tipo lavaggio, costo benzina/km), durata simulazione
-  Output: numero sacchetti utilizzati, costi e ricavi dell’intero processo
-  Descrizione degli eventi:
    	Giornata lavorativa supermercato (8h): per ogni supermercato simulo numero di sacchetti nuovi richiesti, numero di sacchetti restituiti e da lavare. Per ogni supermercato si otterranno numeri diversi in quanto la simulazione dipende da parametri (trovarsi in un centro commerciale, la superficie tot) e da percentuali (20% non richiede il sacchetto, 20%preferisce il sacchetto usa e getta,60% usa il nuovo sistema bag-sharing e di questi 20% è un cliente nuovo e 40% riporta un sacchetto per il lavaggio)
    	Ritiro sacchetti da lavare e consegna puliti: alla fine di ogni giornata bisogna ritirare i sacchetti da lavare e portare quelli puliti per il giorno successivo ad ogni supermercato. Per effettuare il ritiro/consegna si segue il percorso migliore calcolato dal grafo e si stimano i costi in base alla distanza percorsa e al costo del carburante inserito dall’utente 
    	Lavaggio: i sacchetti raccolti vanno lavati ma bisogna scartarne in media 2 su 100 perché troppo usurati. Vengono calcolati i costi in base alle scelte fatte dall’utente (lavaggio sharing, lavaggio tintoria)
- Durata della simulazione: variabile a scelta dell’utente. Si procede per giorni perché per ogni giorno ci devono essere tanti eventi “Giornata lavorativa supermercato” quanti supermercati presenti nella simulazione e ci devono infine essere un evento “ritiro/consegna” e un evento “lavaggio”

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione software consiste di due pagine: 

- La prima pagina è dedicata alla creazione del grafo e alla ricerca dei centri migliori. Verrà dotata di:
o	1 tendina per selezionare i dati delle Grandi strutture di vendita e/o delle Medie strutture di vendita
o	1 bottone e una tendina per scegliere una provincia e calcolare per essa la il miglior centro (stampa a video del miglior centro e del percorso ottimo per la provincia) 
o	1 bottone per calcolare tutti i centri provinciali (stampa video della lista dei centri provinciali)
o	1 bottone per trovare l’ubicazione aziendale a livello regionale (stampa a video dell’ubicazione aziendale e del percorso ottimo tra i vari centri provinciali)
o	Area di testo per stampare i valori 

- La seconda pagina è dedicata alla simulazione ed è composta da:
o	1 tendina per selezionare i dati delle Grandi strutture di vendita e/o delle Medie strutture di vendita
o	1 campo di testo per inserire il costo dei sacchetti 
o	1 campo di testo per inserire il prezzo attuale della benzina 
o	1 tendina a scelta per selezionare il tipo di lavaggio 
o	1 tendina per selezionare i numero di giorni della simulazione 
o	1 tendina per scegliere la provincia nella quale far partire la simulazione 
o	1 bottone per far partire la simulazione 
o	1 area di testo per stampare a video i risultati

**Comment by fulcorno** [comment]
Il problema è rilevante e gli algoritmi proposti sono adeguati. Probabilmente sarà necessario semplificare il problema (ad esempio filtrando la dimensione dei grafi) per fare sì che la ricorsione giunga a termine, oppure verificare se siano sufficienti algoritmi più semplici per il calcoli dei cammini minimi.
Con queste precisazioni, la proposta è approvata.
