### ISSUE TITLE
Tool per la gestione della Nazionale Italiana di calcio

### ISSUE THREAD

**Issue by iliaskhanani** [TdP-prove-finali/Introduzione#72]
### Studente proponente

S259842 Khanani Ilias

### Titolo della proposta

Tool per la gestione della Nazionale Italiana di calcio

### Descrizione del problema proposto

L’applicazione si propone l’obiettivo di aiutare l’allenatore della Nazionale Italiana di calcio a selezionare una rosa di calciatori da convocare per un raduno/amichevole. Il fine è quello di permettere all’allenatore di usufruire di uno strumento in grado di segnalare i calciatori più performanti.
Dopo aver selezionato la rosa, l’applicazione provvederà di fornire al mister, oltre gli undici titolari, i tiratori dei calci piazzati (rigoristi, calci d’angolo, calci di punizione).

### Descrizione della rilevanza gestionale del problema

L’introduzione della tecnologia nel calcio ha permesso di migliorare il ruolo dell’allenatore fornendogli una grandissima quantità di dati. 
Il problema che si vuole affrontare è rilevante dal punto di vista gestionale, in quanto la formazione, quindi l’ottimizzazione, della rosa è uno dei momenti più importanti e decisivi nel lavoro di un allenatore. L’obiettivo di questa applicazione è quello di suggerire i calciatori ottimali al fine creare una squadra competitiva e che rispetti i vincoli scelti dal mister (rosa giovane, solo giocatori di serie A, rosa più forte fisicamente/tecnica).
### Descrizione dei data-set per la valutazione	
Il data-set dal quale verranno prelevati i dati è il celebre video-gioco FIFA 2021, reperibile in rete sul sito www.kaggle.com.
Link data-set: https://www.kaggle.com/stefanoleone992/fifa-21-complete-player-dataset 
Il data-set contiene una tabella contenente tutti i calciatori presenti nel gioco (circa 19000) e oltre 100 colonne che forniscono informazioni esaustive per ognuno di essi.
Il formato del file trovato è CSV, quindi è necessario formattare e successivamente eliminare le informazioni non essenziali.
### Descrizione preliminare degli algoritmi coinvolti	
Una volta selezionata la rosa, l’applicazione si servirà della ricorsione per la ricerca degli undici titolari che soddisfano le richieste del mister, dopo aver settato i filtri del caso. 
L’applicazione, inoltre, con delle operazioni di ricerca genererà delle liste di calciatori per alcune funzionalità specifiche (capitano, rigoristi, calci piazzati, …).

### Descrizione preliminare delle funzionalità previste per l’applicazione software	
L’applicazione inizialmente consentirà all’allenatore di settare alcuni filtri per permettere la creazione della miglior rosa (più forte) in base alle caratteristiche chieste, per esempio giocatori giovani (sotto 25 anni), solo giocatori che militano in Serie A e tanto altro.
Successivamente il mister dovrà scegliere il modulo desiderato e le tattiche di gioco (offensivo/difensivo, fisicità/tecnica) e l’applicazione fornirà la miglior soluzione schierando gli undici titolari che più rispecchiano le caratteristiche scelte.
Un’altra sezione suggerirà all’allenatore, tra gli undici titolari, il calciatore più propenso a fare il capitano, i 5 rigoristi in caso di calci di rigore, il calciatore più preciso e quindi sarà colui che tirerà i calci piazzati.

**Comment by fulcorno** [comment]
Chiedo scusa per il prolungato silenzio, il semestre mi ha impegnato parecchio.
Ti chiederei se sei ancora interessato alla proposta, in modo da poterla definire con precisione e permetterti di iniziare.
