### ISSUE TITLE
Tool per il calcolo del tour ideale delle principali città italiane.

### ISSUE THREAD

**Issue by lorenzomelchionna** [TdP-prove-finali/Introduzione#73]
### Studente proponente

s258760 Melchionna Lorenzo

### Titolo della proposta

Tool per il calcolo del tour ideale delle principali città italiane.

### Descrizione del problema proposto

Il problema che si intende risolvere è il calcolo di un percorso turistico ideale, specificando città di partenza, numero e età dei partecipanti, interessi (gastronomia,
arte, sport, musica, movida, ecc...), tempo a disposizione per il viaggio, budget massimo di spesa. Si vuole quindi, dando l'opportuno peso ad ogni fattore relativo a
ciascuna città, in base alle preferenze dell'utente, calcolare l'itinerario che più si adatta ai turisti, tenendo conto del tempo a disposizione per la permanenza in 
Italia e non sforando il budget prefissato. 
La spesa verrà calcolata in relazione ai costi medi degli alloggi e delle attrazioni turistiche per il tempo che vi si trascorre, al costo medio per spostarsi tra le varie
tappe del tour.

### Descrizione della rilevanza gestionale del problema

L'applicazione proposta ha un rilevante interesse gestionale legato al settore turistico. Potrebbe infatti rappresentare un valido supporto per le agenzie di viaggi nel 
calcolo di un preventivo di spesa  per una proposta di vacanza per i propri clienti, e anche per un utente privato che vuole girare l'Italia e stimare i vari itinerari 
possibili in base a ciò che andrà a fare.

### Descrizione dei data-set per la valutazione	

L'idea consiste nel creare un database, in cui una tabella ha come chiave primaria una città e come attributi delle valutazioni (il più oggettive possibile, su dati reali) 
degli interessi accennati precedentemente, il costo medio dell’alloggio e delle attrazioni che si intende visitare, e un indicatore della quantità di attrazioni al fine di
stimare il tempo da trascorrere in un determinato luogo. Un'altra tabella, che rappresenta un collegamento tra 2 città, con il costo medio per spostarsi tra i 2 centri 
abitati per ciascun mezzo di trasporto (aereo,treno,auto).
Sui data-set non ho le idee molto chiare, non essendo riuscito a trovare online qualche spunto da cui partire; come soluzione potrei generare un database partendo da dati 
presi da varie fonti.

### Descrizione preliminare degli algoritmi coinvolti	

Si crea un grafo con delle città come vertici a partire dalle informazioni fornite dall'utente, escludendo le città con punteggio basso nelle aree di maggior interesse.
In seguito, partendo dalle informazioni fornite, ovvero budget e tempo a disposizione per il viaggio, si cerca tramite un algoritmo ricorsivo, utilizzando come parametro da
massimizzare un punteggio calcolato in base all'affinità della città con gli interessi selezionati, il percorso ideale in base alle preferenze e alle necessità di ciascun 
utente.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	
L'algoritmo si presenta all'utente tramite un’interfaccia grafica che innanzitutto mira a spiegare in sintesi le sue funzionalità.
In seguito permetterà all'utente di selezionare (ad esempio su una scala da 1 a 5) il grado di interesse dell'utente per ciascun aspetto (gastronomia, arte, sport, musica, 
movida, ecc..) e a seconda di ciò stampa a video una lista di città potenzialmente interessanti per l'utente, escludendo quelle che non presentano attrazioni per gli 
interessi principali.
In seguito, sarà possibile selezionare altri parametri: budget a disposizione, tempo da trascorrere in Italia e  numero di persone in viaggio.
Se disponibile, verrà stampato il percorso ottimale per l'utente, indicando anche il mezzo migliore per spostarsi da una città all'altra (aereo,treno,auto), altrimenti 
verranno notificate le insufficienze riscontrate ad esempio rispetto al budget  o al tempo a disposizione.

**Comment by fulcorno** [comment]
L'idea è adeguata e l'algoritmo è valido.
Mi preoccupa l'assenza di un data set, e non ritengo che crearne uno manualmente possa portare a risultati soddisfacenti.

Ti inviterei quindi a verificare se trovi delle fonti dati utili, altrimenti sarebbe meglio cambiare idea.

Visto il ritardo (mi scuso) con cui ti rispondo, non so se sei ancora interessato, per favore dammi conferma.
