### ISSUE TITLE
Studio sul tasso di abbandono in un azienda di servizi

### ISSUE THREAD

**Issue by Piovesale** [TdP-prove-finali/Introduzione#74]
### Studente proponente

s261458 Piovesan Alessandro

### Titolo della proposta

Studio sul tasso di abbandono in un azienda di servizi

### Descrizione del problema proposto

L'applicazione si pone l'obbiettivo di informare l'utente finale, i decison-makers di un'azienda di telecumnicazioni, sul tasso di abbandono dei consumatori ed i fattori che su di esso influiscono. Questo scopo è raggiunto in una prima parte mediante data visualization, esponendo le informazioni richieste con grafici e statistiche medie, ed in una seconda parte tramite una simulazione. In quest ultima l'utente potrà creare un gruppo eterogeneo di clienti fittizi (che tuttavia rispettino dei parametri come genere, tipo di abbonamento,fascia di età,servizi sottoscritti etc etc) e simulare il loro comportamento lungo un periodo temporale specificato, in modo da stimare in quanti rimarranno con la compagnia e quanto profitto potrebbero portare.  

### Descrizione della rilevanza gestionale del problema

In una società di servizi, in questo caso un azienda di telecomunicazioni, la retenzione dei clienti è fondamentale. Degli strumenti per capire ed interpetare il tasso di abbandono  del prodotto da parte dei consumatori possono essere molto utili all' area amministrativa. 

### Descrizione dei data-set per la valutazione	

Il data-set contiene 5 tabelle:

    Demographics: Dati rigurdanti ogni cliente come età,genere, numero di figli a carico etc.
    Location: Dati rigurdanti la città di residenza in California dell' utente.
    Population: Popolazione della città.
    Services: Servizi attivati dall'utente (linea internet, telefonia, supporto tecnico premium etc..), modalità di utilizzo della connessione internet (streaming serie o film, gioco online...) ed informazioni relative al pagamento.
    Status: Se e quando l'utente ha disdetto il contratto.

Informazioni dettagliate sono contenute alla pagina https://community.ibm.com/community/user/businessanalytics/blogs/steven-macko/2019/07/11/telco-customer-churn-1113

### Descrizione preliminare degli algoritmi coinvolti	

-Creazione di un cliente con caratteristiche randomiche o specificate dall' utente. 
-Calcolo della probabilità di abbandono mensile per ogni utente, a seconda del suo profilo e le sue caratteristiche. Nel database è già presente una colonna "Churn Score", la mia idea è quella di ricavare tramite una regressione lineare multipla dei coefficenti realistici che definiscano quanto un certo attributo influisca su questo punteggio, ed utilizzarlo poi come probabilità in percentuale di abbandono dell' utente x nel mese y.
-Simulazione. Ogni mese ogni utente del gruppo creato in precendenza avrà una possibilità (calcolata come sopra) di abbandonare il servizio. A seconda del tipo di abbonamento di ogni outente genererà profitti diversi per l'azienda. Alla fine della simulazione verranno raccolte statistiche come "tempo medio di permanenza nel contratto","spesa media","frequenza di abbandono".

### Descrizione preliminare delle funzionalità previste per l’applicazione software

L' UI sarà divisa in tre schede. La prima permette di recuperare e visualizzare informazioni cruciali sui clienti (tra cui genere, stato di residenza, servizi più utilizzati e spesa media mensile) o sul tasso di abbandono (come percentuale di clienti che hanno abbandonato e il servizio e le loro motivazioni).
La seconda scheda permette di creare degli utenti fittizzi indicandne caratteristiche come genere, età, servizi sottoscritti, modalità d'uso della connessione e tipo di pagamento. Questi attributi saranno gli stessi tramite cui verrà calcolata la probabilità percentuale di abbandono. Alternativamente sarà possibile generare utenti con attributi casuali.
La terza scheda permette di eseguire la simulazione vera e propria e ne mostra i risultati.

**Comment by fulcorno** [comment]
Scusa se rispondo solo adesso, spero che sia ancora interessato a svolgere il lavoro.

Ho rivisto la proposta e mi pare adeguata, quindi è approvata.

Dammi solo conferma se ti interessa ancora

**Comment by Piovesale** [comment]
> Scusa se rispondo solo adesso, spero che sia ancora interessato a svolgere il lavoro.
> 
> Ho rivisto la proposta e mi pare adeguata, quindi è approvata.
> 
> Dammi solo conferma se ti interessa ancora

Buongiorno, non sono più interessato al lavoro, la ringrazio per la risposta.
