### ISSUE TITLE
Applicazione per la valutazione e selezione della risorsa energetica idonea alla realizzazione di CER

### ISSUE THREAD

**Issue by RobertaDeSeriis** [TdP-prove-finali/Introduzione#76]
### Studente proponente

s261469 De Seriis Roberta

### Titolo della proposta

Applicazione per la valutazione e selezione della risorsa energetica idonea alla realizzazione di CER (Comunità energetiche rinnovabili).

### Descrizione del problema proposto

L’idea progettuale consiste nella realizzazione di un’applicazione JavaFX capace di analizzare dal punto di vista ambientale ed economico un dato territorio, in modo da definire l’impianto energetico capace di sfruttare al meglio le risorse naturali della zona di interesse.
Il programma riceve in input determinati parametri di analisi, tra cui: budget a disposizione, localizzazione territoriale, superficie disponibile, KWh richiesti; e restituisce la fonte rinnovabile che conviene utilizzare. L’output sarà generato valutando determinati parametri inerenti ai fattori ambientali ed economici e le fonti rinnovabili prese in considerazione saranno energia eolica e solare.

### Descrizione della rilevanza gestionale del problema

La nascita di nuove CER è un problema di rilevanza gestionale, affrontato con frequenza negli ultimi anni per favorire e accelerare il processo di transizione energetica. La CER si costituisce di un insieme di persone fisiche, giuridiche ed enti (privati, PMI, PA  ecc.) il cui scopo è produrre e condividere energia mediante impianti alimentati da fonti rinnovabili. 
Un’errata analisi economico-ambientale porta in genere ad investimenti in risorse inadatte al territorio di riferimento. Grazie all’analisi di fattori ambientali (stime mensili della ventosità e della radiazione solare) ed economici (costo di installazione, manutenzione e smaltimento), tale applicativo permette di individuare la risorsa maggiormente disponibile sul territorio, consigliando l’impianto da installare.

### Descrizione dei data-set per la valutazione	

La risoluzione di tale problema avviene attraverso l’utilizzo di tre data-set. Il primo fa riferito ai dati relativi all’energia solare: nome della città, irraggiamento mensile, ecc. Il secondo, invece, tratta l’energia eolica e, come nel caso precedente, troviamo l’elenco delle città associato alla ventosità mensile rilevata. L’ultimo data-set, infine, contiene stime di costi di installazione, mantenimento e smaltimento di entrambe le tipologie di impianto. 

### Descrizione preliminare degli algoritmi coinvolti	

Nell’applicazione saranno presenti algoritmi di ricerca, i quali si occuperanno di interrogare i database, cercando la città selezionata per recuperare i parametri necessari ai calcoli finali. Successivamente il programma svolgerà semplici operazioni matematiche per la generazione degli output richiesti. A questo punto verrà effettuata una selezione delle stampe necessarie e una produzione di grafici esemplificativi. 

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione si suddivide in tre sezioni: solare, eolico, confronto tra le due. 
Nelle prime due sezioni ci si pone come obiettivo il calcolo del costo di installazione o della quantità di KWh prodotti dall’impianto. Le due sezioni si differenziano per alcuni dati necessari per il calcolo finale e per i data-set a cui fanno riferimento. L’ultima sezione invece, confronta la produzione e il costo delle risorse descritte precedentemente restituendo quale delle due è più conveniente, da un punto di vista energetico ed economico. I dati comuni alle tre sezioni, necessari per la produzione dell’output sono: 

•	Luogo: inizialmente riferito ad una regione specifica, in particolare alle città con popolazione maggiore di (…)
•	Superficie disponibile [mq]
•	Budget 
•	KWh: richiesta annua di KWh

**Comment by fulcorno** [comment]
Il problema proposto è molto interessante ed anche originale rispetto ad altre proposte.

Nella descrizione, però, ci sarebbero due aspetti da migliorare:

1. specifica meglio se i data-set di cui parli sono già disponibili (ne conosci già la fonte?), quali aree geografiche coprono e con quale risoluzione, oppure se in qualche modo devono essere costruiti o ricavati da altri dati
2. la parte sugli algoritmi è molto superficiale: "semplici operazioni matematiche" non vuol dire nulla... Se si tratta solamente di calcolare un risultato con una formula nota a partire dai dati, allora ciò non è sufficiente ai fini della proposta. È necessario che la proposta comporti un algoritmo di ottimizzazione (ad es. ricorsivo) e/o un algoritmo di simulazione.

Attendo se possibile chiarimenti, soprattutto sul secondo punto

**Comment by RobertaDeSeriis** [comment]
La ringrazio per la risposta. 

Per quanto riguarda il punto 1, ci sto lavorando, per ora ho trovato un database dal sito ISTAT che contiene dati utili, a livello nazionale con risoluzione regionale. Il database include tutti i dati necessari  allo scopo dell'applicazione, esclusi quelli relativi all'aspetto economico (ricavabili dagli attuali costi sul mercato).
Sto effettuando ulteriori ricerche per restringere l'area geografica ad una sola regione con risoluzione provinciale. 

Sulla parte inerente al punto 2, l'algoritmo si occuperà di ricercare la soluzione più adatta, considerando: budget da investire per la realizzazione di CER e ulteriori parametri inseriti in input, mediante la ricorsione, sfruttando i parametri presenti nei dataset, individuerà la combinazione (risorsa+luoghi) che massimizza la produzione di energia generata dagli impianti eolici e/o solari. 
La proposta attualmente non riporta algoritmi di simulazione, in quanto non ho ancora ben chiara la funzione di quest'ultimi. Dopo aver affrontato l'argomento nelle prossime settimane, potrò se necessario aggiungerlo alle funzionalità dell'applicazione.

**Comment by fulcorno** [comment]
Va bene, con le precisazioni che hai fornito (che ti pregherei di inserire, aggiornando la proposta iniziale), il lavoro è accettabile. Se l'algoritmo contiene già la ricorsione, non è necessario a tutti i costi trovare delle funzionalità di simulazione.

**Comment by RobertaDeSeriis** [comment]
Ho apportato le modifiche nella proposta iniziale, come richiesto. Ho inoltre seguito la procedura per la richiesta di inizio prova finale sul Portale della Didattica.
