### ISSUE TITLE
Simulazione di un anno scolastico

### ISSUE THREAD

**Issue by LorenzoCanini5** [TdP-prove-finali/Introduzione#78]
### Studente proponente

s257620 Lorenzo Canini

### Titolo della proposta

Simulazione di un anno scolastico

### Descrizione del problema proposto

Il software ha come obiettivo quello di simulare l'andamento scolastico di tutti gli alunni all'interno di un'istituzione scolastica. 
I risultati ottenuti in seguito a questa ricostruzione saranno utilizzati dal programma per indicare all'utente la divisione ottimale del budget scolastico. Questo perché la scuola divide i fondi che ha a disposizione in base al numero di alunni che svolgeranno le diverse attività proposte come, per esempio, visite di istruzione, incontri con enti esterni, corsi di recupero e simili. 

### Descrizione della rilevanza gestionale del problema

Il software risulta utile dal punto di vista gestionale perché può essere utilizzato da qualsiasi istituzione scolastica a inizio anno per prevedere quale sarà il numero di alunni promossi, bocciati o rimandati. Questo permetterà alla scuola di scegliere in maniera più precisa quanto budget dedicare alle attività previste: un numero maggiore di rimandati porterà a stanziare più budget per i corsi di recupero, come un maggior numero di bocciati in quarta porterà a stanziare meno budget per il viaggio di istruzione delle quinte.

### Descrizione dei data-set per la valutazione	

Il software utilizzerà i data-set che l'istituzione scolastica mi ha fornito. Questi file xml, che convertirò in sql, contengono gli andamenti scolastici di tutti gli alunni degli ultimi 5 anni scolastici. All'interno di questi file è possibile trovare le medie di ogni alunno per tutte le materie, le ore di assenza, la media generale dei voti e l'esito degli scrutini (ammesso/non ammesso). Ovviamente tutti i dati sensibili (come nome e cognome) verranno censurati e sostituiti da numeri di matricola inventati, per tenere traccia degli studenti nei vari anni scolastici.     

### Descrizione preliminare degli algoritmi coinvolti	

Il programma conterrà algoritmi di simulazione per riprodurre il comportamento degli alunni lungo l'anno scolastico, questi permetteranno di vedere i voti che ogni alunno si ritroverà in pagella alla fine dell'anno e che decreteranno se lo studente è stato promosso, bocciato o rimandato.

Il programma utilizzerà anche algoritmi di ottimizzazione sia per l'ottimizzazione del numero di alunni in ogni classe, questo perché in seguito a un numero elevato di bocciature alcune classi potranno essere accorpate o smistate, a seconda del comportamento generale della classe, sia per quanto riguarda la divisione del budget, cercando di gestire i costi delle attività didattiche e distribuendo il budget in base alle necessità.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

Il software chiederà all'utente di inserire il numero di alunni iscritti al primo anno (questo numero cambia ogni anno e potrà essere inserito dal dirigente scolastico a inizio anno una volta ricevute le iscrizioni). Dopodiché partirà la simulazione. Una volta terminata sarà possibile visualizzare gli esiti di tutte le classi presenti nell'istituto e per ogni alunno saranno mostrate le medie di tutte le materie e l'esito degli scrutini.
Inoltre, sarà possibile visualizzare eventuali situazioni particolari, come per esempio una classe che deve essere smistata o due classi che dovranno essere accorpate. Sarà anche possibile decidere se memorizzare i dati ricevuti all'interno del data-set, questo permetterà di utilizzare questi dati per continuare le simulazioni seguenti.
Infine, sarà possibile visualizzare un resoconto con la suddivisione del budget, dove verranno mostrate le diverse parti di budget dedicate ad ogni tipo di attività.

**Comment by fulcorno** [comment]
Il problema è rilevante e gli algoritmi proposti sono adeguati.
L'unica preoccupazione è per la verosimiglianza dei risultati degli algoritmi si simulazione... immagino che si avvarranno di molti parametri, e non è chiaro come questi parametri verranno stimati (su base storica?).
In attesa di chiarimenti, comunque approvo la proposta.

**Comment by LorenzoCanini5** [comment]
Buongiorno,
i parametri per la simulazione pensavo di stimarli tenendo conto degli andamenti medi avuti dalle classi dello stesso anno negli anni scolastici precedenti, ma tenendo anche conto dell'andamento specifico di ogni studente nel corso degli anni. Per esempio, in ogni classe ci sono sempre studenti sopra o sotto la media, questo aumenterà la loro possibilità di ottenere voti più alti o più bassi, senza però esentarli dalla possibilità di ottenere risultati diametralmente opposti. Infine i risultati del singolo studente potranno cambiare a seconda della materia, visto che a volte gli alunni ottengono risultati migliori nelle materie che più interessano loro.
Tutte queste stime saranno fatte usando i tabelloni di fine anno di tutte le classi di tutti gli anni degli ultimi 5 anni scolastici, escludendo sicuramente quelli dell'a.s. 2019-2020 a causa dell'automatica promozione di tutti gli alunni. Inoltre, non sono sicuro sull'utilizzo dei dati dell'a.s scorso (2020-2021), a causa dell'alternanza tra Dad e lezioni in presenza che ha sicuramente falsato i risultati finali (se i dati non sono sufficienti è possibile utilizzare tabelloni ancora più vecchi).
Sperando di aver chiarito il suo dubbio, le auguro una buona giornata.

**Comment by fulcorno** [comment]
ok, va bene, grazie per il chiarimento
