### ISSUE TITLE
Gestione delle scorte di una libreria basata sulle preferenze degli utenti 

### ISSUE THREAD

**Issue by AlessandraSacco** [TdP-prove-finali/Introduzione#79]
### Studente proponente

s236623 Sacco Alessandra

### Titolo della proposta

Gestione delle scorte di una libreria basata sulle preferenze degli utenti 

### Descrizione del problema proposto

L'applicazione ha come obiettivo la simulazione della gestione dinamica delle scorte di una libreria. Le scorte saranno valutate in intervalli costanti di tempo, sulla base degli ultimi acquisti da parte degli utenti e delle recensioni. In particolare si vuole creare una lista di libri con maggiore probabilità di acquisto, poiché legati ai libri maggiormente venduti, tramite diversi parametri: genere, autore, lingua, editore o saga. Ogni intervallo di tempo questa lista verrà valutata con i nuovi acquisti e aggiornata sulla base di questi ultimi, con l'obiettivo di definire costantemente le scorte del magazzino della libreria sulla base delle preferenze degli utenti.

### Descrizione della rilevanza gestionale del problema

Organizzare dinamicamente le scorte sulla base degli interessi dei propri clienti è fondamentale dal punto di vista della gestione di un magazzino, per ottimizzare il processo di compravendita ed evitare la presenza di risorse superflue e non richieste all'interno del magazzino. La simulazione ha il compito di comprendere le variazioni nel tempo della domanda del pubblico e aggiornare conseguentemente l'offerta per soddisfare le richieste. 

### Descrizione dei data-set per la valutazione	

Per l'analisi e l'ottenimento dei dati, è disponibile il dataset Bookshop, scaricabile presso: https://help.tableau.com/current/pro/desktop/en-us/bookshop_data.htm.
I dati non sono reali ma realistici e sembrano fornire un buono schema per lo sviluppo dell'applicazione. 

### Descrizione preliminare degli algoritmi coinvolti	

Possiamo immaginare il dataset relativo ai libri come un grafo pesato non orientato, in cui i nodi sono i singoli libri, collegati tra loro tramite diversi parametri, accennati in precedenza: genere, autore, lingua, saga ecc...
Ogni libro sarà collegato con un altro che possiede in comune uno di questi parametri. Ovviamente ognuno di questi parametri influenzerà sul peso dell'arco in maniera diversa: per esempio la saga che accomuna due libri ha un'importanza maggiore rispetto alla lingua o all'autore.
Dal grafo si vuole ottenere una lista di libri potenzialmente acquistabili sulla base degli ultimi libri venduti: questa lista conterrà, infatti, i libri connessi a quelli più venduti con un peso maggiore.
La lista di libri determinerà le future ordinazioni del magazzino. Questa sarà aggiornata con la lista del precedente periodo di analisi e ordinazione, in modo da determinare le differenze (negative o positive) rispetto alle scorte già presenti in magazzino, in modo da ottimizzare le future scorte sulla base degli acquisti dei clienti.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente potrà selezionare un periodo di analisi, o una quantità di libri sulla quale generare la lista di nuove ordinazioni.
Potrà determinare una soglia minima di valutazione da considerare per le recensioni, in modo da ignorare o comprendere alcuni libri nella ricerca, e potrà scegliere se considerare o meno alcuni parametri che influenzano il peso degli archi.
Potrà indicare un numero massimo di ordinazioni, che potrebbe dipendere dalle dimensioni del magazzino.
Infine ci sarà un bottone per la simulazione di un periodo di vendita per la generazione della successiva lista di libri potenzialmente acquistabili.

**Comment by fulcorno** [comment]
Il problema proposto è interessante e rilevante.
Ho un paio di dubbi relativi agli algoritmi proposti.

Il primo algoritmo (libri potenziamente acquistabili) mi pare abbastanza "banale", basterà fare un ordinamento di tutti i libri sulla base di un valore pari a somma(libri simili venduti * peso dell'arco). Non ci vedo algoritmi di ottimizzazione, sembra un semplice ranking. 

Il secondo algoritmo è un po' slegato dal primo (introduce il concetto di giacenze, ed anche le vendite nell'unità di tempo. Una volta introdotte queste, anche qui l'algoritmo si riduce ad una somma algebrica.

Ti chiederei di cercare di focalizzare meglio il problema, magari restringendolo su un aspetto più specifico, che però comporti degli algoritmi maggiormente complessi.

**Comment by fulcorno** [comment]
Alessandra, intendi ancora lavorare su questa proposta o la consideriamo abbandonata?

**Comment by AlessandraSacco** [comment]
Salve professore,
Vorrei lavorarci ancora, mi scusi per l'attesa nella risposta ma dato 
che la sessione di esami sta per iniziare non sono riuscita ancora a 
trovare una soluzione al problema da lei posto nella tesi.
Mi scusi ancora, spero che non ci siano problemi.

Cordiali saluti
Sacco Alessandra

**Comment by fulcorno** [comment]
Ok, va bene, per semplicità di gestione preferisco indicare come "abbandonata" questa proposta, in modo che quando riprenderai a lavorarci potrai aprire una nuova richiesta con l'idea rielaborata.
