### ISSUE TITLE
Carta dei Servizi per le Imprese - Tesi in Azienda

### ISSUE THREAD

**Issue by AndreaAvidano** [TdP-prove-finali/Introduzione#8]
### Studente proponente

s193565 Andrea Avidano

### Titolo della proposta

Carta dei Servizi per le Imprese - Tesi in Azienda

### Descrizione del problema proposto

L'azienda dove lavoro sta concludendo un accordo con vari fornitori di consulenza (estero, produzione, fiscalità), tra cui anche il Politecnico di Torino: nello specifico è prevista una collaborazione con l'ateneo al fine di fornire consulenza a 360° alle PMI interessate al nuovo servizio (processi di produzione, consulenza dello specifico settore, gestionale, ...).
Le filiali dovranno poter inserire in un applicativo i dati dell'azienda e i servizi richiesti, la mia proposta è quella di affiancare la società IT chiamata per lo sviluppo.

### Descrizione della rilevanza gestionale del problema

Non essendo io dipendente della società IT adibita allo sviluppo del software ma della azienda committente, sarei il ponte di comunicazione tra le due e quindi saprei "parlare" entrambe le lingue (da un lato so cosa si sta facendo a livello informatico, dall'altro so dove si vuole arrivare una volta concluso l'applicativo)

### Descrizione dei data-set per la valutazione

I dati utilizzati saranno caricati man mano che i clienti richiedono il servizio

### Descrizione preliminare degli algoritmi coinvolti	

Non essendo io il progettista non ho idea degli algoritmi che si impiegheranno nella costruzione del software

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'utente che dovrà utilizzare il software sarà il collega in filiale. L'applicativo presumibilmente verrà inserito nella intranet aziendale: il collega entrerà nell'applicativo e in qualche maniera inserirà i dati dell'azienda (si gestiranno i casi di censimento già effettuato, ...) e modulerà il servizio sulla base delle richieste fatte dal cliente.

**Comment by fulcorno** [comment]
La struttura ed il contenuto di questa proposta non sono adatti alla "prova finale" per il corso di Tecniche di Programmazione.
