### ISSUE TITLE
Software per generazione automatica maratona cinematografica

### ISSUE THREAD

**Issue by Bigghe01** [TdP-prove-finali/Introduzione#81]
### Studente proponente

s269431 Grandi Emanuele

### Titolo della proposta

Sviluppo di un software per la generazione automatica di una maratona cinematografica

### Descrizione del problema proposto

L’obbiettivo del software è quello di permettere all’utente di generare automaticamente una maratona cinematografica, elaborata rispettando i vincoli dettati dall’utente stesso e comunicati al software mediante l’interfaccia applicativa.
In particolare, si intende fornire all’utente la possibilità di determinare una durata massima (in termini di minuti) della sequenza dei Film (vincolo di solito assente nella ricerca dei Film nelle piattaforme di streaming più utilizzate); i generi, gli attori e i registi privilegiati.
Sarà possibile, inoltre, definire un vincolo sulla valutazione media della critica e del pubblico nell’elaborazione della maratona desiderata.
Il software permetterà, per quanto riguarda le Serie Tv, di esprimere una preferenza per una determinata durata media degli episodi e un numero complessivo di stagioni.
Funzioni implementate saranno quelle di ricerca semplice (senza generare una maratona) di Film e Serie Tv (forniti i vincoli da parte dell’utente) e di aggiunta dei Film e Serie a una playlist personale “Guarda più tardi”, per tenere traccia dei titoli da vedere in un secondo momento.
### Descrizione della rilevanza gestionale del problema

Il software si focalizzerà, in primo luogo, su una globale ottimizzazione dei tempi.
L’utente, infatti, grazie al vincolo sulla durata massima dei Film, delle Serie e della maratona, potrà effettuare una ricerca su misura, in base al proprio programma giornaliero, al proprio tempo libero e in generale alle proprie esigenze in termini di tempistiche.
I titoli proposti dal software si incastreranno perfettamente nelle finestre temporali stabilite dal fruitore, evitando di dover interrompere e metà la visione di un film o di perdere tempo dietro a Serie Tv dagli episodi troppo lunghi.
Oltre a fornire informazioni generali sui titoli proposti, il software segnalerà all’utente la piattaforma di streaming in cui il titolo è attualmente disponibile (tra quelle più utilizzate), semplificando ulteriormente la ricerca.
Il processo di generazione della maratona cinematografica, infine, porterà chiaramente alla generazione di molteplici possibilità per l’utente, che potrà per esempio stabilire una valutazione minima o media (in termini di voto della critica e del pubblico) dei titoli che la compongono.
Tale ricerca dovrà quindi essere automatizzata e soprattutto ottimizzata.

 ### Descrizione dei data-set per la valutazione	

Il software si appoggerà a un data-set da me costruito ed elaborato a partire da alcuni data-set forniti dalla piattaforma Kaggle.
In particolare, utilizzerò i data-set che contengono informazioni su Film e Serie Tv presenti nelle principali piattaforme di streaming (Netflix, Disney +, Amazon Prime video), combinati con altri set di dati, per poter fornire all’utente informazioni sui titoli come: una breve descrizione del titolo, anno di uscita, ratings (dal Sito IMDb), informazioni sul genere e sul tipo di contenuti, le fondamentali informazioni sulla durata e la presenza o meno su una data piattaforma.

### Descrizione preliminare degli algoritmi coinvolti	
L’intero software sarà realizzato in linguaggio Java e le interfacce grafiche in Java Fx, utilizzando l’applicativo Scene Builder.
Per lo sviluppo dell’applicazione si seguirà il pattern MVC (Model View Controller) e il pattern DAO (Data Access Object). Grazie a questi pattern, è possibile mantenere distinte le tre parti fondamentali di un programma, ovvero la logica, l’accesso al database e l’interfaccia utente, che verranno sviluppate in tre packages diversi.

Il software lavorerà sul database costruito con l’obbiettivo di costruire una sequenza di titoli, vincolata alle preferenze dell’utente.
Per fare ciò si baserà su un algoritmo ricorsivo, che estrarrà tre le moltissime combinazioni fornite all’utente, un numero limitato di proposte, che dovranno essere ottimizzate sulla base della durata massima stabilita, della valutazione dei titoli richiesta dall’utente, del numero minimo di Film e Serie Tv (che comporranno la maratona) e su un serie di ulteriori parametri, che si potrà far variare a piacere (livello di humor nel Film, livello di violenza…).
La ricerca semplice di Film e Serie Tv si baserà invece su un algoritmo di ricerca e di interrogazione Sql del database.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’utente si troverà davanti a una serie di vincoli da determinare nella ricerca o nella generazione della maratona ad hoc.
Potrà digitare il nome di un regista o di un attore, scegliere il Paese in cui è stato prodotto il titolo, la durata (tramite una ComboBox), il numero minimo di titoli per la maratona.
Inoltre, potrà far variare a piacere (con dei cursori) alcuni parametri legati al tipo di contenuto dei titoli proposti, come il livello di violenza, paura, umorismo…
A questo punto l’utente si troverà di fronte a due Button, uno permetterà la ricerca semplice, l’altro genererà una o più maratone possibili.
Selezionando un titolo sarà possibile leggere una breve descrizione o una nota, se disponibile.
Solo dopo aver premuto uno dei due bottoni prima descritti, sarà possibile premere un terzo Button che permetterà di aggiungere uno o più titoli a una playlist personale “Guarda più Tardi”.

**Comment by fulcorno** [comment]
Il problema proposto è interessante, rilevante ed anche divertente.
Ho però due perplessità:
1. l'acquisizione dei data set necessari. Non so se i data set dei servizi di streaming siano così facilmente disponibili, e soprattutto se gli attributi di cui hai bisogno (livello di humor, violenza, horror, romance, ...) siano presenti in tali database. Escluderei l'opzione di aggiungere "a mano" tali informazioni, per ragioni di volume di dati, quindi ti chiederei preventivamente di verificare l'effettiva disponibilità delle informazioni che ti servono.
2. la complessità del processo di ottimizzazione: se parliamo di centinaia di film e centinaia di serie TV, non escluderei che un approccio ricorsivo risulti troppo lento rispetto ai tempi di risposta necessari. Teniamolo presente fin dall'inizio, pensando anche a "filtri" che possano permettere di ridurre la dimensione dello spazio di ricerca da esplorare.

Rimango in attesa di chiarimenti sul punto 1. (ovviamente il punto 2. si potrà vedere solo durante lo sviluppo)

**Comment by Bigghe01** [comment]
Salve Professore,
Per quanto riguarda il primo punto ero riuscito a trovare sempre sulla piattaforma Kaggle, un dataset Imdb di Film e Serie tv , che contiene per 4 parametri( nudità, violenza, paura, alcol) il "livello", da moderato a elevato.
L'idea era quella di combinare questo data-set con quelli dei servizi di streaming( ovviamente il data-set si ridurrà di dimensione, perché andrei a prendere solo i film e serie tv presenti nel primo dataset Imdb).
Nel caso poi diventasse complicato da implementare il meccanismo del "livello", nel data-set cercherò comunque di aggiungere l'informazione sulla classificazione dei contenuti dei titoli ( P-13,TV-14...), oltre a quella sul genere.

Riguardo la seconda perplessità, invece, seppur non avendo ancora fatto i conti con l'effettiva complessità dell'algoritmo, contavo, come accennato prima, di ridurre le dimensioni del dataset finale (dato che proviene dalla combinazione di più dataset), considerando anche i filtri.

Ovviamente se ha qualche suggerimento in questo senso, posso rivedere e modificare l'idea iniziale.

La ringrazio per il celere riscontro.

**Comment by fulcorno** [comment]
grazie per i chiarimenti, la proposta è accettata, con la raccomandazione sul fare molta attenzione alla congruenza dei dati raccolti ed alla complessità della ricerca.
