### ISSUE TITLE
Applicazione Java per il calcolo di un itinerario Interrail

### ISSUE THREAD

**Issue by filippoCaste** [TdP-prove-finali/Introduzione#83]
### Studente proponente

s270867 Castellarin Filippo

### Titolo della proposta

Applicazione Java per il calcolo di un itinerario Interrail

### Descrizione del problema proposto

 
 L'applicazione si propone di calcolare un itinerario percorribile in treno attraverso le stazioni delle citt&agrave; europee. Per fare ci&ograve;, &egrave; necessario l'inserimento da parte dell'utente dei propri interessi turistici, inteso come le proprie preferenze in termini di attivit&agrave; da svolgere durante un viaggio, da quale citt&agrave; desidera partire, e il numero di *'giorni di viaggio'* del biglietto Interrail da lui acquistato. 

 Per la definizione di 'giorni di viaggio' vedasi fondo pagina.

### Descrizione della rilevanza gestionale del problema

L'algoritmo tratta il calcolo di un itinerario turistico ottimale a partire dall'inserimento di semplici preferenze turistiche da parte del fruitore dell'applicazione. Per questo motivo, tale applicazione potrebbe risultare appropriata per tour operator e agenzie viaggi che si occupano nella definizione di itinerari turistici da vendere ai propri clienti. <br>Inoltre, l'applicazione in questione, potrebbe risultare utile anche ai fini del progetto Interrail stesso, in quanto potrebbe suggerire gi&agrave; in partenza un itinerario a coloro i quali sono interessati a viaggi di questo stile (che per&ograve; sono indecisi sui luoghi da visitare), e quindi permettere una maggior diffusione del progetto Interrail tra i cittadini europei.

### Descrizione dei data-set per la valutazione	

Le principali fonti di reperimento delle informazioni sono:
- Kaggle
- Eurostat
  
Al momento i database pi&ugrave; affini sono:
- https://ec.europa.eu/eurostat/databrowser/view/urb_ctour/default/table?lang=en ;
- https://www.kaggle.com/datasets/headsortails/train-stations-in-europe ;
  
**Nota:** per quanto riguarda il database sulle citt&agrave; europee, &egrave; abbastanza carente in termini di contenuti turistici (considera soltanto numero di visite musei, cinema, biblioteche e teatri), pertanto sto cercandone di pi&ugrave; completi.

### Descrizione preliminare degli algoritmi coinvolti	

**Opzione 1:** <br>
Come primo passo, tramite un algoritmo ricorsivo l'applicazione calcola quali sono le citt&agrave; pi&ugrave; affini agli interessi turistici del fruitore dell'applicazione tramite un processo di massimizzazione attribuendo ai vari indicatori un ordine decrescente (in questo caso all'utente sarebbe richiesto ordinare i criteri turistici). Questo primo passo, restituisce una lista (di dimensione massima pari (o pari al doppio) al numero di giorni di viaggio Interrail) di citt&agrave; ordinate in base agli interessi espressi.<br>
Successivamente, poich&eacute; il dataset che concerne le citt&agrave; europee contiene indicazioni circa la posizione geografica della citt&agrave;, potrebbe essere creato un grafo dove il peso degli archi corrisponde alla distanza calcolata tra le due citt&agrave; usando le informazioni di latitudine e longitudine. <br>L'obiettivo &egrave; quindi massimizzare il numero di vertici (citt&agrave; selezionate in base alle preferenze turistiche espresse) attraversate con la minor distanza percorsa e verificando sia sempre minore del numero di giorni di viaggio Interrail (&egrave; qui necessario supporre che in un 'giorno di viaggio' Interrail possono essere percorsi TOT numero di km poich&eacute; il database non contiene informazioni riguardo le connessioni ferroviarie tra le varie citt&agrave; fatta salva l'ipotesi di trovarne uno pi&ugrave; completo).

**Nota:** Questo punto potrebbe essere altres&igrave; svolto tramite algoritmo ricorsivo nel quale si va a minimizzare la distanza di percorrenza tra le citt&agrave;. 

**Opzione 2:** <br>
Se possibile, eseguire concettualmente lo stesso algoritmo di sopra ristretto a un singolo stato europeo nel quale le informazioni riguardo interconnessioni ferroviarie (con durata di percorrenza delle singole tratte) e dati derivanti dal turismo nelle varie citt&agrave;, siano presenti in maniera pi&ugrave; accurata.

**Nota:** Interrail offre anche la possibilit&agrave; di fare un viaggio Interrail all'interno di uno stesso paese. Clicca <a href="https://www.interrail.eu/it/interrail-passes>"> qui</a> per maggiori informazioni riguardo le offerte di viaggio Interrail.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

All'avvio dell'applicazione, l'utente si trover&agrave; una serie di campi a scelta (*ComboBox*) che &egrave; tenuto a completare per procedere al calcolo dell'itinerario. <br> In particolare dovr&agrave; scegliere:
1. Quali sono i suoi interessi turistici in base a quelli contenuti nella *ComboBox* (in base al database, ed eventualmente ordinarli in base alle proprie preferenze);
2. Quale &egrave; la citt&agrave; di origine (ed eventualmente una di destinazione);
3. Quanti *giorni di viaggio* Interrail possiede il suo biglietto.

Dopodich&eacute;, vi sar&agrave; un Button 'Calcola itinerario' che non appena premuto, avvier&agrave; gli algoritmi di cui al punto precedente per il calcolo del percorso migliore in base alle preferenze selezionate dall'utente tramite interfaccia grafica.

<hr>

Giorno di viaggio Interrail, dal sito ufficiale <a href="https://www.interrail.eu/it/support/interested-in-interrailing/what-is-a-travel-day"> Interrail</a>:
 <br>Un giorno di viaggio equivale a un periodo di 24 ore in cui puoi viaggiare in treno con il tuo Interrail Pass e va dalle 00:00 (mezzanotte) alle 23:59 dello stesso giorno di calendario. In ciascun giorno di viaggio puoi accedere alle reti ferroviarie di validità del tuo Interrail Pass.

<hr>
 <footer>
<p> Autore: Filippo Castellarin < s270867@studenti.polito.it ></p>
 </footer>

**Comment by filippoCaste** [comment]
## Aggiornamento 28 maggio:
### Database
Il database concernente le città tratto dal sito di eurostat è stato aggiornato e sono presenti alcuni indicatori in più, per cui dovrebbe risultare sufficiente per l'obiettivo dell'applicazione java in questione.

Ciò implica che è possibile procedere con il calcolo dell'itinerario a livello internazionale, entro i confini europei, senza la necessità di restringersi a un solo paese.

### Algoritmo
Per quanto riguarda la parte **algoritmica**, in particolare per il calcolo della distanza tra le varie città, mi avvarrei della libreria LatLng (vista anche a lezione), tenendo viva, se d'accordo, l'ipotesi riguardo il poter percorrere *TOT* km all'interno di un giorno di viaggio.
Per calcolare il percorso, prevedo la costruzione di un grafo nel quale i vertici sono le città potenzialmente interessanti per il fruitore (calcolate al passo 1 con previo inserimento degli interessi da parte dell'utente), e il peso tra di esse è la distanza calcolata come specificato.

**Comment by fulcorno** [comment]
La proposta mi pare adeguata e rilevante.
Direi di concentrarsi sul percorso europeo (e tralasciare quello nazionale).
Riguardo all'algoritmo, mi sembra controproducente selezionare PRIMA un set di città e poi selezionare un percorso breve tra di esse, quindi cercare di affrontare il problema in un'unica passata di ottimizzazione.
Con queste precisazioni, la proposta è approvata.
