### ISSUE TITLE
Software gestionale per ufficio acquisti

### ISSUE THREAD

**Issue by MauroCaradonna** [TdP-prove-finali/Introduzione#86]
### Studente proponente

s268974 Mauro Caradonna

### Titolo della proposta

Software gestionale per ufficio acquisti

### Descrizione del problema proposto

Il software ha come obiettivo quello di misurare le performance dell'ufficio acquisti e simulare il costo finale di un prodotto finito
composto da più articoli acquistati. Le performance saranno misurate sulla base di parametri che si basano sullo scostamento del prezzo di acquisto dell'anno in esame rispetto al prezzo dell'anno precedente . I risultati saranno calcolati sia per buyer, sia per 
sedi aziendali, sia per categorie di prodotti. L'utente potrà caricare tramite file i nuovi ordini, per i quali verrà stampata l'analisi della varianza dei costi. Inoltre intendo simulare il ciclo di vita degli articoli per un'azienda, da quando dovranno essere acquistati a quando sarà venduto il prodotto finito finale che li contiene. Una serie di eventi specifici potranno avvenire per i singoli articoli e ciò avrà influenza sul prezzo finale del prodotto.

### Descrizione della rilevanza gestionale del problema

Sto svolgendo il tirocinio presso un ufficio acquisti di una multinazionale e so che uno strumento di questo tipo è fondamentale per il 
management di una media/grande azienda per supportare le decisioni manageriali e per tenere sotto controllo le performance dei dipendenti. Inoltre all'ufficio acquisti viene richiesto di prevedere il prezzo dei materiali dei prodotti venduti e in un periodo di crisi di 
approvvigionamento come quello attuale e lead-time lungo risulta utile avere una simulazione di possibili scenari che potrebbero accadere.

### Descrizione dei data-set per la valutazione	

Come data-set intendo usare i dati dell'azienda presso la quale sto svolgendo il tirocinio, eventualmente cambiando alcuni valori.
In particolare userò dei data-set per i buyer aziendali, gli articoli acquistati, gli ordini, le fatture, fornitori e distinte base.

### Descrizione preliminare degli algoritmi coinvolti	
All'avvio il programma calcolerà una serie di parametri tramite un algoritmo sia per l'anno da analizzare, sia per l'anno precedente.
Questi parametri saranno memorizzati in un'opportuna struttura dati per poter essere disponibili per essere visualizzati e
per essere elaborati successivamente. All'inserimento di nuovi ordini saranno ricalcolati tutti i parametri e gli ordini saranno 
memorizzati nel database. Sulla base dei dati in possesso del modello e dai parametri inseriti dall'utente il programma userà algoritmi di simulazione per calcolare il costo di un prodotto finito, tenendo in considerazione alcuni eventi che possono accadere durante il lead-time.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'idea è quella di permettere all'utente di ricevere i risultati in scene differenti.
In una scena l'utente potrà visualizzare i valori sugli andamenti dei prezzi d'acquisto degli articoli. Da comboBox potrà scegliere se
visualizzare le performance per ciascun dipendente, per sede aziendale, per articolo o per commodity. In un'altra scena l'utente potrà inserire da file .csv, che è facile ottenere da un foglio di lavoro Excel, i nuovi ordini fatti e per quegli articoli visualizzare l'analisi della cost variance. Infine in un'altra scena l'utente può impostare alcuni parametri, scegliere un prodotto finale da analizzare con la simulazione e in una textArea ricevere i risultati.

**Comment by fulcorno** [comment]
Il problema è certamente rilevante e ben definito, il fatto che lo stai trattando durante il tirocinio ti aiuterà certamente a definirne i confini e le specifiche.
La proposta è approvata.
Una raccomandazione: i data set dovranno fare parte del progetto consegnato, quindi verifica con l'azienda se li puoi ridistribuire, o in alternativa se ne puoi proporre una versione anonimizzata.
