### ISSUE TITLE
“PlanURTour” Tour personalizzati nel National Gallery of Art di Washington D.C.

### ISSUE THREAD

**Issue by FMSDanna** [TdP-prove-finali/Introduzione#89]
### Studente proponente

s275791 D'Anna Filippo Maria Simone

### Titolo della proposta

“Plan Your Tour”
Tour personalizzati nel National Gallery of Art di Washington D.C.

### Descrizione del problema proposto

Il software proposto sarà in grado di pianificare dei tour all’interno del museo, proponendo una lista ordinata di opere da osservare al suo interno e tenendo in considerazione le preferenze dell’utente che usufruirà dell’applicazione. 
Quest’ultima si appoggia a un database che permetterà di massimizzare la rilevanza delle opere o di minimizzare la durata della visita cercando di scegliere il percorso che comporta il minor numero di spostamenti da una stanza all’altra. 
I clienti potranno scegliere di filtrare la ricerca in funzione di :
- Autore/Autori o Proprietari/Donatori
-Periodo Storico
-Genere
-Dimensioni
-Età dell’artista
Le visite possono riguardare gruppi da 1 a 15 clienti e ciascun gruppo sarà associato al relativo tour. 
Inoltre sarà messa a disposizione dei gestori del museo una sezione in grado di simulare una giornata nel museo che terrà conto dei tour personalizzati creati in precedenza. In questo modo sarà possibile osservare l’andamento giornaliero del museo e l’occupazione delle singole stanze nei vari momenti della giornata, valutando se sarà necessario aumentare la sicurezza in determinati settori e se la capienza delle varie stanze verrà rispettata non creando malcontento nei clienti (o altri possibili controlli).

### Descrizione della rilevanza gestionale del problema

Utilizzando questo software il museo potrà fornire ai clienti un’esperienza personalizzata e adatta agli interessi degli acquirenti con la possibilità di generare una maggiore affluenza. 
Inoltre il software può essere applicato a qualsiasi museo che sia in grado di fornire un database adatto e la sezione di simulazione può essere ampliata con ulteriori controlli a seconda dei risultati d’interesse (prezzi dei singoli tour, guide disponibili, promozioni etc.).

### Descrizione dei data-set per la valutazione	

Il programma utilizza il database fornito dal NGoA che contiene 130.000 + opere, nonché informazioni sull’artista, sul periodo e la loro posizione nel museo (relativa alle due costruzioni principali : ala est e ala ovest, alla stanza e alla posizione all’interno della suddetta).
https://github.com/NationalGalleryOfArt/opendata

### Descrizione preliminare degli algoritmi coinvolti	

Da un punto di vista algoritmico la prima parte del software riguarda la costruzione di un grafo che metta in relazione le singole opere in funzione dell’interesse del cliente. A seconda delle preferenze l’applicazione restituirà una lista di opere, che in questo programma rappresentano i nodi del grafo, nell’ordine in cui essere dovranno essere visitate per mantenere la sequenza ottima (ottenuta tramite algoritmo ricorsivo) .
La seconda parte svolgerà invece una simulazione che tiene conto delle visite prenotate dai clienti e del numero di persone in ciascun gruppo al fine di valutare l’affluenza del museo. 
Potrebbe essere implementata un’opzione che permetta di generare casualmente N visite con determinati parametri limite per diverse possibilità di analisi.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

Il software sarà utilizzato dai dipendenti del museo o dai clienti che potranno modificare i parametri di interesse nell’interfaccia.
L’utente potrà innanzitutto scegliere la dimensione del gruppo che intende visitare il museo con un minimo di 1 a un massimo di 20  (numero modificabile a seconda dei risultati ottenuti dalle simulazioni).
In seguito all’utente sarà chiesto di inserire determinati filtri sulle opere da visitare: 
- Autore/Autori o Proprietari/Donatori
-Periodo Storico
-Genere
-Dimensioni minime e massime
-Età dell’artista
… 
Elementi che saranno importati sul controller tramite database e saranno disponibili all’interno di combo box. 
Infine alla pressione del bottone ‘Calcola Tour’ il programma restituirà il totale di opere da visitare, la lista di quest’ultime , accompagnate dalla stanza in cui esse si trovano.
Per quanto riguarda la parte di simulazione, l’utente potrà visualizzare il numero totale di tour prenotati e il totale di clienti sommando i componenti dei singoli gruppi; potrà modificare la capienza massima totale delle stanze e scegliere se avviare una simulazione per i gruppi coinvolti o se generare altre visite con parametri casuali. 
Al termine della simulazione apparirà a schermo  una lista di stanze che in un determinato momento della giornata ha avuto un’affluenza maggiore rispetto a quella scelta e se gli addetti alla sicurezza disponibili possono essere in grado di coprire i settori richiesti. Nel caso di eccessiva affluenza i clienti potrebbero mostrare malcontento sulla base di un parametro generato casualmente tra 0.1 e 1.0 che indica la probabilità di essere insoddisfatto entrando in una stanza piena. 
Altri controlli possono essere aggiunti.

**Comment by fulcorno** [comment]
La proposta è interessante e l'argomento è rilevante.
Mi sembra però che possa essere un po' troppo ampio, visto che si propone sia un algoritmo di ottimizzazione sia uno di simulazione (è sufficiente uno dei due ai fini della prova finale). In particolare, l'algoritmo di simulazione si dovrebbe basare sui risultati di una serie di ottimizzazioni precedenti (quali? tutte? memorizzate nel DB?).

La proposta è accettata, con la raccomandazione di concentrarsi prioritariamente su una delle due parti proposte.
