### ISSUE TITLE
Simulazione di una stagione di Champions League, calcolo dei guadagni e delle percentuale media di capienza dello stadio

### ISSUE THREAD

**Issue by NicooFiore** [TdP-prove-finali/Introduzione#90]
### Studente proponente

s273552 Fiore Nicolò Antonio

### Titolo della proposta

Simulazione di una stagione di Champions League, calcolo dei guadagni e delle percentuale media di capienza dello stadio

### Descrizione del problema proposto

Il primo problema da risolvere è la creazione di un calendario che secondo le nuove modalità della Champions League dal 2024 sarà a girone unico a 36 squadre. La particolarità è che non tutte le squadre si sfideranno tra di loro, in particolare le 36 squadre saranno divise in 4 fasce da 9 squadre, ogni squadra affronterà 2 squadre appartenenti alle 4 diverse fasce. Alla fine di tutte le partite del girone le prime 8 squadre passano agli ottavi mentre dalla nona alla 24esima si sfideranno in un play off.
Il secondo problema è la simulazione delle partite per decretare un risultato per ogni match disputato. I risultati delle partite servono per stabilire la classifica del girone o il passaggio del turno, i risultati influiscono anche sui guadagni e sulla capienza dello stadio.

### Descrizione della rilevanza gestionale del problema

Dal punto di vista gestionale la rilevanza sta nella creazione del calendario che dovrà essere equilibrato in modo da avere partite di un certo spessore(sfide tra squadre di un certo livello di ranking)in ogni turno , evitando che queste si concentrino tutte nella stessa giornata. Inoltre è importante avere una stima dei guadagni che una squadra potrà ottenere in base ai risultati ottenuti nella competizione.

### Descrizione dei data-set per la valutazione	
I data-set per la valutazione saranno tre.
Il primo è rappresentato dalla tabella ranking(sito di riferimento https://it.uefa.com/) in questo data set è presente la posizione in classifica del ranking UEFA ,il nome della squadra, la sigla della federazione nazionale di cui fa parte la squadra, i punti ottenuti nelle ultime 5 stagioni, la somma totale dei punti ,e infine il punteggio della federazione di riferimento.
Il secondo include le 36 squadre qualificate alla Champions League in questa tabella è presente : nome della squadra, campionato di appartenenza, nome dello stadio, 4 caratteristiche sulla squadra espresse in numeri interi che indicano la "forza" della squadra e infine la fascia in cui è inserita la squadra.
L'ultimo data set riguarda gli stadi per ogni riga sono presenti il nome della squadra, la capienza, la città e l'anno di costruzione

Identificare le fonti dalle quali verranno tratti i dati utilizzati
https://it.uefa.com
https://sofifa.com/teams
https://it.wikipedia.org

### Descrizione preliminare degli algoritmi coinvolti	
I principali algoritmo saranno:
-un algoritmo di ottimizzazione del calendario per renderlo il più equilibrato possibile, secondo le condizioni indicate in precedenza (squadre di 
 fasce diverse si sfidino in egual modo, e che non tutte le partite di cartello avvengano nello stesso turno).
-un algoritmo che svilupperà la simulazione dei match e quindi i risultati che andranno a comporre la classifica
- un secondo algoritmo che svilupperà la simulazione delle diverse condizioni di capienza dello stadio e di costo dei biglietti, ad esempio per una partita di squadre di prima la fascia la capienza dello stadio con grande probabilità sarà al completo e avrà un costo alto del biglietto

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione sarà in grado  , tramite un’interfaccia dotata di bottoni, di permettere all’utente di sfruttare alcune funzionalità.
- “Crea Calendario Partite” crea il calendario delle partite del girone.
- “Simula Fase Girone” dopo la creazione delle sfide del girone sarà possibile simulare le partite del girone da cui si otterrà la classifica che verrà mostrata a video
- “Simula Fase eliminazione Diretta” crea gli accoppiamenti per la fase a eliminazione diretta e ne calcola il risultato ottenendo così il vincitore
Saranno poi a disposizioni altre funzionalità in grado di ricercare informazioni richieste dall’utente:
-Sarà possibile selezionare da un menù a tendina una squadra e tramite un bottone sarà possibile visualizzare tutti i risultati relativi a quella squadra con un messaggio che indica la posizione raggiunta(es: vincitore Competizione o eliminata agli Ottavi di finale)
- Sarà possibile selezionare da un altro menù un turno della competizione e sempre tramite bottone sarà possibile vedere tutti i risultati relativi a quel turno

**Comment by fulcorno** [comment]
Va bene, proposta approvata
