### ISSUE TITLE
Proposta di tesi - Molinatto Sylvie, matricola s271636

### ISSUE THREAD

**Issue by sylviemolinatto** [TdP-prove-finali/Introduzione#93]
### Studente proponente

s271636 Molinatto Sylvie

### Titolo della proposta

Tool per analisi del Gender Gap e simulazione ricerca di un team work

### Descrizione del problema proposto

La candidata propone di realizzare un tool che permetta di visualizzare in maniera semplice e immediata alcuni dati riguardanti la differenza di genere in alcuni settori lavorativi. In particolare il tool si propone di valutare la percentuale di rappresentanza femminile nei settori considerati (segregazione orizzontale), le differenze salariali di genere e altri fattori presi da un dataset. Inoltre l’applicazione ha l’ulteriore funzione di permettere all’utente di aprire delle candidature per determinate posizioni lavorative e ottenere il team work che rispetti maggiormente i requisiti richiesti. 

### Descrizione della rilevanza gestionale del problema

Poichè il tema del divario di genere è piuttosto dibattuto, la realizzazione di un tool che possa analizzare alcuni dati e mostrarne i risultati in maniera chiara e intuitiva risulta essere un modo pratico per diffondere consapevolezza della problematica esistente. 
Conseguentemente la possibilità di effettuare la ricerca di un team di lavoro in cui sia massimizzata la professionalità costituisce un’ulteriore fonte di analisi in termini di disparità di genere.

### Descrizione dei data-set per la valutazione	

Il data-set utilizzato è tratto da Kaggle al link https://www.kaggle.com/datasets/nilimajauhari/glassdoor-analyze-gender-pay-gap
Si tratta di una raccolta di dati relativi a utenti iscritti al sito web Glassdoor
nel quale gli impiegati e gli ex impiegati di un'azienda anonimamente recensiscono le aziende e i loro superiori. 
Il dataset contiene i seguenti attributi:
•	Id – attributo aggiunto 
•	JobTitle (Data Scientist, Driver, Financial Analyst, Graphic Designer, IT, Manager, Marketing Associate, Sales Associate, Software 
        Engineer, Warehouse Associate)
•	Gender (Male,Female)
•	Age
•	PerfEval (performance Evaluation Score)
•	Education (College, High School, Masters, PhD)
•	Dept (Department)
•	Seniority
•	BasePay (Annual Basic Pay in $)
•	Bonus (Annual Bonus Pay in $)
La dimensione del dataset è di 1000 righe di cui 532 riguardanti utenti di genere maschile e 468 di genere femminile.

### Descrizione preliminare degli algoritmi coinvolti	

Poiché il dataset è in formato CSV, come primo passaggio è necessario effettuare una conversione in linguaggio SQL. Al dataset viene aggiunto un attributo, nominato ‘id’, per distinguere i vari record. L’applicazione viene realizzata in linguaggio Java e segue i pattern MVC (Model View Controller) e DAO (Data Access Object) per ottenere separazione tra interfaccia utente, logica applicativa e accesso ai dati.

Successivamente per effettuare l’analisi relativa alla prima funzione del tool, è necessario creare i metodi che permettano all’utente di formulare le query per la rilevazione delle percentuali riguardanti un determinato settore lavorativo e generare i grafici per la visualizzazione dei risultati.

In seguito, per realizzare la funzione di ricerca di un team, si utilizzerà un algoritmo ricorsivo che permetterà di ottenere le specifiche richieste dall’utente tramite interfaccia congiuntamente alla massimizzazione degli altri attributi. Inoltre al termine della ricorsione verranno visualizzate alcune statistiche.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione prevede che l’utente possa scegliere un determinato settore lavorativo (attributo jobTitle), tramite menù a tendina, e cliccare un bottone ‘Analizza’ al fine di ottenere la percentuale di occupazione di genere nel settore e altri dati quali lo stipendio medio di genere, il bonus medio, il livello di istruzione e l’età media.
I risultati verranno mostrati in maniera chiara grazie all’utilizzo di grafici a torta e a barre.

Successivamente l’utente potrà decidere di aprire la candidatura a diverse posizioni lavorative per creare un team di lavoro e, per mezzo di un algoritmo ricorsivo, verrà costituito il team cercando di massimizzare la professionalità. A seguito della creazione del team si potrà visionare la percentuale di genere e ipotizzare se tale risultato sia influenzato o meno dalla segregazione verticale o orizzontale.

**Comment by fulcorno** [comment]
L'argomento è rilevante e molto interessante, oltre che originale.

La parte di 'Analizza' è abbastanza standard (semplici query e calcoli di medie), va bene ma non è la parte essenziale del lavoro.
Sulla parte successiva, quella della ricerca del team di lavoro, ci sono pochi dettagli, e non riesco bene a capire che tipo di ricerca intendi realizzare. 
Ti chiederei di aggiungere qualche dettaglio su come funziona la parte ricorsiva, in particolare specificando (almeno a grandi linee) quali informazioni deve specificare l'utente, e quali caratteristiche avrà il team 'ottimo' calcolato (sarà il nome di un'azienda? un elenco di persone? quale metrica viene massimizzata?).

**Comment by sylviemolinatto** [comment]
Per quanto riguarda la seconda parte l'idea era quella di permettere all'utente di scegliere, per ogni settore lavorativo, il numero di professionisti richiesti e successivamente calcolare, per mezzo di un algoritmo ricorsivo, il team work che massimizzi l'attributo 'perfEval'  ossia il punteggio attribuito alle performance del lavoratore. Poiché il numero di record in questo modo sarebbe piuttosto elevato e la ricorsione potrebbe risultare lunga probabilmente permetterò all'utente anche di specificare qualche altro attributo in modo da limitare il numero di record che partecipano all'algoritmo (per esempio l'attributo 'Seniority' o 'Education'). 
Inoltre avevo anche l'idea di permettere all'utente di specificare se volesse un team work con la stessa rappresentanza di genere e realizzare un ulteriore algoritmo ricorsivo che permetta di trovare il sottoinsieme di utenti che massimizzino 'perfEval' mantenendo equa la percentuale di genere.
Sarebbe interessante riuscire a vedere le differenze tra questi due algoritmi in termini di rappresentanza di genere e del performance evaluation score medio.

**Comment by fulcorno** [comment]
ok, ho capito. In effetti il confronto tra le due versioni (libera vs equigenere) dell'algoritmo mi pare interessante.
Approvo la proposta
