### ISSUE TITLE
Software per creare squadra ideale Euroleghe Fantacalcio

### ISSUE THREAD

**Issue by RiccardoViglione** [TdP-prove-finali/Introduzione#97]
### Studente proponente

S247607 Viglione Riccardo

### Titolo della proposta

Realizzazione software per creare squadra ideale per EuroLeghe Fantacalcio

### Descrizione del problema proposto

Il problema da risolvere è la costruzione di una squadra ideale del gioco EuroLeghe Fantacalcio. Il fantacalcio è un popolare gioco che consiste nel creare una squadra a piacere con giocatori reali e i risultati dipendono dalle prestazioni dei giocatori nelle partite reali. Euroleghe è una variante del normale fantacalcio in cui i giocatori vanno acquistati dalle migliori squadre dei 5 principali campionati Europei (Serie A, Ligue 1, Premier League, Bundesliga, Liga). L’applicazione ha come scopo quello di aiutare l’utente nella composizione della rosa a partire dal suo giocatore preferito in modo tale da avere una rosa efficiente. Inoltre, l’applicazione ha anche una seconda funzione che permette di trovare il giocatore migliore da acquistare nella sessione di mercato in base al budget disponibile e al ruolo in cui serve.

### Descrizione della rilevanza gestionale del problema

Euroleghe Fantacalcio è un gioco in cui bisogna andare a comporre la propria rosa tramite un Budget limitato che si ha disposizione considerando che i vari calciatori hanno prezzi diversi. A livello gestionale è dunque fondamentale saper gestire bene queste risorse per comporre una squadra competitiva nei vari ruoli e poter vincere la competizione.

### Descrizione dei data-set per la valutazione	

I dati vengono presi dal sito ufficiale di EuroLeghe Fantacalcio che  mette a disposizione un file xlsx con la lista dei giocatori e il loro prezzo(https://www.fantacalcio.it/quotazioni-fantacalcio-euro-leghe )  ed un secondo file che contiene invece le varie statistiche di tutti i giocatori presenti (https://www.fantacalcio.it/statistiche-euro-leghe ).

### Descrizione preliminare degli algoritmi coinvolti	

Per la creazione della rosa migliore dopo che utente ha selezionato il proprio giocatore preferito, viene utilizzato un algoritmo di ricorsione per ogni ruolo arrivando  al completamento della rosa migliore.
Per la lista dei migliori giocatori da acquistare in un determinato ruolo viene invece effettuata una semplice ricerca basata sui dati inseriti da utente 

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione sarà formata da due opzioni principali: la creazione di una rosa a partire dal proprio giocatore preferito e una lista dei migliori giocatori disponibili per il ruolo che viene selezionato e per il budget che si ha a disposizione (un’opzione utile per poter trovare in fase di mercato il giocatore migliore con cui sostituire un proprio giocatore).
Per la prima opzione L’Utente dovrà prima selezionare il proprio giocatore preferito: per farlo ci saranno due menù a tendina con cui selezionare squadra e posizione, una volta fatto un terzo menù a tendina si riempirà con i giocatori di quel ruolo e di quella squadra, tra i quali l’utente selezionerà il suo preferito. Una volta fatto questo l’utente inserirà i crediti a disposizione nell’asta e cliccherà sul bottone per avere la miglior combinazione di portieri, poi su quello per i difensori, quello dei centrocampisti e infine quello per gli attaccanti fino ad avere la squadra perfetta in base a budget inserito e giocatore preferito. Di volta in volta appariranno i giocatori del ruolo di cui si è premuto il bottone fino ad avere la squadra completa.
L’opzione per trovare il miglior giocatore da prendere nel mercato si basa semplicemente sullo scrivere il numero di crediti disponibili e ruolo in cui si vuole acquistare tramite menu a tendina e l’applicazione darà i migliori 5 giocatori in quel ruolo in base alla loro media voto, tra cui l’utente sceglierà chi vuole.

**Comment by fulcorno** [comment]
Ci sono già diverse proposte sul tema del Fantacalcio, potresti per favore visionarne le descrizioni, e dirmi che cosa ci sarebbe di diverso nella tua proposta?
Eventualmente, dovresti modificare la tua proposta in modo da renderla diversa da quelle esistenti.
Non sono un fan del fantacalcio, quindi le "sfumature" mi sfuggono, per questo ti chiederei di evidenziare e spiegare le specificità.

**Comment by RiccardoViglione** [comment]
Buongiorno, non sono più interessato al lavoro, la ringrazio per la risposta

**Comment by fulcorno** [comment]
Ok, grazie per la precisazione
