### ISSUE TITLE
Analisi e ottimizzazione di una linea di produzione industriale nel settore automotive

### ISSUE THREAD

**Issue by stefanobonazzi** [TdP-prove-finali/Introduzione#98]
### Studente proponente

s268576 Bonazzi Stefano

### Titolo della proposta

Analisi e ottimizzazione di una linea di produzione industriale nel settore automotive

### Descrizione del problema proposto

La linea di produzione di un’azienda, per ottenere la massima produttività, ha bisogno di una pianificazione puntuale e precisa della sua utilizzazione nell’arco del tempo. Interagendo con un’azienda locale ho riscontrato che la creazione di un software che permetta facilmente di modulare e analizzare la produzione ha un positivo incremento sulla produttività.

### Descrizione della rilevanza gestionale del problema

Ogni azienda che opera tramite una linea produttiva, in particolar modo se variabile, ha necessità di valutare l’impatto che questo lavoro avrà sull’intera linea. Un software che permetta di simulare in ogni momento la pianificazione ottimale di tutti gli ordini ancora non in fase di produzione sui diversi macchinari liberi permette di evitare sprechi o ritardi, avere costantemente una linea ottimizzata e quindi poter acquisire con più facilità ordini nuovi. Una linea ottimizzata farà risparmiare l’azienda e, non meno importante, avendo magari meno macchinari in funzione l’impatto ambientale sarà minore.

### Descrizione dei data-set per la valutazione	

I dati da me utilizzati mi sono stati forniti da una azienda locale che per motivi di privacy non verrà nominata e rappresentano una parte di storico degli ordini e della produzione. Il data-set è stato poi ordinato e adeguato da me tramite Excel eliminando eventuali dati sensibili e inserendo parametri realistici essenziali per la realizzazione del programma. Una prima tabella contiene gli ordini con data d’ordinazione, numero di pezzi, tonnellaggio che servirà per lavorare i pezzi e definire la pressa a cui assegnare la lavorazione, descrizione e codice del lotto. Una seconda tabella contiene le caratteristiche delle presse: numero, tonnellaggio massimo, tempo ciclo medio e tempo di setup. La terza tabella riporta le correlazioni tra ID di produzione e Lotto di produzione con eventuali altri lotti assegnati allo stesso prodotto. La quarta e ultima tabella contiene i dati della produzione: l’ID di produzione, le date di inizio e fine lavorazione e i rispettivi orari, il numero della pressa assegnata, le cavità del pezzo aperte e quelle che dovrebbero essere presenti, il tempo ciclo e il lotto di produzione.

### Descrizione preliminare degli algoritmi coinvolti	

Accesso tramite query e modifica del database.
L’analisi consisterà nella valutazione di ogni record estrapolando e ricavando dati di utilizzo.
Una ricorsione per ottimizzare la produzione ventura in base agli ordini già presenti e inseribili. Verranno valutate tutte le possibili combinazioni di organizzazione della produzione, date di avvio dei lavori in base al tonnellaggio consentito dalle presse, dai tempi di setup e tempo ciclo di ogni macchinario senza dimenticare il limite di tempo di evasione dell’ordine.
Simulazione di produzione in base ad una percentuale di incertezza che può inserire l’utente per quanto riguarda l’errore nella produzione del pezzo e i dati inseribili dall’utente quali presse aggiuntive e ordini immediati.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L'applicazione consisterà in un’interfaccia grafica con cui l’utente, dopo aver aggiunto in modo consono il database da cui prelevare i dati, analizzerà la produzione passata ricevendo in output il tempo ciclo medio per ogni pressa, l’utilizzazione percentuale dei macchinari e la percentuale di errore della produzione. Effettuata l’analisi il programma avrà acquisito e aggiunto i dati di utilizzo. L’interfaccia grafica consentirà quindi all’utente di inserire ordinazioni nuove con cui effettuare la ricorsione in cerca dell’ottimizzazione della produzione. I dati da inserire sono: la data dell’ordine, il numero di pezzi, il tonnellaggio e una descrizione. Il programma analizzerà tutte le possibili combinazioni e fornirà in output all’utente la programmazione dettagliata della produzione ottimale con dati importanti come l’utilizzazione delle presse percentuale. Da notare che il tempo massimo di evasione dell’ordine è di 21 giorni e si presuppone che la lavorazione avvenga in modo continuativo 24 ore al giorno tutti i giorni della settimana. L’ultima funzionalità del programma consiste in una simulazione che avrà come dati in input eventuali presse aggiuntive (tonnellaggio e tempo ciclo medio, il numero di pressa verrà assegnato automaticamente), ordini da evadere tempestivamente con i relativi dati come in precedenza e una percentuale di errore dei macchinari o possibilità di ordini improvvisi casuali. La simulazione come la ricorsione fornirà in output il resoconto della produzione pianificata e i dati di utilizzazione fornendo così all’utente la possibilità di analizzare il risultato e organizzare di conseguenza la propria produzione.

**Comment by fulcorno** [comment]
Il dominio applicativo è chiaro e pertinente e gli algoritmi proposti sono accettabili. La proposta è accettata

Punti di attenzione:
- Verificare che il numero di combinazioni da testare non sia eccessivo per l'algoritmo ricorsivo.
- Verificare che i data set su cui lavorerà il programma siano distribuibili liberamente (anonimizzati)
