### ISSUE TITLE
IoT & sorted waste: la transizione 4.0 di ASP e Comune di Asti

### ISSUE THREAD

**Issue by noemarchi** [TdP-prove-finali/Introduzione#99]
### Studente proponente

s272162 Marchiaro Noemi

### Titolo della proposta

IoT & sorted waste: la transizione 4.0 di ASP e Comune di Asti

### Descrizione del problema proposto

Asti Servizi Pubblici e Comune di Asti stanno lavorando a un progetto di raccolta rifiuti.
“Il nuovo metodo, che sostituirà il servizio di raccolta porta a porta, verrà attuato con il posizionamento di nuovi cassonetti per la raccolta differenziata, raggruppati in ecoisole.
Tali contenitori saranno dotati anche di un sensore in grado di rilevare il livello di riempimento, al fine di ottimizzare le procedure di raccolta, garantendo altresì sempre una volumetria disponibile all’Utenza.”
L’applicativo proposto dalla sottoscritta simulerà i volumi presenti nei contenitori, permettendone poi la visualizzazione mediante tabelle. Inoltre sarà possibile trovare il percorso ottimizzato di raccolta (in base alla capacità dei mezzi disponibili e alla disponibilità degli operatori) abbassando così il consumo di carburante e le emissioni di CO2.

### Descrizione della rilevanza gestionale del problema

Si tratta di un progetto “reale”, per cui è stata anche appaltata la realizzazione di un sistema informatico in grado di monitorare il parco contenitori.
Le diverse funzionalità sopra elencate potranno essere sfruttate dal personale dell’azienda per controllare e pianificare la raccolta dei rifiuti.
L’ottimizzazione del percorso abbasserà il consumo di carburante (con un risparmio economico) e le emissioni di CO2 (riducendo l’impatto ambientale).

### Descrizione dei data-set per la valutazione	

Il data-set utilizzato è stato fornito dall’azienda ASP di Asti, in forma confidenziale.
Si tratta di una raccolta di dati relativa al posizionamento dei 1120 cassonetti nel comune di Asti realizzata dall’ufficio progettazione dell’igiene urbana.
Il data-set contiene i seguenti attributi relativi ai cassonetti:
- Id: codice identificativo aggiunto
- Latitudine 
- Longitudine 
- Indirizzo
- Tipo: carta, plastica, indifferenziata, vetro
- Dimensione: in Litri

Inoltre sono stati forniti dati necessari al calcolo del percorso di raccolta:
- Dimensione del mezzo adibito alla raccolta, in base al tipo di rifiuto
- Durata indicativa di un turno di raccolta
- Percentuale di riduzione dei rifiuti nel mezzo di raccolta
- Durata svuotamento cassonetto
- Durata svuotamento camion in discarica
- Velocità media camion
- Località discarica, in base al tipo di rifiuto

L’azienda ha condiviso tali informazioni esclusivamente per la scrittura della tesi di laurea e chiede la non divulgazione dei suddetti dati, vista la natura sperimentale del progetto e le future gare d’appalto. Resto a disposizione per eventuali chiarimenti e indicazioni sulla procedura da seguire.

### Descrizione preliminare degli algoritmi coinvolti	

Il data-set fornito dall’azienda è un file Excel, è dunque necessaria la conversione a CSV e successivamente in linguaggio SQL.
L’applicazione viene realizzata in linguaggio Java e segue i pattern DAO (Data Access Object) e MVC (Model View Controller), ottenendo una separazione tra accesso ai dati, interfaccia utente e logica applicativa. 

La prima funzionalità del tool è la simulazione dei volumi presenti nei contenitori (in base al tipo ti rifiuto scelto) e la seguente visualizzazione mediante tabella.
Dopo una query al database su tutti i cassonetti del tipo selezionato i contenitori verranno “riempiti” in modo casuale e poi ordinati in base alla percentuale di riempimento.
In futuro i cassonetti saranno dotati di sensori in grado di rilevare tale percentuale e si avrà a disposizione un database aggiornato in tempo reale.

La seconda funzionalità è quella più complessa: trovare il percorso di raccolta, in base al tipo di rifiuto selezionato, che minimizzi il tempo e lo spazio percorso e massimizzi la quantità raccolta, rispettando i vincoli di tempo disponibile e dimensione del camion.
Per fare ciò viene creato un grafo (completo, pesato e non orientato) in cui i vertici sono i cassonetti mentre gli archi rappresentano la distanza (in linea d’aria) tra ogni possibile coppia di contenitori. Verrà poi utilizzato un algoritmo ricorsivo in grado di trovare il percorso ottimo in base alle specifiche introdotte dall’utente. Al termine della ricorsione verrà mostrato il percorso e alcune statistiche.

### Descrizione preliminare delle funzionalità previste per l’applicazione software	

L’applicazione potrà essere utilizzata dal personale addetto alla pianificazione giornaliera del servizio vuotatura dei contenitori.
In una prima schermata l’addetto potrà visualizzare, selezionando la tipologia di rifiuto, il livello di riempimento dei cassonetti in tempo reale e la quantità totale di rifiuto prodotto. Grazie alla sua esperienza potrà decidere quale raccolta ha la priorità.
Nella schermata successiva, dopo aver scelto la tipologia di rifiuto, otterrà il percorso ottimizzato di raccolta. 
Inoltre potrà visualizzare alcune statistiche come il numero di cassonetti svuotati e non, la durata del viaggio, la quantità raccolta e quella rimanente.
Tali informazioni saranno presenti sia numericamente che graficamente e aiuteranno l’operatore a decidere se “accettare” o meno il percorso consigliato.
In caso affermativo otterrà ulteriori dettagli sul viaggio programmato da fornire all’autista.
Potrà poi decidere se pianificare un ulteriore giro di raccolta per i cassonetti esclusi dal percorso precedente o programmare la raccolta per altre tipologie di rifiuto.
In caso negativo può effettuare una nuova pianificazione, eventualmente modificando i parametri (durata viaggio e capacità mezzo).

**Comment by fulcorno** [comment]
Il problema è molto interessante sia dal punto di vista applicativo che algoritmico. Proposta accettata.

Per quanto riguarda la riservatezza dei dati, sarebbero necessari dei dati realistici per permettermi di valutarli (anche in forma confidenziale), e dei dati "anonimi" o "inventati" da caricare nel progetto, al fine di permettere a chiunque di scaricarlo e testarlo (anche se con dati non reali).
